"""
Market-data layer — Phase 13 architecture (docs/MARKET_DATA_PROPOSAL.md).

A SEPARATE module with a separate lifecycle from the client-FS loader:
`load_market_data()` has its own required-file set, so a market refresh
never touches a client load and vice versa (refresh independence,
decision d). Facts are APPEND-ONLY: revisions become new rows with newer
retrieval_timestamps; "current" and "point-in-time" are computed views,
never stored files.

Today every observation is the seed-42 SYNTHETIC history, re-platformed
into canonical rows with honest metadata (source=SYNTHETIC,
revision_status=SYNTHETIC, lineage to the generator script). The FRED
adapter below is coded and tested for URL/parse behavior, but the LIVE
source flip (preferred_source SYNTHETIC -> FRED, per metric) waits for
the owner's "reporting tool finalized" gate (DECISIONS #5) — and FRED,
like EDGAR, blocks hosted IPs (403 verified), so live fetches run from
the analyst's machine.
"""

import logging
import urllib.request
from io import StringIO
from pathlib import Path

import numpy as np
import pandas as pd

from financials import validator
from financials.loader import ClientFSValidationError, _coerce_types, _read_csv
from financials.schemas import (
    MARKET_METRIC_MASTER,
    MARKET_OBSERVATIONS,
)

log = logging.getLogger("financials.market")

BASE_DIR = Path(__file__).resolve().parents[2]
MARKET_DIR = BASE_DIR / "data" / "market"
SYNTHETIC_HISTORY = BASE_DIR / "data" / "raw" / "macro_history.csv"

# One fixed vintage stamp for the synthetic re-platform (deterministic;
# real fetches stamp their own retrieval time).
SYNTHETIC_RETRIEVAL = "2026-08-31T00:00:00Z"

_SYNTHETIC_COLUMNS = {
    "treasury_2y": "ust_2y",
    "treasury_10y": "ust_10y",
    "fed_funds": "fed_funds_eff",
    "cpi": "cpi_yoy",
    "unemployment": "unemployment_rate",
}


# Metrics generated by synthetic_macro_extensions(), derived from the
# base seed-42 history so the co-movements are coherent (spreads widen
# and growth dips when unemployment spikes). Honest labels throughout:
# plausible SYNTHETIC series for the learning build, never calibrated to
# any real market, replaced by FRED at the live cutover.
_EXTENSION_REFERENCE = "financials/market_data.py seed 42 (macro extensions)"


def synthetic_macro_extensions(wide: pd.DataFrame) -> pd.DataFrame:
    """
    Derive four more macro series from the base synthetic history.

    Formulas (documented so the teaching stays honest):
      pce_yoy         = cpi - 0.35 + smooth noise      (PCE runs below CPI)
      gdp_growth_yoy  = 2.6 - 0.55 x unemployment gap  (growth dips in stress)
      hy_oas          = 3.8 + 0.85 x unemployment gap  (spreads widen in stress)
      ig_oas          = 1.1 + 0.30 x (hy - min(hy))    (IG follows HY, damped)
    where "unemployment gap" = unemployment minus its series minimum and
    the noise is an AR(1)-smoothed draw from a seed-42 generator.
    """
    rng = np.random.default_rng(42)
    n = len(wide)

    def smooth(scale):
        shocks = rng.normal(0.0, scale, n)
        out = np.zeros(n)
        for i in range(1, n):
            out[i] = 0.85 * out[i - 1] + shocks[i]
        return out

    u_gap = wide["unemployment"] - wide["unemployment"].min()
    series = {
        "pce_yoy": ("PCT", wide["cpi"] - 0.35 + smooth(0.05)),
        "gdp_growth_yoy": ("PCT", 2.6 - 0.55 * u_gap + smooth(0.12)),
        "hy_oas": ("PCT_POINTS",
                   (3.8 + 0.85 * u_gap + smooth(0.15)).clip(lower=2.5)),
    }
    series["ig_oas"] = ("PCT_POINTS",
                        (1.1 + 0.30 * (series["hy_oas"][1]
                                       - series["hy_oas"][1].min())
                         + smooth(0.04)).clip(lower=0.7))

    rows = []
    for metric_id, (unit, values) in series.items():
        for date, value in zip(wide["date"], values):
            rows.append({
                "metric_id": metric_id,
                "observation_date": date.strftime("%Y-%m-%d"),
                "value": round(float(value), 6),
                "unit": unit,
                "source": "SYNTHETIC",
                "source_reference": _EXTENSION_REFERENCE,
                "retrieval_timestamp": SYNTHETIC_RETRIEVAL,
                "frequency": "MONTHLY",
                "revision_status": "SYNTHETIC",
            })
    return pd.DataFrame(rows, columns=MARKET_OBSERVATIONS.column_names())


# Second extension batch (owner request 2026-09-01): the headline monthly
# indicators the news cycle runs on. Same honesty contract - derived
# deterministically from the base seed-42 history on a SEPARATE random
# stream (seed 4242) so the earlier series stay byte-identical and the
# observation store stays append-only. Replaced by FRED at the cutover.
_HEADLINE_REFERENCE = "financials/market_data.py seed 4242 (headline indicators)"


def synthetic_headline_indicators(wide: pd.DataFrame,
                                  ext: pd.DataFrame) -> pd.DataFrame:
    """
    Nineteen more series, each a documented formula over the base
    history (and the first extension batch, passed in as `ext` wide):
    yields interpolate along the curve; core inflation damps headline;
    claims, duration and U-6 stretch the unemployment gap; payrolls move
    against the change in unemployment; housing starts fall when yields
    rise. Plausible co-movement for the learning build - never
    calibrated to any real market.
    """
    rng = np.random.default_rng(4242)
    n = len(wide)

    def smooth(scale):
        shocks = rng.normal(0.0, scale, n)
        out = np.zeros(n)
        for i in range(1, n):
            out[i] = 0.85 * out[i - 1] + shocks[i]
        return out

    u = wide["unemployment"]
    u_gap = u - u.min()
    du3 = u.diff().rolling(3, min_periods=1).mean().fillna(0.0)
    cpi = wide["cpi"]
    cpi_trend = cpi.rolling(12, min_periods=1).mean()
    gdp = ext["gdp_growth_yoy"]
    y10 = wide["treasury_10y"]

    series = {
        "ust_3m": ("PCT", wide["fed_funds"] + 0.05 + smooth(0.03)),
        "ust_5y": ("PCT", 0.45 * wide["treasury_2y"]
                   + 0.55 * y10 + smooth(0.04)),
        "ust_30y": ("PCT", y10 + 0.45 + smooth(0.05)),
        "core_cpi_yoy": ("PCT", 0.7 * cpi + 0.3 * cpi_trend
                         + 0.10 + smooth(0.04)),
        "core_pce_yoy": ("PCT", 0.7 * ext["pce_yoy"]
                         + 0.3 * ext["pce_yoy"].rolling(12, min_periods=1).mean()
                         + 0.05 + smooth(0.04)),
        "ppi_yoy": ("PCT", 1.4 * cpi - 0.5 + smooth(0.30)),
        "ahe_yoy": ("PCT", 2.8 + 0.45 * cpi_trend
                    - 0.15 * u_gap + smooth(0.08)),
        "retail_sales_yoy": ("PCT", 1.5 * gdp - 0.8 + smooth(0.50)),
        "indprod_yoy": ("PCT", 1.2 * gdp - 1.0 + smooth(0.35)),
        "u6_rate": ("PCT", 1.8 * u + 0.4 + smooth(0.08)),
        "participation_rate": ("PCT", 63.0 - 0.25 * u_gap
                               - 0.005 * np.arange(n) + smooth(0.05)),
        "unemp_duration_weeks": ("WEEKS",
                                 9.0 + 2.2 * u_gap.shift(3).fillna(0.0)
                                 + smooth(0.25)),
        "initial_claims_k": ("THOUSANDS",
                             (210 + 120 * u_gap + 900 * du3.clip(lower=0)
                              + smooth(15)).clip(lower=150)),
        "continuing_claims_k": ("THOUSANDS",
                                (1600 + 900 * u_gap.shift(1).fillna(0.0)
                                 + smooth(60)).clip(lower=1100)),
        "payroll_chg_k": ("THOUSANDS", 170 - 1500 * du3 + smooth(40)),
        "jolts_openings_k": ("THOUSANDS",
                             (7000 - 700 * u_gap + smooth(120))
                             .clip(lower=4500)),
        "housing_starts_k": ("THOUSANDS",
                             (1450 - 260 * (y10 - y10.mean())
                              - 120 * u_gap + smooth(35)).clip(lower=700)),
        "consumer_sentiment_idx": ("INDEX",
                                   95 - 6 * u_gap
                                   - 5 * (cpi - 2).clip(lower=0)
                                   + smooth(1.2)),
        "ism_pmi_idx": ("INDEX", 51 + 1.8 * (gdp - 2.0) + smooth(0.5)),
    }

    rows = []
    for metric_id, (unit, values) in series.items():
        for date, value in zip(wide["date"], values):
            rows.append({
                "metric_id": metric_id,
                "observation_date": date.strftime("%Y-%m-%d"),
                "value": round(float(value), 6),
                "unit": unit,
                "source": "SYNTHETIC",
                "source_reference": _HEADLINE_REFERENCE,
                "retrieval_timestamp": SYNTHETIC_RETRIEVAL,
                "frequency": "MONTHLY",
                "revision_status": "SYNTHETIC",
            })
    return pd.DataFrame(rows, columns=MARKET_OBSERVATIONS.column_names())


# Third extension batch (owner request 2026-09-02): commodities, sector
# indices, and firm-level price SLOTS. Separate seed-424242 stream so
# all prior series stay byte-identical. HONESTY BOUNDARY: the firm
# series carry placeholder names (TECH_CO_1..5, AI_CO_1..5), never real
# tickers - inventing a price history for a named real company would
# violate the no-invented-market-data rule even with a SYNTHETIC label.
# The owner assigns real tickers + a live equity source at the cutover.
_MARKETS_REFERENCE = "financials/market_data.py seed 424242 (commodities & equities)"


def synthetic_market_prices(wide: pd.DataFrame,
                            ext: pd.DataFrame) -> pd.DataFrame:
    """
    Sixteen price series derived from the macro world with documented
    behavior: gold catches a stress bid (rises with the unemployment
    gap), oil tracks growth and collapses in the 2020 shock, beef
    compounds with CPI, equity indices grow with drawdowns when yields
    rise, and the AI index steepens late-sample. Firm placeholders are
    their sector index times idiosyncratic noise.
    """
    rng = np.random.default_rng(424242)
    n = len(wide)
    t_idx = np.arange(n)

    def smooth(scale):
        shocks = rng.normal(0.0, scale, n)
        out = np.zeros(n)
        for i in range(1, n):
            out[i] = 0.85 * out[i - 1] + shocks[i]
        return out

    u_gap = wide["unemployment"] - wide["unemployment"].min()
    cpi = wide["cpi"]
    gdp = ext["gdp_growth_yoy"]
    y10 = wide["treasury_10y"]

    gold = 1300 * np.exp(0.004 * t_idx + 0.06 * smooth(0.5)) + 80 * u_gap
    silver = gold / (72 + 6 * smooth(0.3))
    oil = (58 + 8 * (gdp - 2.6) - 16 * (u_gap - 1).clip(lower=0)
           + 6 * (cpi - 2).clip(lower=0) + smooth(2.5)).clip(lower=15)
    beef = 3.7 * np.exp(np.cumsum(cpi.values / 1200.0)) + smooth(0.04)
    tech = 100 * np.exp(0.010 * t_idx + 0.08 * smooth(0.6)
                        - 0.05 * (y10 - y10.min()))
    ai = 100 * np.exp(0.006 * t_idx + 0.020 * (t_idx - 60).clip(min=0)
                      + 0.10 * smooth(0.6))

    series = {
        "gold_usd_oz": ("USD", gold),
        "silver_usd_oz": ("USD", silver),
        "oil_wti_usd_bbl": ("USD", oil),
        "beef_usd_lb": ("USD", beef),
        "tech_sector_idx": ("INDEX", tech),
        "ai_sector_idx": ("INDEX", ai),
    }
    for i in range(1, 6):
        scale = float(rng.uniform(0.4, 3.0))
        series[f"tech_co_{i}_px"] = (
            "USD", tech * scale * np.exp(0.12 * smooth(0.5)))
    for i in range(1, 6):
        scale = float(rng.uniform(0.2, 1.5))
        series[f"ai_co_{i}_px"] = (
            "USD", ai * scale * np.exp(0.16 * smooth(0.6)))

    rows = []
    for metric_id, (unit, values) in series.items():
        values = pd.Series(values)
        for date, value in zip(wide["date"], values):
            rows.append({
                "metric_id": metric_id,
                "observation_date": date.strftime("%Y-%m-%d"),
                "value": round(float(value), 6),
                "unit": unit,
                "source": "SYNTHETIC",
                "source_reference": _MARKETS_REFERENCE,
                "retrieval_timestamp": SYNTHETIC_RETRIEVAL,
                "frequency": "MONTHLY",
                "revision_status": "SYNTHETIC",
            })
    return pd.DataFrame(rows, columns=MARKET_OBSERVATIONS.column_names())


# Fourth extension batch (owner watchlist 2026-09-02): Brent crude only.
# Separate seed stream so all prior series stay byte-identical. The 15
# real companies on the same watchlist get NO synthetic series - a real
# name never carries an invented history; their data arrives via
# src/fetch_equity_prices.py run on the owner's machine.
_BRENT_REFERENCE = "financials/market_data.py seed 24242 (brent)"


def synthetic_brent(wide: pd.DataFrame,
                    markets_wide: pd.DataFrame) -> pd.DataFrame:
    """Brent rides WTI at a modest premium (quality/freight spread)."""
    rng = np.random.default_rng(24242)
    n = len(wide)
    shocks = rng.normal(0.0, 0.8, n)
    smooth = np.zeros(n)
    for i in range(1, n):
        smooth[i] = 0.85 * smooth[i - 1] + shocks[i]
    brent = (markets_wide["oil_wti_usd_bbl"].values + 3.5 + smooth).clip(min=17)
    rows = [{
        "metric_id": "brent_usd_bbl",
        "observation_date": date.strftime("%Y-%m-%d"),
        "value": round(float(value), 6),
        "unit": "USD",
        "source": "SYNTHETIC",
        "source_reference": _BRENT_REFERENCE,
        "retrieval_timestamp": SYNTHETIC_RETRIEVAL,
        "frequency": "MONTHLY",
        "revision_status": "SYNTHETIC",
    } for date, value in zip(wide["date"], brent)]
    return pd.DataFrame(rows, columns=MARKET_OBSERVATIONS.column_names())


def replatform_synthetic_history() -> pd.DataFrame:
    """Seed-42 history -> canonical observation rows, honestly labeled."""
    wide = pd.read_csv(SYNTHETIC_HISTORY, parse_dates=["date"])
    rows = []
    for column, metric_id in _SYNTHETIC_COLUMNS.items():
        for _, r in wide.iterrows():
            rows.append({
                "metric_id": metric_id,
                "observation_date": r["date"].strftime("%Y-%m-%d"),
                "value": round(float(r[column]), 6),
                "unit": "PCT",
                "source": "SYNTHETIC",
                "source_reference": "src/generate_history.py seed 42",
                "retrieval_timestamp": SYNTHETIC_RETRIEVAL,
                "frequency": "MONTHLY",
                "revision_status": "SYNTHETIC",
            })
    base = pd.DataFrame(rows, columns=MARKET_OBSERVATIONS.column_names())
    extensions = synthetic_macro_extensions(wide)
    ext_wide = extensions.pivot(index="observation_date",
                                columns="metric_id",
                                values="value").reset_index(drop=True)
    headline = synthetic_headline_indicators(wide, ext_wide)
    markets = synthetic_market_prices(wide, ext_wide)
    markets_wide = markets.pivot(index="observation_date",
                                 columns="metric_id",
                                 values="value").reset_index(drop=True)
    brent = synthetic_brent(wide, markets_wide)
    frame = pd.concat([base, extensions, headline, markets, brent],
                      ignore_index=True)
    return frame.sort_values(
        ["metric_id", "observation_date"]).reset_index(drop=True)


def load_market_data(market_dir=None, strict=True):
    """Independent market loader: its own files, its own validation."""
    market_dir = Path(market_dir) if market_dir else MARKET_DIR
    issues, tables = [], {}

    for schema in (MARKET_METRIC_MASTER, MARKET_OBSERVATIONS):
        path = market_dir / schema.filename
        if not path.exists():
            issues.append(validator.Issue(
                "ERROR", schema.table, "missing_file",
                f"required file not found: {path}",
            ))
            continue
        raw = _read_csv(path)
        issues.extend(validator.validate_table(raw, schema))
        tables[schema.table] = _coerce_types(raw, schema)

    if "market_metric_master" in tables and "market_observations" in tables:
        master = tables["market_metric_master"]
        obs = tables["market_observations"]

        known = set(master["metric_id"])
        bad = obs.index[~obs["metric_id"].isin(known)].tolist()
        if bad:
            issues.append(validator.Issue(
                "ERROR", "market_observations", "unknown_metric",
                f"metric_id not in market_metric_master — "
                f"{validator._rows(bad)}",
            ))

        expected_unit = dict(zip(master["metric_id"], master["unit"]))
        mismatched = obs.index[[
            expected_unit.get(m) not in (None, u)
            for m, u in zip(obs["metric_id"], obs["unit"])
        ]].tolist()
        if mismatched:
            issues.append(validator.Issue(
                "ERROR", "market_observations", "unit_mismatch",
                f"unit differs from the metric master — values are stored "
                f"as published, never rescaled — {validator._rows(mismatched)}",
            ))

    if strict and any(i.severity == "ERROR" for i in issues):
        raise ClientFSValidationError(issues)
    log.info("market layer loaded: %d metric(s), %d observation(s)",
             len(tables.get("market_metric_master", [])),
             len(tables.get("market_observations", [])))
    return tables, issues


def current_view(observations: pd.DataFrame) -> pd.DataFrame:
    """Latest known value per metric (max date, then max retrieval)."""
    ordered = observations.sort_values(
        ["metric_id", "observation_date", "retrieval_timestamp"]
    )
    return ordered.groupby("metric_id", as_index=False).last()


def point_in_time_view(observations: pd.DataFrame,
                       as_of: str) -> pd.DataFrame:
    """What was known ON a date: observations retrieved by then."""
    known = observations[observations["retrieval_timestamp"] <= as_of]
    return current_view(known) if len(known) else known


# ------------------------------------------------
# FRED ADAPTER — coded and unit-tested; live flip gated (DECISIONS #5)
# ------------------------------------------------

def fred_csv_url(series_id: str) -> str:
    """Keyless official CSV endpoint (blocked from hosted IPs; run locally)."""
    return f"https://fred.stlouisfed.org/graph/fredgraph.csv?id={series_id}"


def parse_fred_csv(csv_text: str, metric_id: str, unit: str,
                   frequency: str, retrieval_timestamp: str) -> pd.DataFrame:
    """FRED CSV ('DATE,<SERIES>' with '.' for missing) -> canonical rows."""
    frame = pd.read_csv(StringIO(csv_text))
    frame.columns = [c.strip().lower() for c in frame.columns]
    date_col, value_col = frame.columns[0], frame.columns[1]
    frame = frame[frame[value_col] != "."]        # gaps stay absent, never filled
    return pd.DataFrame({
        "metric_id": metric_id,
        "observation_date": frame[date_col],
        "value": pd.to_numeric(frame[value_col]),
        "unit": unit,
        "source": "FRED",
        "source_reference": f"fredgraph.csv id={value_col.upper()}",
        "retrieval_timestamp": retrieval_timestamp,
        "frequency": frequency,
        "revision_status": "FINAL",
    })[MARKET_OBSERVATIONS.column_names()]


def fetch_fred_series(series_id: str, timeout=60) -> str:
    request = urllib.request.Request(
        fred_csv_url(series_id),
        headers={"User-Agent": "Finance-ML-learning-project"},
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.read().decode("utf-8")


# The Page 5 curated export: monthly history with 24-month rolling means.
ROLLING_WINDOW = 24
HISTORY_METRICS = (
    "ust_3m", "ust_2y", "ust_5y", "ust_10y", "ust_30y",
    "curve_spread_10y_2y", "curve_spread_10y_3m", "fed_funds_eff",
    "cpi_yoy", "core_cpi_yoy", "pce_yoy", "core_pce_yoy", "ppi_yoy",
    "ahe_yoy", "gdp_growth_yoy", "indprod_yoy", "retail_sales_yoy",
    "unemployment_rate", "u6_rate", "participation_rate",
    "unemp_duration_weeks", "initial_claims_k", "continuing_claims_k",
    "payroll_chg_k", "jolts_openings_k", "housing_starts_k",
    "consumer_sentiment_idx", "ism_pmi_idx", "ig_oas", "hy_oas",
    "gold_usd_oz", "silver_usd_oz", "oil_wti_usd_bbl", "brent_usd_bbl", "beef_usd_lb",
    "tech_sector_idx", "ai_sector_idx",
    "tech_co_1_px", "tech_co_2_px", "tech_co_3_px", "tech_co_4_px",
    "tech_co_5_px",
    "ai_co_1_px", "ai_co_2_px", "ai_co_3_px", "ai_co_4_px", "ai_co_5_px",
)
HISTORY_OUTPUT = BASE_DIR / "reports" / "market_history_rolling24.csv"


def rolling_24m_history(observations: pd.DataFrame) -> pd.DataFrame:
    """
    Wide monthly frame: each metric's as-observed value plus its rolling
    24-month mean (blank until a full 24-month window exists - a partial
    window would be a different, misleading statistic). Latest vintage
    per (metric, date); the curve spread is derived on the fly per its
    registered derivation_rule (ust_10y - ust_2y).
    """
    latest = (observations.sort_values("retrieval_timestamp")
              .groupby(["metric_id", "observation_date"]).tail(1))
    wide = (latest.pivot(index="observation_date", columns="metric_id",
                         values="value").sort_index())
    wide["curve_spread_10y_2y"] = wide["ust_10y"] - wide["ust_2y"]
    wide["curve_spread_10y_3m"] = wide["ust_10y"] - wide["ust_3m"]

    out = pd.DataFrame({"observation_date":
                        pd.to_datetime(wide.index).strftime("%Y-%m-%d")})
    for metric in HISTORY_METRICS:
        out[metric] = wide[metric].round(4).values
        out[f"{metric}_r24"] = (wide[metric]
                                .rolling(ROLLING_WINDOW,
                                         min_periods=ROLLING_WINDOW)
                                .mean().round(4).values)
    out["source"] = "SYNTHETIC"
    out["value_class"] = "MARKET_DATA"
    return out


# Windowed history (Page 5 toggle): the same series at several trailing
# windows plus calendar year-to-date. Long format - one row per (month,
# window) - so a single page picker swaps every chart at once. Labels
# are zero-padded so they sort naturally in a picker.
HISTORY_WINDOWS = {"03M": 3, "06M": 6, "12M": 12, "24M": 24}
WINDOWS_OUTPUT = BASE_DIR / "reports" / "market_history_windows.csv"


def windowed_history(observations: pd.DataFrame) -> pd.DataFrame:
    """
    For each window label: the trailing mean with min_periods equal to
    the window (partial windows stay blank - same honesty rule as the
    24-month export). YTD is the calendar year-to-date mean: January
    equals the month itself, December averages the whole year.
    """
    latest = (observations.sort_values("retrieval_timestamp")
              .groupby(["metric_id", "observation_date"]).tail(1))
    wide = (latest.pivot(index="observation_date", columns="metric_id",
                         values="value").sort_index())
    wide["curve_spread_10y_2y"] = wide["ust_10y"] - wide["ust_2y"]
    wide["curve_spread_10y_3m"] = wide["ust_10y"] - wide["ust_3m"]
    wide = wide[list(HISTORY_METRICS)]

    frames = []
    for label, months in HISTORY_WINDOWS.items():
        smoothed = wide.rolling(months, min_periods=months).mean()
        smoothed.insert(0, "window", label)
        frames.append(smoothed)
    year = pd.Series(pd.to_datetime(wide.index).year, index=wide.index)
    ytd = wide.groupby(year, group_keys=False).apply(
        lambda g: g.expanding().mean())
    ytd.insert(0, "window", "YTD")
    frames.append(ytd)

    out = pd.concat(frames)
    out = out.reset_index().rename(columns={"index": "observation_date"})
    out["observation_date"] = pd.to_datetime(
        out["observation_date"]).dt.strftime("%Y-%m-%d")
    # Zoom helper: 0 = the latest month, 1 = the month before, ... so a
    # "last N months" view is a simple filter months_ago <= N-1.
    dates = sorted(out["observation_date"].unique(), reverse=True)
    out.insert(2, "months_ago",
               out["observation_date"].map({d: i for i, d in enumerate(dates)}))
    for metric in HISTORY_METRICS:
        out[metric] = out[metric].round(4)
    out["source"] = "SYNTHETIC"
    out["value_class"] = "MARKET_DATA"
    return (out.sort_values(["window", "observation_date"])
            .reset_index(drop=True))
