/// Curated pipeline export reports/client_fs_statements.csv: the
/// consolidated statement detail with view flags and adjustment /
/// transaction lineage. Full source lineage (file, sheet, row) lives
/// one layer down in data/client_fs/client_fs_normalized.csv.
table client_fs_statements
	lineageTag: a4446162-3113-45cc-8848-2bf0e50ba320

	/// Anchor: the latest period in the statement detail - every ratio
	/// below reads this year, nothing hard-coded.
	measure 'Stmt Latest Period' =
			
			CALCULATE(MAX(client_fs_statements[period_id]), ALL(client_fs_statements))
		displayFolder: Ratios
		lineageTag: 61de7d89-77ce-41e1-a876-06ef8a7d3943

	measure 'Current Assets ($M)' =
			
			CALCULATE(
			    SUM(client_fs_statements[amount_reporting]),
			    FILTER(
			        ALL(client_fs_statements),
			        client_fs_statements[period_id] = [Stmt Latest Period]
			            && client_fs_statements[reported_or_adjusted] = "REPORTED"
			            && client_fs_statements[statement_section] = "current_assets"
			    )
			)
		formatString: #,0.0
		displayFolder: Ratios
		lineageTag: 56c7a3cf-e914-43c8-b70f-df41061a147f

	measure 'Current Liabilities ($M)' =
			
			CALCULATE(
			    SUM(client_fs_statements[amount_reporting]),
			    FILTER(
			        ALL(client_fs_statements),
			        client_fs_statements[period_id] = [Stmt Latest Period]
			            && client_fs_statements[reported_or_adjusted] = "REPORTED"
			            && client_fs_statements[statement_section] = "current_liabilities"
			    )
			)
		formatString: #,0.0
		displayFolder: Ratios
		lineageTag: 21cf25de-3b7f-43ca-a4cb-3d91a6ce07c0

	measure 'Cash (BS) ($M)' =
			
			CALCULATE(
			    SUM(client_fs_statements[amount_reporting]),
			    FILTER(
			        ALL(client_fs_statements),
			        client_fs_statements[period_id] = [Stmt Latest Period]
			            && client_fs_statements[reported_or_adjusted] = "REPORTED"
			            && client_fs_statements[standard_account_id] = "cash"
			    )
			)
		formatString: #,0.0
		displayFolder: Ratios
		lineageTag: d8d784a2-3be2-4212-8ae8-772648e6d328

	measure 'Inventory (BS) ($M)' =
			
			CALCULATE(
			    SUM(client_fs_statements[amount_reporting]),
			    FILTER(
			        ALL(client_fs_statements),
			        client_fs_statements[period_id] = [Stmt Latest Period]
			            && client_fs_statements[reported_or_adjusted] = "REPORTED"
			            && client_fs_statements[standard_account_id] = "inventory"
			    )
			)
		formatString: #,0.0
		displayFolder: Ratios
		lineageTag: 88e2f1c6-cc0c-4605-af12-1b289ff572e3

	/// Current assets excluding inventory - what could pay bills fast.
	measure 'Quick Assets ($M)' =
			
			[Current Assets ($M)] - [Inventory (BS) ($M)]
		formatString: #,0.0
		displayFolder: Ratios
		lineageTag: 9dad2141-69b9-421f-b041-9b312e661f02

	measure 'Total Equity ($M)' =
			
			CALCULATE(
			    SUM(client_fs_statements[amount_reporting]),
			    FILTER(
			        ALL(client_fs_statements),
			        client_fs_statements[period_id] = [Stmt Latest Period]
			            && client_fs_statements[reported_or_adjusted] = "REPORTED"
			            && client_fs_statements[statement_section] = "equity"
			    )
			)
		formatString: #,0.0
		displayFolder: Ratios
		lineageTag: 129052a3-6373-4d77-941f-8f3d9be50482

	/// Canonical IS signs make expenses negative; flipped positive for
	/// display and the coverage ratio.
	measure 'Interest Expense ($M)' =
			
			-1 *
			CALCULATE(
			    SUM(client_fs_statements[amount_reporting]),
			    FILTER(
			        ALL(client_fs_statements),
			        client_fs_statements[period_id] = [Stmt Latest Period]
			            && client_fs_statements[reported_or_adjusted] = "REPORTED"
			            && client_fs_statements[standard_account_id] = "interest_expense"
			    )
			)
		formatString: #,0.0
		displayFolder: Ratios
		lineageTag: c014d002-288e-4ba2-a059-b97c03f07ca2

	measure 'COGS ($M)' =
			
			-1 *
			CALCULATE(
			    SUM(client_fs_statements[amount_reporting]),
			    FILTER(
			        ALL(client_fs_statements),
			        client_fs_statements[period_id] = [Stmt Latest Period]
			            && client_fs_statements[reported_or_adjusted] = "REPORTED"
			            && client_fs_statements[standard_account_id] = "cogs"
			    )
			)
		formatString: #,0.0
		displayFolder: Ratios
		lineageTag: 05e55824-01a3-47c9-89d8-fef37e8e42dc

	/// Liquidity: can current assets cover current liabilities? Below
	/// 1.0x means bills come due faster than assets turn to cash.
	measure 'Current Ratio (x)' =
			
			DIVIDE([Current Assets ($M)], [Current Liabilities ($M)])
		formatString: 0.00"x"
		displayFolder: Ratios
		lineageTag: 431f19c4-4a28-40ac-8208-5485678cae98

	measure 'Quick Ratio (x)' =
			
			DIVIDE([Quick Assets ($M)], [Current Liabilities ($M)])
		formatString: 0.00"x"
		displayFolder: Ratios
		lineageTag: 96447789-e7b1-4a95-b10e-d1801780657d

	measure 'Cash Ratio (x)' =
			
			DIVIDE([Cash (BS) ($M)], [Current Liabilities ($M)])
		formatString: 0.00"x"
		displayFolder: Ratios
		lineageTag: 51dc0de2-24b6-43c8-959e-610352e9bafd

	/// Solvency: how the capital structure splits between lenders and
	/// owners, at book value.
	measure 'Debt / Equity (x)' =
			
			DIVIDE([Client Total Debt ($M)], [Total Equity ($M)])
		formatString: 0.00"x"
		displayFolder: Ratios
		lineageTag: 1a1f3883-b524-481f-918f-8e2f5c08480e

	/// EBIT over interest expense - how many times operating profit
	/// covers the interest bill.
	measure 'Interest Coverage (x)' =
			
			DIVIDE([Client EBIT ($M)], [Interest Expense ($M)])
		formatString: 0.0"x"
		displayFolder: Ratios
		lineageTag: 4e2dba46-e5d4-49fc-a5fd-8d092729e453

	/// APPROXIMATION: COGS stands in for variable cost - the books do
	/// not tag fixed vs variable, so this is gross-margin-as-contribution
	/// with the assumption stated.
	measure 'Contribution ($M)' =
			
			[Client Revenue ($M)] - [COGS ($M)]
		formatString: #,0.0
		displayFolder: Ratios
		lineageTag: 609547fe-cb4d-4c13-9db2-f20c41f30ab8

	measure 'Contribution Margin (%)' =
			
			100 * DIVIDE([Contribution ($M)], [Client Revenue ($M)])
		formatString: 0.0
		displayFolder: Ratios
		lineageTag: 34fd9354-6236-4b9f-9d29-04f75d7a79a2

	/// ASSUMPTION: share of revenue that recurs. The statements do not
	/// tag recurring vs one-time - until the client provides the split,
	/// this is an owned input shown on its own card.
	measure 'Recurring Share (%) (Assumption)' =
			
			65.0
		formatString: 0.0
		displayFolder: Ratios
		lineageTag: 581cf667-40ac-4476-aedd-2bb977b3dea8

	/// Annual recurring revenue = the assumed recurring share times
	/// revenue. Quality-of-revenue lens, honest about its assumption.
	measure 'ARR ($M)' =
			
			DIVIDE([Recurring Share (%) (Assumption)], 100)
			    * [Client Revenue ($M)]
		formatString: #,0.0
		displayFolder: Ratios
		lineageTag: 69f1f5ff-5e82-4205-b781-9479ed016917

	/// UFCF spread monthly. Positive = the business FUNDS itself;
	/// negative would be a burn rate.
	measure 'Cash Generated per Month ($M)' =
			
			DIVIDE([Client UFCF ($M)], 12)
		formatString: #,0.0
		displayFolder: Ratios
		lineageTag: eaa5eec9-5527-460a-b3a2-f0944ed321d5

	/// Months of cash left at the current burn - N/A when there is no
	/// burn, stated rather than a fake number.
	measure 'Cash Runway' =
			
			IF(
			    [Client UFCF ($M)] >= 0,
			    "N/A - self-funding: cash grows ~$" &
			        FORMAT([Cash Generated per Month ($M)], "0.0") & "M/mo",
			    FORMAT(DIVIDE([Cash (BS) ($M)],
			        -[Cash Generated per Month ($M)]), "0.0") & " months of cash"
			)
		displayFolder: Ratios
		lineageTag: b7e3c487-06bb-453d-b435-2359ddbf448a

	/// Operating expenses from the IS detail (canonical sign
	/// flipped positive for the build-out row).
	measure 'Opex ($M)' =
			
			-1 *
			CALCULATE(
			    SUM(client_fs_statements[amount_reporting]),
			    FILTER(
			        ALL(client_fs_statements),
			        client_fs_statements[period_id] = [Stmt Latest Period]
			            && client_fs_statements[reported_or_adjusted] = "REPORTED"
			            && client_fs_statements[standard_account_id] = "opex"
			    )
			)
		formatString: #,0.0
		displayFolder: Calc Build-Out
		lineageTag: c13f7174-c0ff-4764-8d7b-4e824b311a1f

	/// EBITDA rebuilt line-by-line from the statements; must equal
	/// the pipeline's EBITDA - the check card proves it.
	measure 'EBITDA (Built) ($M)' =
			
			[Client Revenue ($M)] - [COGS ($M)] - [Opex ($M)]
		formatString: #,0.0
		displayFolder: Calc Build-Out
		lineageTag: 99266664-ed00-4796-8dbe-a85162a6ae8a

	/// Rebuilt minus pipeline - must read 0.00.
	measure 'EBITDA Build Check ($M)' =
			
			ROUND([EBITDA (Built) ($M)] - [Client EBITDA ($M)], 6) + 0
		formatString: 0.00
		displayFolder: Calc Build-Out
		lineageTag: 20a3dd9c-6baf-4aee-a563-c9a22c009c83

	/// Operating cash flow, indirect method: start at net income, add
	/// back the non-cash D&A, subtract the cash tied up in working
	/// capital. Taxes and interest are already inside net income.
	measure 'OCF Indirect ($M)' =
			
			[Net Income Reported ($M)] + [Client D&A ($M)]
			    - [Client Change in NWC ($M)]
		formatString: #,0.0
		displayFolder: Calc Build-Out
		lineageTag: 77604651-1a5a-47d0-8188-cd716aeda920

	/// Free cash flow TO EQUITY-side readers: what is left after
	/// reinvestment, with interest already paid inside net income.
	measure 'Levered FCF ($M)' =
			
			[OCF Indirect ($M)] - [Client CapEx ($M)]
		formatString: #,0.0
		displayFolder: Calc Build-Out
		lineageTag: 0d83a6b1-1f2c-463a-9a19-b3ea857b0acd

	/// Interest x (1 - tax): what debt truly costs after the shield.
	/// The exact wedge between levered FCF and UFCF.
	measure 'After-Tax Interest ($M)' =
			
			[Interest Expense ($M)] * [Client After-Tax Factor]
		formatString: #,0.0
		displayFolder: Calc Build-Out
		lineageTag: 67bb1c85-3ea5-402e-b0cb-1258fc31fac0

	/// Levered FCF + after-tax interest must equal UFCF exactly -
	/// the two cash-flow definitions differ ONLY by where debt is
	/// charged (in the flows vs in the WACC).
	measure 'FCF Bridge Check ($M)' =
			
			ROUND([Levered FCF ($M)] + [After-Tax Interest ($M)]
			    - [Client UFCF ($M)], 6) + 0
		formatString: 0.00
		displayFolder: Calc Build-Out
		lineageTag: fab0c2d3-794f-48b8-8ba0-85b1e9b9b16a

	/// Backed out of the pipeline's market-value weights: since
	/// E/(E+D) and D/(E+D) are known and D = 366, E = D x We/Wd.
	measure 'Market Cap (Implied) ($M)' =
			
			DIVIDE([Client Total Debt ($M)] * [Equity Weight], [Debt Weight])
		formatString: #,0.0
		displayFolder: Calc Build-Out
		lineageTag: 9ac29854-e801-4204-8965-e2a7639b2510

	/// The market price the weights were built from - $18.00 in the
	/// fixture (the shares_dilution input), vs the DCF's $28.86.
	measure 'Market Price per Share (Implied $)' =
			
			DIVIDE([Market Cap (Implied) ($M)], [Client Diluted Shares (M)])
		formatString: "$"#,0.00
		displayFolder: Calc Build-Out
		lineageTag: 7e96ab1e-fb56-436b-9617-6a6725cfbd9b

	measure 'Capital E plus D ($M)' =
			
			[Market Cap (Implied) ($M)] + [Client Total Debt ($M)]
		formatString: #,0.0
		displayFolder: Calc Build-Out
		lineageTag: 39b1431a-dae8-47fb-9922-825ef7ce890f

	/// The company-side cost of debt: actual interest paid over debt
	/// carried (6.94%) - compare with the market-built Kd of 6.53%.
	measure 'Book Interest Rate (%)' =
			
			100 * DIVIDE([Interest Expense ($M)], [Client Total Debt ($M)])
		formatString: 0.00
		displayFolder: Calc Build-Out
		lineageTag: d91187f8-a2c2-40d4-8d69-3c92751afd40

	column entity_id
		dataType: string
		lineageTag: 17fc8e23-2bd6-4340-b839-3702349b04fb
		summarizeBy: none
		sourceColumn: entity_id

		annotation SummarizationSetBy = Automatic

	column period_id
		dataType: string
		lineageTag: f627ecae-9af2-4e41-86f1-bd173ce93a82
		summarizeBy: none
		sourceColumn: period_id

		annotation SummarizationSetBy = Automatic

	column statement_type
		dataType: string
		lineageTag: 16fecb59-0053-44e8-a31b-62af480140a2
		summarizeBy: none
		sourceColumn: statement_type

		annotation SummarizationSetBy = Automatic

	column statement_section
		dataType: string
		lineageTag: de98147b-b679-4481-ac6c-b27f2507c370
		summarizeBy: none
		sourceColumn: statement_section

		annotation SummarizationSetBy = Automatic

	column standard_account_id
		dataType: string
		lineageTag: f67f7e45-6e4c-4f7d-93de-7dc18fd71607
		summarizeBy: none
		sourceColumn: standard_account_id

		annotation SummarizationSetBy = Automatic

	column standard_account_name
		dataType: string
		lineageTag: 88c88c12-a96c-4705-83f1-f4efac7ed729
		summarizeBy: none
		sourceColumn: standard_account_name

		annotation SummarizationSetBy = Automatic

	column reported_or_adjusted
		dataType: string
		lineageTag: e3305235-e5d3-40b6-a8ef-be1dd2f727a1
		summarizeBy: none
		sourceColumn: reported_or_adjusted

		annotation SummarizationSetBy = Automatic

	column adjustment_id
		dataType: string
		lineageTag: 5c0e2361-7064-4016-ac09-39a6d1ddb515
		summarizeBy: none
		sourceColumn: adjustment_id

		annotation SummarizationSetBy = Automatic

	column transaction_id
		dataType: string
		lineageTag: 00236b3a-9736-4bb4-9a72-1be0ac3b61bc
		summarizeBy: none
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column amount_reporting
		dataType: double
		lineageTag: 1889060d-36d1-4e4e-9238-e1efc02551b5
		summarizeBy: none
		sourceColumn: amount_reporting

		annotation SummarizationSetBy = Automatic

	partition client_fs_statements = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\client_fs_statements.csv"),
				    [Delimiter = ",", Columns = 16, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"entity_id", "period_id", "statement_type", "statement_section", "standard_account_id", "standard_account_name", "reported_or_adjusted", "adjustment_id", "transaction_id", "amount_reporting"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {{"amount_reporting", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

