table finance_scenario_report
	lineageTag: 73db8991-ec28-458a-91ca-ad6800a16878

	measure 'Enterprise Value Billions' =
			
			DIVIDE(
			    SUM(finance_scenario_report[enterprise_value]),
			    1000
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Valuation
		lineageTag: 36ce741b-bde3-4261-84b2-0cb0a198b708

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Measure 4'
		displayFolder: Other
		lineageTag: 1f6a2b25-1cb4-46f1-9806-052e474841be

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Selected Implied Share Price' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[implied_share_price]),
			    CALCULATE(
			        MAX(finance_scenario_report[implied_share_price]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		displayFolder: Valuation
		lineageTag: a59a617e-fbfb-4216-970f-9e4fb23b2e42

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected WACC' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[wacc_pct]),
			    CALCULATE(
			        MAX(finance_scenario_report[wacc_pct]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		displayFolder: Cost of Capital & Market
		lineageTag: afd61705-a8b8-4a4d-b1ac-d5da316b4103

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Enterprise Value Billions' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    DIVIDE(
			        SELECTEDVALUE(finance_scenario_report[enterprise_value]),
			        1000
			    ),
			    CALCULATE(
			        DIVIDE(
			            MAX(finance_scenario_report[enterprise_value]),
			            1000
			        ),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		displayFolder: Valuation
		lineageTag: 19d99471-91a1-4802-ad3f-532b0379d1ab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Equity Value Billions' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    DIVIDE(
			        SELECTEDVALUE(finance_scenario_report[equity_value]),
			        1000
			    ),
			    CALCULATE(
			        DIVIDE(
			            MAX(finance_scenario_report[equity_value]),
			            1000
			        ),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Valuation
		lineageTag: 64644d82-aae7-4a03-a5a3-e9e823206a13

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// CLIENT F/S + CALCULATED: debt less eligible cash; bridges enterprise to equity value. Derived from the consolidated balance sheet since the cutover.
	/// Net debt from the pipeline (total debt 366 - cash 194 = 172, statement-derived);
	/// was a hard-coded 0.35 literal until the 2026-09-01 fix.
	measure 'Net Debt Billions' =
			
			DIVIDE(
			    SELECTEDVALUE(finance_scenario_report[net_debt]),
			    1000
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Valuation
		lineageTag: 51f93b43-faf3-4eb7-8f0b-8eef8a18b67a

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// MODEL OUTPUT today: a 10-year yield predicted by the internal model on synthetic data. Target: observed 10Y Treasury with source, maturity, and as-of date (see market_rf_policy).
	measure 'Selected Risk-Free Rate' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[risk_free_rate_pct]),
			    CALCULATE(
			        MAX(finance_scenario_report[risk_free_rate_pct]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		formatString: 0.00
		displayFolder: Cost of Capital & Market
		lineageTag: b929af84-a9ba-4c85-a513-cac123acfb23

	measure 'Selected Treasury 2Y' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[treasury_2y]),
			    CALCULATE(
			        MAX(finance_scenario_report[treasury_2y]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		formatString: 0.00
		displayFolder: Cost of Capital & Market
		lineageTag: b5e9f721-9dd2-43c5-8a64-f34301002dd0

	/// ASSUMPTION: equity beta (1.20). At the live phase this comes from
	/// peer-set regression; until then it is an explicit, labeled input.
	measure 'Selected Beta' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[beta]),
			    CALCULATE(
			        MAX(finance_scenario_report[beta]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		formatString: 0.00
		displayFolder: Cost of Capital & Market
		lineageTag: 5e17120e-23dc-4f72-ba67-5c7f5cf662f3

	/// ASSUMPTION: equity risk premium in points (4.50), dated and owned -
	/// never an invented market observation.
	measure 'Selected Equity Risk Premium' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[equity_risk_premium_pct]),
			    CALCULATE(
			        MAX(finance_scenario_report[equity_risk_premium_pct]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		formatString: 0.00
		displayFolder: Cost of Capital & Market
		lineageTag: 3d374613-ccc3-4b18-a8ba-fcc2c26b2ec6

	/// ASSUMPTION: credit spread over the risk-free rate (2.00pts),
	/// benchmarked against IG/HY OAS when live market data lands.
	measure 'Selected Credit Spread' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[credit_spread_pct]),
			    CALCULATE(
			        MAX(finance_scenario_report[credit_spread_pct]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		formatString: 0.00
		displayFolder: Cost of Capital & Market
		lineageTag: f5162c3b-ab2a-475e-bcc3-af2c71ffb14d

	/// MACRO CONTEXT: informs the scenario narrative and the assumptions -
	/// never plugged into WACC directly (docs/MODEL_AUDIT.md map W).
	measure 'Selected CPI' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[cpi]),
			    CALCULATE(
			        MAX(finance_scenario_report[cpi]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		formatString: 0.00
		displayFolder: Cost of Capital & Market
		lineageTag: 6b68a92e-9fa0-4ad8-ab73-bca7efaec1f2

	/// MACRO CONTEXT: same role as CPI - context for the scenario, not a
	/// WACC input.
	measure 'Selected Unemployment' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[unemployment]),
			    CALCULATE(
			        MAX(finance_scenario_report[unemployment]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		formatString: 0.00
		displayFolder: Cost of Capital & Market
		lineageTag: 2ed51572-534b-427e-b228-bdb675b07982

	/// Explicit assumption: the hurdle sits 2.00pts above WACC, so a
	/// project must clear financing cost plus a margin of safety.
	measure 'Hurdle Premium (pts)' =
			
			[Hurdle Rate (%)] - [Calculated WACC]
		formatString: 0.00
		displayFolder: Cost of Capital & Market
		lineageTag: d95f7ae9-de5b-4bfb-ab7c-c55b47186099

	/// Return on invested capital minus the cost of that capital -
	/// positive means operations create value over financing cost.
	measure 'ROIC WACC Spread (pts)' =
			
			[ROIC Check (%)] - [Calculated WACC]
		formatString: 0.00
		displayFolder: Capital Allocation
		lineageTag: 2262db04-d0c7-46c8-bace-560f4392fc99

	measure 'Selected Fed Funds' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[fed_funds]),
			    CALCULATE(
			        MAX(finance_scenario_report[fed_funds]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		formatString: 0.00
		displayFolder: Cost of Capital & Market
		lineageTag: cabb4c18-47ef-4fc9-a463-a6ceb1c914e2

	measure Measure
		displayFolder: Other
		lineageTag: 6257dd60-9fd9-4186-b06b-2f8cccdf58c1

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Selected Cost of Equity' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[cost_of_equity_pct]),
			    CALCULATE(
			        MAX(finance_scenario_report[cost_of_equity_pct]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		formatString: 0.00
		displayFolder: Cost of Capital & Market
		lineageTag: e86b0c64-506c-461a-b09e-288b3699dc57

	measure 'Selected Cost of Debt' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[cost_of_debt_pct]),
			    CALCULATE(
			        MAX(finance_scenario_report[cost_of_debt_pct]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		formatString: 0.00
		displayFolder: Cost of Capital & Market
		lineageTag: f8bacb5d-3689-4667-9563-e5ddfc8f77e9

	/// CALCULATED since the 2026-08-31 cutover: market value of equity / total capitalization (was an assumed 70%).
	measure 'Equity Weight' =
			
			SELECTEDVALUE(finance_scenario_report[equity_weight_pct]) / 100
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Cost of Capital & Market
		lineageTag: 98ecae62-3c88-4df2-a4a5-e7cc49f37a6e

	/// CALCULATED since the 2026-08-31 cutover: debt / total capitalization (was an assumed 30%).
	measure 'Debt Weight' =
			
			SELECTEDVALUE(finance_scenario_report[debt_weight_pct]) / 100
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Cost of Capital & Market
		lineageTag: a819fe9d-c3fb-4e1d-917f-28ed6ead3729

	measure 'Tax Rate' =
			
			SELECTEDVALUE(finance_scenario_report[tax_rate_pct]) / 100
		formatString: 0%;-0%;0%
		displayFolder: Cost of Capital & Market
		lineageTag: 376e4071-7b40-4c81-8406-2e640620dbc4

	/// CALCULATED: weighted average required return of debt and equity used to discount unlevered free cash flow.
	measure 'Calculated WACC' =
			
			VAR EquityWeight =
			    SELECTEDVALUE(finance_scenario_report[equity_weight_pct]) / 100
			VAR DebtWeight =
			    SELECTEDVALUE(finance_scenario_report[debt_weight_pct]) / 100
			VAR CostEquity =
			    SELECTEDVALUE(finance_scenario_report[cost_of_equity_pct]) / 100
			VAR CostDebt =
			    SELECTEDVALUE(finance_scenario_report[cost_of_debt_pct]) / 100
			VAR TaxRate =
			    SELECTEDVALUE(finance_scenario_report[tax_rate_pct]) / 100
			RETURN
			    (
			        EquityWeight * CostEquity
			        + DebtWeight * CostDebt * (1 - TaxRate)
			    ) * 100
		displayFolder: Cost of Capital & Market
		lineageTag: 89cf55fc-cad2-4f31-8acd-eff6013181c2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Equity WACC Contribution' =
			
			VAR EquityWeight =
			    SELECTEDVALUE(finance_scenario_report[equity_weight_pct]) / 100
			VAR CostEquity =
			    SELECTEDVALUE(finance_scenario_report[cost_of_equity_pct]) / 100
			RETURN
			    EquityWeight * CostEquity * 100
		displayFolder: Cost of Capital & Market
		lineageTag: f854f773-f830-4f58-bb1d-384b16ee0293

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Debt WACC Contribution' =
			
			VAR DebtWeight =
			    SELECTEDVALUE(finance_scenario_report[debt_weight_pct]) / 100
			VAR CostDebt =
			    SELECTEDVALUE(finance_scenario_report[cost_of_debt_pct]) / 100
			VAR TaxRate =
			    SELECTEDVALUE(finance_scenario_report[tax_rate_pct]) / 100
			RETURN
			    DebtWeight * CostDebt * (1 - TaxRate) * 100
		displayFolder: Cost of Capital & Market
		lineageTag: 7120391e-9a47-4ce2-8886-585fa9a708f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// CALCULATED since the cutover: year-1 unlevered free cash flow from the driver-based forecast (client_fs_ufcf), replacing the old hard-coded 100.
	measure 'FCF Year 1' =
			
			VAR ForecastYears =
			    TOPN(
			        1,
			        FILTER(
			            ALL(client_fs_ufcf),
			            client_fs_ufcf[forecast_method] = "DRIVER_BASED"
			        ),
			        client_fs_ufcf[period_id], ASC
			    )
			RETURN
			    MAXX(
			        TOPN(1, ForecastYears, client_fs_ufcf[period_id], DESC),
			        client_fs_ufcf[ufcf]
			    )
		formatString: 0.0
		displayFolder: Valuation
		lineageTag: bd62f282-08c4-455e-93cc-4d1cc1574144

	measure 'FCF Year 2' =
			
			VAR ForecastYears =
			    TOPN(
			        2,
			        FILTER(
			            ALL(client_fs_ufcf),
			            client_fs_ufcf[forecast_method] = "DRIVER_BASED"
			        ),
			        client_fs_ufcf[period_id], ASC
			    )
			RETURN
			    MAXX(
			        TOPN(1, ForecastYears, client_fs_ufcf[period_id], DESC),
			        client_fs_ufcf[ufcf]
			    )
		formatString: 0.0
		displayFolder: Valuation
		lineageTag: 1c01f057-0a11-48ea-84ba-b1289050184f

	measure 'FCF Year 3' =
			
			VAR ForecastYears =
			    TOPN(
			        3,
			        FILTER(
			            ALL(client_fs_ufcf),
			            client_fs_ufcf[forecast_method] = "DRIVER_BASED"
			        ),
			        client_fs_ufcf[period_id], ASC
			    )
			RETURN
			    MAXX(
			        TOPN(1, ForecastYears, client_fs_ufcf[period_id], DESC),
			        client_fs_ufcf[ufcf]
			    )
		formatString: 0.0
		displayFolder: Valuation
		lineageTag: a1948eca-980f-4d0e-a038-4b5b1ebbca6e

	measure 'FCF Year 4' =
			
			VAR ForecastYears =
			    TOPN(
			        4,
			        FILTER(
			            ALL(client_fs_ufcf),
			            client_fs_ufcf[forecast_method] = "DRIVER_BASED"
			        ),
			        client_fs_ufcf[period_id], ASC
			    )
			RETURN
			    MAXX(
			        TOPN(1, ForecastYears, client_fs_ufcf[period_id], DESC),
			        client_fs_ufcf[ufcf]
			    )
		formatString: 0.0
		displayFolder: Valuation
		lineageTag: 2f39496e-d75c-493c-8f7f-0cd7d8e68e12

	measure 'FCF Year 5' =
			
			VAR ForecastYears =
			    TOPN(
			        5,
			        FILTER(
			            ALL(client_fs_ufcf),
			            client_fs_ufcf[forecast_method] = "DRIVER_BASED"
			        ),
			        client_fs_ufcf[period_id], ASC
			    )
			RETURN
			    MAXX(
			        TOPN(1, ForecastYears, client_fs_ufcf[period_id], DESC),
			        client_fs_ufcf[ufcf]
			    )
		formatString: 0.0
		displayFolder: Valuation
		lineageTag: 6860d4f8-a24c-44e1-93c9-fb01d7fabd12

	measure 'Selected Terminal Growth' =
			
			IF(
			    HASONEVALUE(finance_scenario_report[scenario]),
			    SELECTEDVALUE(finance_scenario_report[terminal_growth_pct]),
			    CALCULATE(
			        MAX(finance_scenario_report[terminal_growth_pct]),
			        finance_scenario_report[scenario] = "Base"
			    )
			)
		displayFolder: Valuation
		lineageTag: 4ac8d20c-28bb-4c52-9c32-02203199ebee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// CALCULATED: value of cash flows beyond year 5 via Gordon growth - FCF5 x (1+g) / (WACC - g).
	measure 'Terminal Value' =
			
			VAR FCF5 =
			    [FCF Year 5]
			
			VAR GrowthRate =
			    [Selected Terminal Growth] / 100
			
			VAR WACCRate =
			    [Calculated WACC] / 100
			
			RETURN
			    DIVIDE(
			        FCF5 * (1 + GrowthRate),
			        WACCRate - GrowthRate
			    )
		displayFolder: Valuation
		lineageTag: 88ccc624-9991-45d2-a6f5-99b62ba839c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// CALCULATED: terminal value discounted back 5 years at WACC.
	measure 'PV Terminal Value' =
			
			VAR TerminalValue =
			    [Terminal Value]
			
			VAR WACCRate =
			    [Calculated WACC] / 100
			
			RETURN
			    DIVIDE(
			        TerminalValue,
			        (1 + WACCRate) ^ 5
			    )
		displayFolder: Valuation
		lineageTag: a8be89a3-5446-478b-afd0-ac841e5f3175

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PV FCF Year 1' =
			
			VAR WACCRate =
			    [Calculated WACC] / 100
			RETURN
			    DIVIDE(
			        [FCF Year 1],
			        (1 + WACCRate) ^ 1
			    )
		displayFolder: Valuation
		lineageTag: 0630293e-23da-47f6-9b0e-41f4e1a29ba7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PV FCF Year 2' =
			
			VAR WACCRate =
			    [Calculated WACC] / 100
			RETURN
			    DIVIDE(
			        [FCF Year 2],
			        (1 + WACCRate) ^ 2
			    )
		displayFolder: Valuation
		lineageTag: 56271dbc-bbba-4802-96d2-a57b297d17cd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PV FCF Year 3' =
			
			VAR WACCRate =
			    [Calculated WACC] / 100
			RETURN
			    DIVIDE(
			        [FCF Year 3],
			        (1 + WACCRate) ^ 3
			    )
		displayFolder: Valuation
		lineageTag: 7a8cf941-e254-4f61-8282-c00eca184083

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PV FCF Year 4' =
			
			VAR WACCRate =
			    [Calculated WACC] / 100
			RETURN
			    DIVIDE(
			        [FCF Year 4],
			        (1 + WACCRate) ^ 4
			    )
		displayFolder: Valuation
		lineageTag: dba37e9c-7de6-4878-9178-f77a5313e116

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PV FCF Year 5' =
			
			VAR WACCRate =
			    [Calculated WACC] / 100
			RETURN
			    DIVIDE(
			        [FCF Year 5],
			        (1 + WACCRate) ^ 5
			    )
		displayFolder: Valuation
		lineageTag: 600cb868-9e60-4534-9d74-11d4dcc0caa7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PV FCF Years 1-5' =
			
			[PV FCF Year 1]
			+ [PV FCF Year 2]
			+ [PV FCF Year 3]
			+ [PV FCF Year 4]
			+ [PV FCF Year 5]
		displayFolder: Valuation
		lineageTag: 32e725ba-6a85-4d16-83e7-67f7c957d78c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// CALCULATED: PV of forecast FCF plus PV of terminal value - the value of the whole business.
	measure 'DCF Enterprise Value' =
			
			[PV FCF Years 1-5] + [PV Terminal Value]
		displayFolder: Valuation
		lineageTag: e1264990-5c8e-4c84-bb53-4be917956178

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DCF Equity Value' =
			
			[DCF Enterprise Value]
			- SELECTEDVALUE(finance_scenario_report[net_debt])
		displayFolder: Valuation
		lineageTag: 26ffc607-b422-4cf7-92ee-35acae7f4f6d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DCF Implied Share Price' =
			
			VAR EquityValue =
			    [DCF Equity Value]
			VAR SharesOutstanding =
			    SELECTEDVALUE(finance_scenario_report[shares_outstanding])
			RETURN
			    DIVIDE(
			        EquityValue,
			        SharesOutstanding
			    )
		displayFolder: Valuation
		lineageTag: 222bf99a-2953-4303-8a31-1a5b472de39d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Terminal Value % of EV' =
			
			DIVIDE(
			    [PV Terminal Value],
			    [DCF Enterprise Value]
			)
		formatString: 0%;-0%;0%
		displayFolder: Scenario Diagnostics
		lineageTag: 77443163-4d57-474c-bc63-be2e441aa729

	measure 'FCF Years 1-5 % of EV' =
			
			DIVIDE(
			    [PV FCF Years 1-5],
			    [DCF Enterprise Value]
			)
		formatString: 0%;-0%;0%
		displayFolder: Scenario Diagnostics
		lineageTag: a03fb28e-8b40-47ad-a328-58f17a53d673

	measure 'DCF EV Reconciliation' =
			
			VAR Difference =
			    [DCF Enterprise Value]
			    - SELECTEDVALUE(finance_scenario_report[enterprise_value])
			RETURN
			    IF(
			        ABS(Difference) < 0.01,
			        0,
			        Difference
			    )
		formatString: #,0.00
		displayFolder: Scenario Diagnostics
		lineageTag: 3a8d1557-342d-494f-b3f8-de603dfe7e92

	measure 'Share Price Change vs Base %' =
			
			VAR CurrentPrice =
			    [DCF Implied Share Price]
			VAR BasePrice =
			    CALCULATE(
			        [DCF Implied Share Price],
			        ALL(finance_scenario_report[scenario]),
			        finance_scenario_report[scenario] = "Base"
			    )
			RETURN
			    DIVIDE(
			        CurrentPrice - BasePrice,
			        BasePrice
			    )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Scenario Diagnostics
		lineageTag: 2a09e2ad-31af-4689-a267-4a50749b8fd6

	measure 'Share Price Change vs Base $' =
			
			VAR CurrentPrice =
			    [DCF Implied Share Price]
			VAR BasePrice =
			    CALCULATE(
			        [DCF Implied Share Price],
			        ALL(finance_scenario_report[scenario]),
			        finance_scenario_report[scenario] = "Base"
			    )
			RETURN
			    CurrentPrice - BasePrice
		displayFolder: Scenario Diagnostics
		lineageTag: 4ed7e6d1-cd1a-4cd6-bd57-9a95541bc9ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Share Price Scenario Range' =
			
			VAR LowPrice =
			    CALCULATE(
			        [DCF Implied Share Price],
			        ALL(finance_scenario_report[scenario]),
			        finance_scenario_report[scenario] = "Lower Rate"
			    )
			VAR HighPrice =
			    CALCULATE(
			        [DCF Implied Share Price],
			        ALL(finance_scenario_report[scenario]),
			        finance_scenario_report[scenario] = "Higher Rate"
			    )
			RETURN
			    LowPrice - HighPrice
		displayFolder: Decision Display
		lineageTag: 6563c311-158f-4bde-9a66-dd74df6c9063

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACC Multiply Symbol' = "×"
		displayFolder: Formatting Symbols
		lineageTag: 3b33056c-818b-45f5-ae74-9ea0ee7a893d

	measure 'WACC Equals Symbol' = "="
		displayFolder: Formatting Symbols
		lineageTag: 6c145761-6d5a-412a-8980-a9d8e38ca27b

	measure 'Measure 2'
		displayFolder: Other
		lineageTag: 1c299eb8-cc58-4c21-a07e-0b3c0b7230a6

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Measure 3'
		displayFolder: Other
		lineageTag: 113631e1-6bd4-4da6-8248-6397faf26fe4

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Measure 5'
		displayFolder: Other
		lineageTag: 273c43af-0c39-449f-ab76-99cabf5f0498

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'After Tax Debt Factor' =
			
			1 - [Tax Rate]
		displayFolder: Cost of Capital & Market
		lineageTag: 8afeb084-26c5-4f4b-93bb-2643d13c7654

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Measure 6'
		displayFolder: Other
		lineageTag: d59512db-59db-42d6-8f00-c6fff71fbb68

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'WACC Plus Symbol' = "+"
		displayFolder: Formatting Symbols
		lineageTag: 24f438aa-6ed0-4dc7-92fb-c932515de582

	measure 'Minus Symbol' = "−"
		displayFolder: Formatting Symbols
		lineageTag: a3ba9253-f88d-42ff-bdd5-2b14e2bb7506

	measure 'Divide Symbol' = "÷"
		displayFolder: Formatting Symbols
		lineageTag: ccf64d40-498e-4a09-95bc-3eccc73ba5cf

	measure 'Terminal Growth Factor' =
			
			1 + ([Selected Terminal Growth] / 100)
		formatString: 0.000
		displayFolder: Valuation
		lineageTag: 05efe15e-abd9-4bd1-ba63-62401c86f490

	measure 'WACC Less Growth' =
			
			([Calculated WACC] - [Selected Terminal Growth]) / 100
		formatString: 0.0000
		displayFolder: Cost of Capital & Market
		lineageTag: afdcc2ac-1567-4289-b9b6-84dee1cb3643

	measure 'WACC Discount Factor Year 5' =
			
			(1 + ([Calculated WACC] / 100)) ^ 5
		formatString: 0.000
		displayFolder: Valuation
		lineageTag: d4565170-fdc0-4d64-b42a-73a2d2f42fd9

	measure 'EV Change vs Base %' =
			
			VAR CurrentEV =
			    [Selected Enterprise Value Billions]
			
			VAR BaseEV =
			    CALCULATE(
			        [Selected Enterprise Value Billions],
			        REMOVEFILTERS(finance_scenario_report[scenario]),
			        finance_scenario_report[scenario] = "Base"
			    )
			
			RETURN
			    DIVIDE(CurrentEV - BaseEV, BaseEV)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Scenario Diagnostics
		lineageTag: 2a0dfb5a-d539-44b9-b71c-212baacda7e7

	measure 'Equity Value Change vs Base %' =
			
			VAR CurrentEquity =
			    [Selected Equity Value Billions]
			
			VAR BaseEquity =
			    CALCULATE(
			        [Selected Equity Value Billions],
			        REMOVEFILTERS(finance_scenario_report[scenario]),
			        finance_scenario_report[scenario] = "Base"
			    )
			
			RETURN
			    DIVIDE(CurrentEquity - BaseEquity, BaseEquity)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Scenario Diagnostics
		lineageTag: 7deb88c4-521e-4dd5-bf97-b489e37d587d

	measure 'WACC Change vs Base' =
			
			VAR CurrentWACC =
			    [Calculated WACC]
			
			VAR BaseWACC =
			    CALCULATE(
			        [Calculated WACC],
			        REMOVEFILTERS(finance_scenario_report[scenario]),
			        finance_scenario_report[scenario] = "Base"
			    )
			
			RETURN
			    CurrentWACC - BaseWACC
		displayFolder: Scenario Diagnostics
		lineageTag: 03f255ae-a86b-41c3-8160-5a4ca698523f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Risk-Free Rate Change vs Base' =
			
			VAR CurrentRate =
			    [Selected Risk-Free Rate]
			
			VAR BaseRate =
			    CALCULATE(
			        [Selected Risk-Free Rate],
			        REMOVEFILTERS(finance_scenario_report[scenario]),
			        finance_scenario_report[scenario] = "Base"
			    )
			
			RETURN
			    CurrentRate - BaseRate
		displayFolder: Scenario Diagnostics
		lineageTag: af20fa36-64b9-46ff-930f-f51e2fa84f30

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cost of Equity Change vs Base' =
			
			VAR CurrentCOE =
			    [Selected Cost of Equity]
			
			VAR BaseCOE =
			    CALCULATE(
			        [Selected Cost of Equity],
			        REMOVEFILTERS(finance_scenario_report[scenario]),
			        finance_scenario_report[scenario] = "Base"
			    )
			
			RETURN
			    CurrentCOE - BaseCOE
		displayFolder: Scenario Diagnostics
		lineageTag: d79f6afb-e56a-4c5e-b9fc-1bb38a51c24f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cost of Debt Change vs Base' =
			
			VAR CurrentCOD =
			    [Selected Cost of Debt]
			
			VAR BaseCOD =
			    CALCULATE(
			        [Selected Cost of Debt],
			        REMOVEFILTERS(finance_scenario_report[scenario]),
			        finance_scenario_report[scenario] = "Base"
			    )
			
			RETURN
			    CurrentCOD - BaseCOD
		displayFolder: Scenario Diagnostics
		lineageTag: 702ea5e9-2f67-4686-8e14-d07bcdd42ab6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DCF Enterprise Value ($B)' =
			
			DIVIDE(
			    [DCF Enterprise Value],
			    1000
			)
		displayFolder: Valuation
		lineageTag: 5062fb91-c722-4edc-8dfb-75fddcf3b03b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DCF Equity Value ($B)' =
			
			DIVIDE(
			    [DCF Equity Value],
			    1000
			)
		displayFolder: Valuation
		lineageTag: d226cdd4-d3bd-4910-b20a-97d411932f64

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PV Terminal Value ($B)' =
			
			DIVIDE(
			    [PV Terminal Value],
			    1000
			)
		displayFolder: Valuation
		lineageTag: ee677f95-1467-425f-9bda-192e52e6002b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Terminal Value ($B)' =
			
			DIVIDE(
			    [Terminal Value],
			    1000
			)
		displayFolder: Valuation
		lineageTag: 139502fa-bb78-464c-aee0-89b6bcf486c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Invested Capital Display' =
			
			FORMAT(
			    SELECTEDVALUE(finance_scenario_report[invested_capital]),
			    "#,##0"
			)
		displayFolder: Other
		lineageTag: 1fe0f108-b517-4d5b-bcfb-bb3e3473cb0e

	/// CALCULATED: NOPAT / component-built invested capital (operating NWC + net PP&E). Statement-derived since the cutover.
	measure 'ROIC Check (%)' =
			
			DIVIDE(
			    SELECTEDVALUE(finance_scenario_report[nopat]),
			    SELECTEDVALUE(finance_scenario_report[invested_capital])
			) * 100
		displayFolder: ROIC
		lineageTag: ffb4ac0d-68fc-48be-ae91-c72524c3258c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ROIC Value Creation Status' =
			
			VAR ROIC =
			    [ROIC Check (%)]
			VAR WACC =
			    [Calculated WACC]
			RETURN
			    SWITCH(
			        TRUE(),
			        ROIC > WACC, "Value Creating",
			        ROIC < WACC, "Value Destroying",
			        "Value Neutral"
			    )
		displayFolder: ROIC
		lineageTag: 35872bf0-5d06-4b08-9ad5-abc459c78a38

	/// ANALYST ASSUMPTION: WACC + 2.00pt project risk premium. Read from the versioned pipeline column since the cutover (was a DAX-only constant).
	measure 'Hurdle Rate (%)' =
			
			SELECTEDVALUE(finance_scenario_report[hurdle_rate_pct])
		displayFolder: Capital Allocation
		lineageTag: b805ef31-b464-43cc-93bd-23f91a109687

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// ANALYST ASSUMPTION: explicit project budget, deliberately decoupled from invested capital.
	measure 'Initial Investment ($M)' =
			
			1500
		formatString: 0
		displayFolder: Capital Allocation
		lineageTag: 996c7b91-7ea7-4d96-b375-8942d3e4888b

	measure 'Project PV of Cash Flows ($M)' =
			
			VAR r = [Hurdle Rate (%)] / 100
			RETURN
			    DIVIDE([FCF Year 1], (1 + r)^1) +
			    DIVIDE([FCF Year 2], (1 + r)^2) +
			    DIVIDE([FCF Year 3], (1 + r)^3) +
			    DIVIDE([FCF Year 4], (1 + r)^4) +
			    DIVIDE([FCF Year 5], (1 + r)^5)
		displayFolder: Capital Allocation
		lineageTag: f373881b-ef22-4986-9f2e-d10d10eceda8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Project Terminal Value ($M)' =
			
			VAR FCF5 = [FCF Year 5]
			VAR g = [Selected Terminal Growth] / 100
			VAR r = [Hurdle Rate (%)] / 100
			RETURN
			    DIVIDE(
			        FCF5 * (1 + g),
			        r - g
			    )
		displayFolder: Capital Allocation
		lineageTag: 4fa7bc45-f690-4d9d-bbdb-4bcb2bde823c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Project PV Terminal Value ($M)' =
			
			VAR TV = [Project Terminal Value ($M)]
			VAR r = [Hurdle Rate (%)] / 100
			RETURN
			    DIVIDE(
			        TV,
			        (1 + r)^5
			    )
		displayFolder: Capital Allocation
		lineageTag: 2751beae-9cff-4501-aaf3-1210346b8489

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// CALCULATED: PV of project cash flows at the hurdle rate minus the initial investment.
	measure 'Project NPV ($M)' =
			
			[Project PV of Cash Flows ($M)]
			+ [Project PV Terminal Value ($M)]
			- [Initial Investment ($M)]
		displayFolder: Capital Allocation
		lineageTag: d6cc8f8c-97f5-4825-a587-b162dcc0374a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'NPV Decision' =
			
			IF(
			    [Project NPV ($M)] > 0,
			    "ACCEPT — Creates Value",
			    IF(
			        [Project NPV ($M)] < 0,
			        "REJECT — Destroys Value",
			        "NEUTRAL"
			    )
			)
		displayFolder: Capital Allocation
		lineageTag: 65bc22a5-f97a-4c22-8fe3-45abdbe365cc

	/// CALCULATED: the discount rate that zeroes project NPV, on the same hurdle-basis cash-flow set as the NPV panel.
	measure 'Project IRR (%)' =
			
			SELECTEDVALUE(finance_scenario_report[project_irr_pct])
		displayFolder: Capital Allocation
		lineageTag: bfcca1aa-3b65-4ca4-ba20-49066b227016

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'IRR Decision' =
			
			IF(
			    [Project IRR (%)] > [Hurdle Rate (%)],
			    "ACCEPT — IRR Above Hurdle",
			    "REJECT — IRR Below Hurdle"
			)
		formatString: 0
		displayFolder: Capital Allocation
		lineageTag: 06f0bacb-5bb2-4f16-82de-4c3454a049f6

	measure 'IRR - Hurdle Spread (pts)' =
			
			[Project IRR (%)] - [Hurdle Rate (%)]
		displayFolder: Capital Allocation
		lineageTag: 92d59c8a-5962-42d3-a761-af48ec24ba1b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'IRR Margin Status' =
			
			SWITCH(
			    TRUE(),
			    [IRR - Hurdle Spread (pts)] > 0, "PASS — Clears Hurdle",
			    [IRR - Hurdle Spread (pts)] = 0, "BREAKEVEN",
			    "FAIL — Below Hurdle"
			)
		displayFolder: Capital Allocation
		lineageTag: b84e8692-62dd-49f7-9001-2fef7f2bedb1

	measure 'IRR Investment Decision' =
			
			IF(
			    [IRR - Hurdle Spread (pts)] > 0,
			    "INVEST",
			    "DO NOT INVEST"
			)
		displayFolder: Capital Allocation
		lineageTag: 11b586a6-ab02-46f4-836c-a40f6e6887e2

	/// MODEL OUTPUT: APPROVE only if NPV > 0 and IRR > hurdle and ROIC > WACC.
	measure 'Investment Recommendation' =
			
			IF(
			    [Project NPV ($M)] > 0
			        && [IRR - Hurdle Spread (pts)] > 0
			        && SELECTEDVALUE(finance_scenario_report[roic_wacc_spread_pct]) > 0,
			    "APPROVE — Creates Value",
			    "REJECT — Does Not Create Value"
			)
		displayFolder: Capital Allocation
		lineageTag: 6f39faac-acf6-4dd9-b420-27a5bb88abdf

	measure 'ROIC Range Green' =
			
			"● Value Creating: ROIC > WACC"
		displayFolder: Decision Display
		lineageTag: d673c3b8-63d6-4380-a881-157bf14c1f71

	measure 'IRR Decision Range' =
			
			"Strong: IRR > Hurdle Rate" & UNICHAR(10) &
			"Break-even: IRR = Hurdle Rate" & UNICHAR(10) &
			"Reject: IRR < Hurdle Rate"
		displayFolder: Decision Display
		lineageTag: 1fc6cf7c-f43a-405c-86cb-c2569dbf2a26

	measure 'NPV Decision Range' =
			
			"Accept: NPV > $0"
			    & UNICHAR(13) & UNICHAR(10) &
			"Break-even: NPV = $0"
			    & UNICHAR(13) & UNICHAR(10) &
			"Reject: NPV < $0"
		displayFolder: Decision Display
		lineageTag: aa9ee09d-7049-4ba3-864c-0b1e664f9043

	measure 'Measure 7'
		displayFolder: Other
		lineageTag: 18a3ebb0-6d4a-4390-9002-5bee62ee496b

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Investment Recommendation Range' =
			
			"APPROVE: NPV > $0 AND ROIC > WACC AND IRR > Hurdle"
			& UNICHAR(10) &
			"REVIEW: Mixed results across the three tests"
			& UNICHAR(10) &
			"REJECT: NPV < $0 AND ROIC < WACC AND IRR < Hurdle"
		displayFolder: Decision Display
		lineageTag: 37fd4f31-7961-4814-a63e-b45df007bdf4

	measure 'ROIC Range Green Color' =
			
			"#107C10"
		displayFolder: Decision Colors
		lineageTag: 7a8e441b-3c12-449e-a3a8-18571fd7aba5

	measure 'ROIC Range Neutral' =
			
			"● Break-even: ROIC = WACC"
		displayFolder: Decision Display
		lineageTag: 7e43dd12-08db-4d28-abc4-cf5cb990333d

	measure 'ROIC Range Neutral Color' =
			
			"#404040"
		displayFolder: Decision Colors
		lineageTag: 61c01568-6569-4328-a11a-f581d478d540

	measure 'ROIC Range Red' =
			
			"● Value Destroying: ROIC < WACC"
		displayFolder: Decision Display
		lineageTag: a91fd283-55b1-4f18-bcee-5e454ef366a0

	measure 'ROIC Range Red Color' =
			
			"#C42B1C"
		displayFolder: Decision Colors
		lineageTag: 8d01279b-d83d-49a7-bed0-c519af8e269e

	measure 'ROIC Decision Range Display' =
			
			[ROIC Range Green]
			    & UNICHAR(10) &
			[ROIC Range Neutral]
			    & UNICHAR(10) &
			[ROIC Range Red]
		displayFolder: Decision Display
		lineageTag: f9bc9d3f-f580-468a-8741-ad7660a2a71b

	measure 'ROIC Status Color' =
			
			VAR ROICValue = [ROIC Check (%)]
			VAR WACCValue = [Calculated WACC]
			RETURN
			    SWITCH(
			        TRUE(),
			        ROICValue > WACCValue, "#107C10",
			        ROICValue = WACCValue, "#404040",
			        ROICValue < WACCValue, "#C42B1C",
			        "#404040"
			    )
		displayFolder: Decision Colors
		lineageTag: 2187759d-29f9-492a-a956-94345ec71603

	measure 'IRR Decision Range Display' =
			
			"● Strong: IRR > Hurdle Rate"
			    & UNICHAR(13) & UNICHAR(10) &
			"● Break-even: IRR = Hurdle Rate"
			    & UNICHAR(13) & UNICHAR(10) &
			"● Reject: IRR < Hurdle Rate"
		displayFolder: Decision Display
		lineageTag: b50ae982-77b5-4e3e-ad19-deecf57e5d07

	measure 'IRR Status Color' =
			
			VAR IRRValue = [Project IRR (%)]
			VAR HurdleValue = [Hurdle Rate (%)]
			RETURN
			    SWITCH(
			        TRUE(),
			        IRRValue > HurdleValue, "#107C10",
			        IRRValue = HurdleValue, "#404040",
			        IRRValue < HurdleValue, "#C42B1C",
			        "#404040"
			    )
		displayFolder: Decision Colors
		lineageTag: 5e8d5422-3b07-4b14-a6fc-a2b68146f79c

	measure 'NPV Decision Color' =
			
			VAR NPVValue = [Project NPV ($M)]
			RETURN
			    SWITCH(
			        TRUE(),
			        NPVValue > 0, "#107C10",
			        NPVValue = 0, "#404040",
			        NPVValue < 0, "#C42B1C",
			        "#404040"
			    )
		displayFolder: Decision Colors
		lineageTag: f34b1289-7162-4676-a6f8-1a29ecd87dcd

	measure 'Investment Recommendation Color' =
			
			VAR NPVValue = [Project NPV ($M)]
			
			VAR ROICValue =
			    SELECTEDVALUE(finance_scenario_report[roic_pct])
			
			VAR WACCValue =
			    [Calculated WACC]
			
			VAR IRRValue =
			    [Project IRR (%)]
			
			VAR HurdleValue =
			    [Hurdle Rate (%)]
			
			VAR PassNPV =
			    NPVValue > 0
			
			VAR PassROIC =
			    ROICValue > WACCValue
			
			VAR PassIRR =
			    IRRValue > HurdleValue
			
			RETURN
			    SWITCH(
			        TRUE(),
			        PassNPV && PassROIC && PassIRR, "#107C10",
			        NOT PassNPV && NOT PassROIC && NOT PassIRR, "#C42B1C",
			        "#0078D4"
			    )
		displayFolder: Decision Colors
		lineageTag: 8a93486d-9cf9-4f6c-a9ab-d4d33a386345

	measure 'IRR Investment Decision Color' =
			
			VAR IRRValue = [Project IRR (%)]
			VAR HurdleValue = [Hurdle Rate (%)]
			
			RETURN
			    SWITCH(
			        TRUE(),
			        IRRValue > HurdleValue, "#107C10",
			        IRRValue = HurdleValue, "#404040",
			        IRRValue < HurdleValue, "#C42B1C",
			        "#404040"
			    )
		displayFolder: Decision Colors
		lineageTag: b60cc9aa-3ccf-4054-a2a9-377ffc264e3c

	measure 'IRR Comparison Symbol' =
			
			VAR IRRValue = [Project IRR (%)]
			VAR HurdleValue = [Hurdle Rate (%)]
			
			RETURN
			    SWITCH(
			        TRUE(),
			        IRRValue > HurdleValue, ">",
			        IRRValue < HurdleValue, "<",
			        "="
			    )
		displayFolder: Formatting Symbols
		lineageTag: 86c366d0-a026-4173-8498-f8ce7aa3ee76

	measure 'Measure 8'
		displayFolder: Other
		lineageTag: 83c02707-042e-41ae-b7db-1d5f8c7a7e2e

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Hurdle vs IRR Symbol' =
			
			VAR IRRValue = [Project IRR (%)]
			VAR HurdleValue = [Hurdle Rate (%)]
			
			RETURN
			    SWITCH(
			        TRUE(),
			        HurdleValue < IRRValue, "<",
			        HurdleValue > IRRValue, ">",
			        "="
			    )
		displayFolder: Formatting Symbols
		lineageTag: 8adcf421-b6ad-4bb3-989d-35e0cf9e1f0e

	measure 'NPV Comparison Symbol' =
			
			VAR NPVValue = [Project NPV ($M)]
			RETURN
			    SWITCH(
			        TRUE(),
			        NPVValue > 0, ">",
			        NPVValue < 0, "<",
			        "="
			    )
		displayFolder: Formatting Symbols
		lineageTag: f1488f90-f6f0-487c-8cef-3fcdb904759e

	measure 'IRR Investment Range Green' =
			
			"● INVEST: IRR > Hurdle Rate"
		displayFolder: Decision Display
		lineageTag: 27a308e2-9a11-461c-9045-1904db5c2c86

	measure 'IRR Investment Decision Range' =
			
			"INVEST: IRR > Hurdle Rate"
			& UNICHAR(13) & UNICHAR(10) &
			"REVIEW: IRR = Hurdle Rate"
			& UNICHAR(13) & UNICHAR(10) &
			"REJECT: IRR < Hurdle Rate"
		displayFolder: Decision Display
		lineageTag: ea536573-41a5-4d06-b969-95f5830055d5

	measure 'IRR Margin Status Range' =
			
			"PASS: IRR > Hurdle Rate"
			& UNICHAR(13) & UNICHAR(10) &
			"BREAK-EVEN: IRR = Hurdle Rate"
			& UNICHAR(13) & UNICHAR(10) &
			"FAIL: IRR < Hurdle Rate"
		displayFolder: Decision Display
		lineageTag: 13f2007f-8820-45e7-9a2e-1ff60993156c

	measure 'IRR Decision Color' =
			
			VAR IRRValue = [Project IRR (%)]
			VAR HurdleValue = [Hurdle Rate (%)]
			
			RETURN
			    SWITCH(
			        TRUE(),
			        IRRValue > HurdleValue, "#107C10",
			        IRRValue = HurdleValue, "#404040",
			        IRRValue < HurdleValue, "#C42B1C",
			        "#404040"
			    )
		displayFolder: Decision Colors
		lineageTag: 40621376-ef45-41cb-8d1c-d0648098e0a8

	measure 'Zero Value' = 0
		formatString: 0
		displayFolder: Other
		lineageTag: c9b05837-ca37-41ed-8c5a-6f99c7b5e08d

	/// Diluted share count in millions from the pipeline (treasury-stock
	/// method); replaces the raw Sum(shares_outstanding) column binding so
	/// the implied-price row reads 103.7, not a rounded 104.
	measure 'Diluted Shares (M)' =
			
			SELECTEDVALUE(finance_scenario_report[shares_outstanding])
		formatString: #,0.0
		displayFolder: Valuation
		lineageTag: 08523db3-ebad-49ce-b2ab-5378326c671a

	measure 'PV FCF Years 1-5 ($B)' =
			
			DIVIDE(
			    [PV FCF Years 1-5],
			    1000
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Valuation
		lineageTag: c02a3b46-14c0-403d-ae2c-f079ea1ec388

	measure 'ROIC vs WACC Symbol' =
			
			VAR ROICValue = [ROIC Check (%)]
			VAR WACCValue = [Calculated WACC]
			RETURN
			    SWITCH(
			        TRUE(),
			        ROICValue > WACCValue, ">",
			        ROICValue < WACCValue, "<",
			        "="
			    )
		displayFolder: Formatting Symbols
		lineageTag: 76cf6c49-cf15-4c38-8a8f-c5011c597825

	column scenario
		dataType: string
		lineageTag: 15dcaa33-2851-4c39-8e5a-970fc8629fcc
		summarizeBy: none
		sourceColumn: scenario
		sortByColumn: scenario_sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column treasury_2y
		dataType: double
		lineageTag: 516e5e38-67dd-492c-83e9-e6239ee827e0
		summarizeBy: sum
		sourceColumn: treasury_2y

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fed_funds
		dataType: double
		lineageTag: 28e10a01-cfca-4369-a224-47916b3c9e18
		summarizeBy: sum
		sourceColumn: fed_funds

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cpi
		dataType: double
		lineageTag: c15e1518-80be-48e7-a767-c8598e11c316
		summarizeBy: sum
		sourceColumn: cpi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unemployment
		dataType: double
		lineageTag: 9a2fbaa3-6a00-4dbf-a768-7465bfc73f7f
		summarizeBy: sum
		sourceColumn: unemployment

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column risk_free_rate_pct
		dataType: double
		lineageTag: 87b9340c-09bd-43e2-aec1-ab191cac0400
		summarizeBy: sum
		sourceColumn: risk_free_rate_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cost_of_equity_pct
		dataType: double
		lineageTag: 1e10dcc9-66dd-4f3a-8aef-3b7ccc79a768
		summarizeBy: sum
		sourceColumn: cost_of_equity_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cost_of_debt_pct
		dataType: double
		lineageTag: 18052437-1fee-4c67-af16-99e3e4d9667e
		summarizeBy: sum
		sourceColumn: cost_of_debt_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column wacc_pct
		dataType: double
		lineageTag: a469a458-1ed8-40e8-869e-189420f5ea06
		summarizeBy: sum
		sourceColumn: wacc_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column enterprise_value
		dataType: double
		lineageTag: 6c9b7b2f-62b8-4be4-80b5-d5b5e4ecc4bf
		summarizeBy: average
		sourceColumn: enterprise_value

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column equity_value
		dataType: double
		lineageTag: d0f36204-eef0-4b3c-9e32-fb8723840128
		summarizeBy: sum
		sourceColumn: equity_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column implied_share_price
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7fefb636-07e1-4002-b5fe-6095b5182218
		summarizeBy: sum
		sourceColumn: implied_share_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column scenario_sort
		dataType: int64
		formatString: 0
		lineageTag: 4f263fb1-1eee-4f8c-bc9b-3ae73d44e679
		summarizeBy: sum
		sourceColumn: scenario_sort

		annotation SummarizationSetBy = Automatic

	column beta
		dataType: double
		lineageTag: 425df8c1-6f45-42ae-aff2-a397fc38122a
		summarizeBy: average
		sourceColumn: beta

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column equity_risk_premium_pct
		dataType: double
		lineageTag: 3f69ccf9-8375-45f4-8bd7-3d496b7cea2c
		summarizeBy: average
		sourceColumn: equity_risk_premium_pct

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column equity_weight_pct
		dataType: double
		lineageTag: b94e5485-a3a7-439b-9b60-d8c6d4e74e29
		summarizeBy: sum
		sourceColumn: equity_weight_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column debt_weight_pct
		dataType: double
		lineageTag: 312db761-22ac-47c0-9209-195067a69a95
		summarizeBy: sum
		sourceColumn: debt_weight_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column credit_spread_pct
		dataType: double
		lineageTag: 5848cc05-cf2a-4d6f-a527-91bb1c643ac4
		summarizeBy: average
		sourceColumn: credit_spread_pct

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tax_rate_pct
		dataType: double
		lineageTag: 5630e318-34e3-466a-bd6c-1ef5bc398b26
		summarizeBy: sum
		sourceColumn: tax_rate_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column debt
		dataType: double
		lineageTag: df7684e1-d7cb-4c7b-8a6b-99ef3e7e2e3d
		summarizeBy: sum
		sourceColumn: debt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cash
		dataType: double
		lineageTag: 22fd835d-6764-46a0-9d24-8a5994a6966e
		summarizeBy: sum
		sourceColumn: cash

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column net_debt
		dataType: double
		lineageTag: 9b29ef5f-5eea-423a-8dda-332f919f8886
		summarizeBy: sum
		sourceColumn: net_debt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column shares_outstanding
		dataType: double
		formatString: 0
		lineageTag: 3f0b6a0a-43fa-417e-851e-60a87cc48bfb
		summarizeBy: sum
		sourceColumn: shares_outstanding

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column terminal_growth_pct
		dataType: double
		lineageTag: 633bdf87-485a-45bb-87d8-dc5e2bbf6f6f
		summarizeBy: sum
		sourceColumn: terminal_growth_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ebit
		dataType: double
		lineageTag: 0b408d89-474b-4470-9a69-2b46eaf86db1
		summarizeBy: sum
		sourceColumn: ebit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nopat
		dataType: double
		lineageTag: d5da420a-fcc2-4b97-a7dd-dc4d680b83ac
		summarizeBy: sum
		sourceColumn: nopat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column invested_capital
		dataType: double
		lineageTag: e7bf75e6-94b0-47a4-83ca-7b50ef4f429c
		summarizeBy: sum
		sourceColumn: invested_capital

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column roic_pct
		dataType: double
		lineageTag: 05ca890c-3cf0-4f0d-ae76-f3256c203d12
		summarizeBy: sum
		sourceColumn: roic_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column roic_wacc_spread_pct
		dataType: double
		lineageTag: fb1828d7-2e84-4206-8906-c4d7edfc3126
		summarizeBy: sum
		sourceColumn: roic_wacc_spread_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column revenue
		dataType: string
		lineageTag: 391eb507-4894-4267-bd00-d1b0c3d3539b
		summarizeBy: none
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column ebit_margin_pct
		dataType: string
		lineageTag: 33ae22c8-9396-4ab9-aebb-174904b2fcf1
		summarizeBy: none
		sourceColumn: ebit_margin_pct

		annotation SummarizationSetBy = Automatic

	column project_irr_pct
		dataType: double
		formatString: 0.00
		lineageTag: b4386b0b-73e3-4f57-948a-389b27f7ab06
		summarizeBy: none
		sourceColumn: project_irr_pct

		annotation SummarizationSetBy = Automatic

	column hurdle_rate_pct
		dataType: double
		formatString: 0.00
		lineageTag: dd0df80a-dcda-4403-b049-4f6ae0f474b9
		summarizeBy: none
		sourceColumn: hurdle_rate_pct

		annotation SummarizationSetBy = Automatic

	partition finance_scenario_report = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\finance_scenario_report.csv"),
				    [Delimiter = ",", Columns = 33, QuoteStyle = QuoteStyle.None]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted headers",{{"scenario_sort", Int64.Type}, {"treasury_2y", type number}, {"fed_funds", type number}, {"cpi", type number}, {"unemployment", type number}, {"risk_free_rate_pct", type number}, {"beta", type number}, {"equity_risk_premium_pct", type number}, {"equity_weight_pct", type number}, {"debt_weight_pct", type number}, {"credit_spread_pct", type number}, {"tax_rate_pct", type number}, {"cost_of_equity_pct", type number}, {"cost_of_debt_pct", type number}, {"wacc_pct", type number}, {"debt", type number}, {"cash", type number}, {"net_debt", type number}, {"shares_outstanding", type number}, {"terminal_growth_pct", type number}, {"enterprise_value", type number}, {"equity_value", type number}, {"implied_share_price", type number}, {"ebit", type number}, {"roic_pct", type number}, {"invested_capital", type number}, {"nopat", type number}, {"roic_wacc_spread_pct", type number}, {"hurdle_rate_pct", type number}, {"project_irr_pct", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

