/// Curated pipeline export reports/market_history_rolling24.csv:
/// monthly macro history - the full headline-release set (curve,
/// policy, inflation, labor, activity, surveys, credit) - with each
/// metric's rolling 24-month mean, blank until a full window exists.
/// SYNTHETIC seed-42/4242 until the live FRED cutover. Python writes
/// it; Page 5 only reads.
table market_history_rolling24
	lineageTag: 51ebe00f-b191-4029-bf1d-78e519078fcc

	column observation_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 88084c9d-fbbb-4ee4-bb41-4690ffc45ba2
		summarizeBy: none
		sourceColumn: observation_date

		annotation SummarizationSetBy = Automatic

	column ust_3m
		dataType: double
		formatString: 0.00
		lineageTag: bf9b1c75-b144-480e-9aba-95ef3ca77985
		summarizeBy: none
		sourceColumn: ust_3m

		annotation SummarizationSetBy = Automatic

	column ust_3m_r24
		dataType: double
		formatString: 0.00
		lineageTag: 1b54bf36-31c8-4b12-bd7e-3d853004f260
		summarizeBy: none
		sourceColumn: ust_3m_r24

		annotation SummarizationSetBy = Automatic

	column ust_2y
		dataType: double
		formatString: 0.00
		lineageTag: 86a59679-271d-4591-84d2-42a58afb23ca
		summarizeBy: none
		sourceColumn: ust_2y

		annotation SummarizationSetBy = Automatic

	column ust_2y_r24
		dataType: double
		formatString: 0.00
		lineageTag: 8ca0fb5b-d700-475d-8201-4c8509437ca2
		summarizeBy: none
		sourceColumn: ust_2y_r24

		annotation SummarizationSetBy = Automatic

	column ust_5y
		dataType: double
		formatString: 0.00
		lineageTag: 78b8164c-4e4d-444a-be0b-1bef8db9efc9
		summarizeBy: none
		sourceColumn: ust_5y

		annotation SummarizationSetBy = Automatic

	column ust_5y_r24
		dataType: double
		formatString: 0.00
		lineageTag: 779805ae-fc34-4c6a-83ba-b2dcef73b0a2
		summarizeBy: none
		sourceColumn: ust_5y_r24

		annotation SummarizationSetBy = Automatic

	column ust_10y
		dataType: double
		formatString: 0.00
		lineageTag: cdb89950-5b44-43f4-84f0-b1df0c2b3eb8
		summarizeBy: none
		sourceColumn: ust_10y

		annotation SummarizationSetBy = Automatic

	column ust_10y_r24
		dataType: double
		formatString: 0.00
		lineageTag: ef02f4b9-eb76-4925-8181-22e792ee4a04
		summarizeBy: none
		sourceColumn: ust_10y_r24

		annotation SummarizationSetBy = Automatic

	column ust_30y
		dataType: double
		formatString: 0.00
		lineageTag: 54ec1c32-5bdc-47a8-84c7-61bc96cbbfd2
		summarizeBy: none
		sourceColumn: ust_30y

		annotation SummarizationSetBy = Automatic

	column ust_30y_r24
		dataType: double
		formatString: 0.00
		lineageTag: 7c9e59f0-ef83-4775-a047-e03d156c0f96
		summarizeBy: none
		sourceColumn: ust_30y_r24

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_2y
		dataType: double
		formatString: 0.00
		lineageTag: ed26d783-a9fe-445a-9eb0-2d739d95216e
		summarizeBy: none
		sourceColumn: curve_spread_10y_2y

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_2y_r24
		dataType: double
		formatString: 0.00
		lineageTag: 7a31c528-9101-4423-8ad1-592c4ac96928
		summarizeBy: none
		sourceColumn: curve_spread_10y_2y_r24

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_3m
		dataType: double
		formatString: 0.00
		lineageTag: f7a3145d-ea2d-4469-9606-3314d56fcc1a
		summarizeBy: none
		sourceColumn: curve_spread_10y_3m

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_3m_r24
		dataType: double
		formatString: 0.00
		lineageTag: cede87e7-c91b-4e3a-9e10-c66999db04fc
		summarizeBy: none
		sourceColumn: curve_spread_10y_3m_r24

		annotation SummarizationSetBy = Automatic

	column fed_funds_eff
		dataType: double
		formatString: 0.00
		lineageTag: 71240ab3-e4fd-449b-a260-471a11fcf1cb
		summarizeBy: none
		sourceColumn: fed_funds_eff

		annotation SummarizationSetBy = Automatic

	column fed_funds_eff_r24
		dataType: double
		formatString: 0.00
		lineageTag: 8f37d03f-8a89-45c7-bc86-2e7db5ccd534
		summarizeBy: none
		sourceColumn: fed_funds_eff_r24

		annotation SummarizationSetBy = Automatic

	column cpi_yoy
		dataType: double
		formatString: 0.00
		lineageTag: c5708992-8404-4db8-a2bc-1267c28462ca
		summarizeBy: none
		sourceColumn: cpi_yoy

		annotation SummarizationSetBy = Automatic

	column cpi_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 7445f2ab-71b5-4bec-8121-7d637541e359
		summarizeBy: none
		sourceColumn: cpi_yoy_r24

		annotation SummarizationSetBy = Automatic

	column core_cpi_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 489ccb11-2928-4163-8019-1bc49d13634c
		summarizeBy: none
		sourceColumn: core_cpi_yoy

		annotation SummarizationSetBy = Automatic

	column core_cpi_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 24083b91-a9d4-46dd-8329-5aa9d3ed12a1
		summarizeBy: none
		sourceColumn: core_cpi_yoy_r24

		annotation SummarizationSetBy = Automatic

	column pce_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 1de62812-d6aa-4592-aaa5-045b54604eb6
		summarizeBy: none
		sourceColumn: pce_yoy

		annotation SummarizationSetBy = Automatic

	column pce_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: f2e5a411-ad22-456b-af91-f52f4db700e8
		summarizeBy: none
		sourceColumn: pce_yoy_r24

		annotation SummarizationSetBy = Automatic

	column core_pce_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 28a94277-2380-4bcd-9f31-f4e9ed22a678
		summarizeBy: none
		sourceColumn: core_pce_yoy

		annotation SummarizationSetBy = Automatic

	column core_pce_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 4748fabb-fc7b-444e-948e-fe508460065e
		summarizeBy: none
		sourceColumn: core_pce_yoy_r24

		annotation SummarizationSetBy = Automatic

	column ppi_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 37263258-c06f-483f-9ad0-cc5fde2d110e
		summarizeBy: none
		sourceColumn: ppi_yoy

		annotation SummarizationSetBy = Automatic

	column ppi_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 691fe8c6-7a83-497c-ad99-2198c0c6f064
		summarizeBy: none
		sourceColumn: ppi_yoy_r24

		annotation SummarizationSetBy = Automatic

	column ahe_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 510c6ba0-0d82-40d6-890b-9464b4b21f86
		summarizeBy: none
		sourceColumn: ahe_yoy

		annotation SummarizationSetBy = Automatic

	column ahe_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 64b62b6d-0e1c-408d-83f7-57013505cf64
		summarizeBy: none
		sourceColumn: ahe_yoy_r24

		annotation SummarizationSetBy = Automatic

	column gdp_growth_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 4b39e359-95c7-40ee-b5f2-4ede1684c61a
		summarizeBy: none
		sourceColumn: gdp_growth_yoy

		annotation SummarizationSetBy = Automatic

	column gdp_growth_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 0770f483-fec4-447d-84da-09161c4d3de2
		summarizeBy: none
		sourceColumn: gdp_growth_yoy_r24

		annotation SummarizationSetBy = Automatic

	column indprod_yoy
		dataType: double
		formatString: 0.00
		lineageTag: b14d1015-0e5e-47c4-96d7-fccf41e2c532
		summarizeBy: none
		sourceColumn: indprod_yoy

		annotation SummarizationSetBy = Automatic

	column indprod_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: f528bfc6-f328-46ac-8653-b9953c861014
		summarizeBy: none
		sourceColumn: indprod_yoy_r24

		annotation SummarizationSetBy = Automatic

	column retail_sales_yoy
		dataType: double
		formatString: 0.00
		lineageTag: cdb6b5f3-30cb-4f2a-b8d4-ed43dc5ef67a
		summarizeBy: none
		sourceColumn: retail_sales_yoy

		annotation SummarizationSetBy = Automatic

	column retail_sales_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: be6b2014-5504-405f-81ba-0ded781b54a0
		summarizeBy: none
		sourceColumn: retail_sales_yoy_r24

		annotation SummarizationSetBy = Automatic

	column unemployment_rate
		dataType: double
		formatString: 0.00
		lineageTag: 751fa213-acde-4da2-b4e1-eefca07b9481
		summarizeBy: none
		sourceColumn: unemployment_rate

		annotation SummarizationSetBy = Automatic

	column unemployment_rate_r24
		dataType: double
		formatString: 0.00
		lineageTag: cdaed5af-6b7b-4014-be78-de64907417f2
		summarizeBy: none
		sourceColumn: unemployment_rate_r24

		annotation SummarizationSetBy = Automatic

	column u6_rate
		dataType: double
		formatString: 0.00
		lineageTag: d58c0bf8-19ea-42e3-a179-f3f1c18139db
		summarizeBy: none
		sourceColumn: u6_rate

		annotation SummarizationSetBy = Automatic

	column u6_rate_r24
		dataType: double
		formatString: 0.00
		lineageTag: b9f6c9e6-80f4-4149-8f20-908cce6196d7
		summarizeBy: none
		sourceColumn: u6_rate_r24

		annotation SummarizationSetBy = Automatic

	column participation_rate
		dataType: double
		formatString: 0.00
		lineageTag: ca70ce63-b328-42bd-8004-008830fd11ff
		summarizeBy: none
		sourceColumn: participation_rate

		annotation SummarizationSetBy = Automatic

	column participation_rate_r24
		dataType: double
		formatString: 0.00
		lineageTag: 799125cb-f2ea-4be2-8078-a53fad3ab2d9
		summarizeBy: none
		sourceColumn: participation_rate_r24

		annotation SummarizationSetBy = Automatic

	column unemp_duration_weeks
		dataType: double
		formatString: 0.00
		lineageTag: b461cb81-d91c-4026-9a08-ef141e3d3b42
		summarizeBy: none
		sourceColumn: unemp_duration_weeks

		annotation SummarizationSetBy = Automatic

	column unemp_duration_weeks_r24
		dataType: double
		formatString: 0.00
		lineageTag: 249e022b-72b2-45ff-b2f9-f77ac666962a
		summarizeBy: none
		sourceColumn: unemp_duration_weeks_r24

		annotation SummarizationSetBy = Automatic

	column initial_claims_k
		dataType: double
		formatString: 0.00
		lineageTag: 331c42d2-15a6-4e83-8abd-35ecef3e4ed5
		summarizeBy: none
		sourceColumn: initial_claims_k

		annotation SummarizationSetBy = Automatic

	column initial_claims_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 3190df93-c2c0-4835-be84-1b028def64f2
		summarizeBy: none
		sourceColumn: initial_claims_k_r24

		annotation SummarizationSetBy = Automatic

	column continuing_claims_k
		dataType: double
		formatString: 0.00
		lineageTag: bf0a4e54-9098-49df-814c-f032bd03f7c7
		summarizeBy: none
		sourceColumn: continuing_claims_k

		annotation SummarizationSetBy = Automatic

	column continuing_claims_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 5ff206b4-bf76-4446-922e-7e888c57a08e
		summarizeBy: none
		sourceColumn: continuing_claims_k_r24

		annotation SummarizationSetBy = Automatic

	column payroll_chg_k
		dataType: double
		formatString: 0.00
		lineageTag: 2ed61a5f-2e5c-4d45-a993-fea7f47ef246
		summarizeBy: none
		sourceColumn: payroll_chg_k

		annotation SummarizationSetBy = Automatic

	column payroll_chg_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 95267e51-4a0c-4297-9a85-9f7f05977952
		summarizeBy: none
		sourceColumn: payroll_chg_k_r24

		annotation SummarizationSetBy = Automatic

	column jolts_openings_k
		dataType: double
		formatString: 0.00
		lineageTag: a6dbeb42-b404-4748-9a5b-811ebdce99b7
		summarizeBy: none
		sourceColumn: jolts_openings_k

		annotation SummarizationSetBy = Automatic

	column jolts_openings_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 27bce1b7-10e1-4e33-932b-656092edfff1
		summarizeBy: none
		sourceColumn: jolts_openings_k_r24

		annotation SummarizationSetBy = Automatic

	column housing_starts_k
		dataType: double
		formatString: 0.00
		lineageTag: e1c33482-3fd2-4ac9-a9dd-cb69e9190da2
		summarizeBy: none
		sourceColumn: housing_starts_k

		annotation SummarizationSetBy = Automatic

	column housing_starts_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 4a03442b-59f2-49f1-808f-34520ea25151
		summarizeBy: none
		sourceColumn: housing_starts_k_r24

		annotation SummarizationSetBy = Automatic

	column consumer_sentiment_idx
		dataType: double
		formatString: 0.00
		lineageTag: 45a8aa9c-1460-4a0a-a5c8-d3676b4e0a09
		summarizeBy: none
		sourceColumn: consumer_sentiment_idx

		annotation SummarizationSetBy = Automatic

	column consumer_sentiment_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: 784c40aa-bf98-4144-a5eb-0526fc785fab
		summarizeBy: none
		sourceColumn: consumer_sentiment_idx_r24

		annotation SummarizationSetBy = Automatic

	column ism_pmi_idx
		dataType: double
		formatString: 0.00
		lineageTag: 169519c0-6f67-43d2-af82-1760d4419658
		summarizeBy: none
		sourceColumn: ism_pmi_idx

		annotation SummarizationSetBy = Automatic

	column ism_pmi_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: 57434948-38b9-40af-b506-5814b58825c1
		summarizeBy: none
		sourceColumn: ism_pmi_idx_r24

		annotation SummarizationSetBy = Automatic

	column ig_oas
		dataType: double
		formatString: 0.00
		lineageTag: 499ebf5c-86b3-41bc-85de-de1e625283fc
		summarizeBy: none
		sourceColumn: ig_oas

		annotation SummarizationSetBy = Automatic

	column ig_oas_r24
		dataType: double
		formatString: 0.00
		lineageTag: af761b9a-fc61-40fc-aee0-d2faed11da15
		summarizeBy: none
		sourceColumn: ig_oas_r24

		annotation SummarizationSetBy = Automatic

	column hy_oas
		dataType: double
		formatString: 0.00
		lineageTag: a0a512bb-8ae6-4191-a4e8-590cb47c763a
		summarizeBy: none
		sourceColumn: hy_oas

		annotation SummarizationSetBy = Automatic

	column hy_oas_r24
		dataType: double
		formatString: 0.00
		lineageTag: 8505cbed-0ee2-4484-8114-19e17298d2df
		summarizeBy: none
		sourceColumn: hy_oas_r24

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		lineageTag: 110a876c-dd78-49d4-a3f7-feaf42cbb5fe
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: e18bde46-415e-4fb7-90e9-4936d9881540
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	partition market_history_rolling24 = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\market_history_rolling24.csv"),
				    [Delimiter = ",", Columns = 63, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"observation_date", "ust_3m", "ust_3m_r24", "ust_2y", "ust_2y_r24", "ust_5y", "ust_5y_r24", "ust_10y", "ust_10y_r24", "ust_30y", "ust_30y_r24", "curve_spread_10y_2y", "curve_spread_10y_2y_r24", "curve_spread_10y_3m", "curve_spread_10y_3m_r24", "fed_funds_eff", "fed_funds_eff_r24", "cpi_yoy", "cpi_yoy_r24", "core_cpi_yoy", "core_cpi_yoy_r24", "pce_yoy", "pce_yoy_r24", "core_pce_yoy", "core_pce_yoy_r24", "ppi_yoy", "ppi_yoy_r24", "ahe_yoy", "ahe_yoy_r24", "gdp_growth_yoy", "gdp_growth_yoy_r24", "indprod_yoy", "indprod_yoy_r24", "retail_sales_yoy", "retail_sales_yoy_r24", "unemployment_rate", "unemployment_rate_r24", "u6_rate", "u6_rate_r24", "participation_rate", "participation_rate_r24", "unemp_duration_weeks", "unemp_duration_weeks_r24", "initial_claims_k", "initial_claims_k_r24", "continuing_claims_k", "continuing_claims_k_r24", "payroll_chg_k", "payroll_chg_k_r24", "jolts_openings_k", "jolts_openings_k_r24", "housing_starts_k", "housing_starts_k_r24", "consumer_sentiment_idx", "consumer_sentiment_idx_r24", "ism_pmi_idx", "ism_pmi_idx_r24", "ig_oas", "ig_oas_r24", "hy_oas", "hy_oas_r24", "source", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {{"observation_date", type date}, {"ust_3m", type number}, {"ust_3m_r24", type number}, {"ust_2y", type number}, {"ust_2y_r24", type number}, {"ust_5y", type number}, {"ust_5y_r24", type number}, {"ust_10y", type number}, {"ust_10y_r24", type number}, {"ust_30y", type number}, {"ust_30y_r24", type number}, {"curve_spread_10y_2y", type number}, {"curve_spread_10y_2y_r24", type number}, {"curve_spread_10y_3m", type number}, {"curve_spread_10y_3m_r24", type number}, {"fed_funds_eff", type number}, {"fed_funds_eff_r24", type number}, {"cpi_yoy", type number}, {"cpi_yoy_r24", type number}, {"core_cpi_yoy", type number}, {"core_cpi_yoy_r24", type number}, {"pce_yoy", type number}, {"pce_yoy_r24", type number}, {"core_pce_yoy", type number}, {"core_pce_yoy_r24", type number}, {"ppi_yoy", type number}, {"ppi_yoy_r24", type number}, {"ahe_yoy", type number}, {"ahe_yoy_r24", type number}, {"gdp_growth_yoy", type number}, {"gdp_growth_yoy_r24", type number}, {"indprod_yoy", type number}, {"indprod_yoy_r24", type number}, {"retail_sales_yoy", type number}, {"retail_sales_yoy_r24", type number}, {"unemployment_rate", type number}, {"unemployment_rate_r24", type number}, {"u6_rate", type number}, {"u6_rate_r24", type number}, {"participation_rate", type number}, {"participation_rate_r24", type number}, {"unemp_duration_weeks", type number}, {"unemp_duration_weeks_r24", type number}, {"initial_claims_k", type number}, {"initial_claims_k_r24", type number}, {"continuing_claims_k", type number}, {"continuing_claims_k_r24", type number}, {"payroll_chg_k", type number}, {"payroll_chg_k_r24", type number}, {"jolts_openings_k", type number}, {"jolts_openings_k_r24", type number}, {"housing_starts_k", type number}, {"housing_starts_k_r24", type number}, {"consumer_sentiment_idx", type number}, {"consumer_sentiment_idx_r24", type number}, {"ism_pmi_idx", type number}, {"ism_pmi_idx_r24", type number}, {"ig_oas", type number}, {"ig_oas_r24", type number}, {"hy_oas", type number}, {"hy_oas_r24", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
