/// Curated pipeline export: monthly macro + market history with
/// rolling 24-month means. SYNTHETIC until the live cutover; the
/// placeholder firm slots never carry a real ticker's history.
table market_history_rolling24
	lineageTag: deb38a24-02d6-499e-ae1d-c9105d55bb15

	column observation_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 00661875-fac4-4b7a-aff6-427aa141d6cf
		summarizeBy: none
		sourceColumn: observation_date

		annotation SummarizationSetBy = Automatic

	column ust_3m
		dataType: double
		formatString: 0.00
		lineageTag: d64a5f7e-9251-45f1-a297-c1595211e0f7
		summarizeBy: none
		sourceColumn: ust_3m

		annotation SummarizationSetBy = Automatic

	column ust_3m_r24
		dataType: double
		formatString: 0.00
		lineageTag: 569e81fc-534f-48de-b8d0-1e8ed9da3f52
		summarizeBy: none
		sourceColumn: ust_3m_r24

		annotation SummarizationSetBy = Automatic

	column ust_2y
		dataType: double
		formatString: 0.00
		lineageTag: d96b844f-619c-4e8c-b8b9-be432600cf00
		summarizeBy: none
		sourceColumn: ust_2y

		annotation SummarizationSetBy = Automatic

	column ust_2y_r24
		dataType: double
		formatString: 0.00
		lineageTag: c9867ca9-fb57-45b8-a80e-b18f10ad7979
		summarizeBy: none
		sourceColumn: ust_2y_r24

		annotation SummarizationSetBy = Automatic

	column ust_5y
		dataType: double
		formatString: 0.00
		lineageTag: 490d420d-98ad-4360-b8d1-4b500c60332d
		summarizeBy: none
		sourceColumn: ust_5y

		annotation SummarizationSetBy = Automatic

	column ust_5y_r24
		dataType: double
		formatString: 0.00
		lineageTag: 215a33c3-9326-4650-bf32-a1345fea99dc
		summarizeBy: none
		sourceColumn: ust_5y_r24

		annotation SummarizationSetBy = Automatic

	column ust_10y
		dataType: double
		formatString: 0.00
		lineageTag: 2814e888-5150-48ab-9f39-a36af934a068
		summarizeBy: none
		sourceColumn: ust_10y

		annotation SummarizationSetBy = Automatic

	column ust_10y_r24
		dataType: double
		formatString: 0.00
		lineageTag: 54dba3e0-5865-4f14-87be-dd803bb97cfa
		summarizeBy: none
		sourceColumn: ust_10y_r24

		annotation SummarizationSetBy = Automatic

	column ust_30y
		dataType: double
		formatString: 0.00
		lineageTag: 10f1bffa-ffc4-4c2f-bb7d-76585e46094d
		summarizeBy: none
		sourceColumn: ust_30y

		annotation SummarizationSetBy = Automatic

	column ust_30y_r24
		dataType: double
		formatString: 0.00
		lineageTag: 53456b05-7582-4735-b380-1a3513e1ddc3
		summarizeBy: none
		sourceColumn: ust_30y_r24

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_2y
		dataType: double
		formatString: 0.00
		lineageTag: fdd4987a-71aa-47bc-85d7-ab67e71c1cc7
		summarizeBy: none
		sourceColumn: curve_spread_10y_2y

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_2y_r24
		dataType: double
		formatString: 0.00
		lineageTag: e44b4271-1090-40f4-a329-920289996d7d
		summarizeBy: none
		sourceColumn: curve_spread_10y_2y_r24

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_3m
		dataType: double
		formatString: 0.00
		lineageTag: 3175310b-95c8-4525-9c32-42c93185ccb7
		summarizeBy: none
		sourceColumn: curve_spread_10y_3m

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_3m_r24
		dataType: double
		formatString: 0.00
		lineageTag: 2143bf46-4174-4b04-96b5-3c313a7798f0
		summarizeBy: none
		sourceColumn: curve_spread_10y_3m_r24

		annotation SummarizationSetBy = Automatic

	column fed_funds_eff
		dataType: double
		formatString: 0.00
		lineageTag: dcb5f59c-9971-4b9e-9dc5-d3f3f35d46b4
		summarizeBy: none
		sourceColumn: fed_funds_eff

		annotation SummarizationSetBy = Automatic

	column fed_funds_eff_r24
		dataType: double
		formatString: 0.00
		lineageTag: dd33fc70-4c2b-4a9e-8785-66c6d22be2ee
		summarizeBy: none
		sourceColumn: fed_funds_eff_r24

		annotation SummarizationSetBy = Automatic

	column cpi_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 569d1bfc-d6f3-406b-8198-6f13589d89e3
		summarizeBy: none
		sourceColumn: cpi_yoy

		annotation SummarizationSetBy = Automatic

	column cpi_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: c1974ac1-9c12-49bc-9174-79df1aba95b9
		summarizeBy: none
		sourceColumn: cpi_yoy_r24

		annotation SummarizationSetBy = Automatic

	column core_cpi_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 3d1dcb22-9a1a-4b23-b09e-7f623a649f3f
		summarizeBy: none
		sourceColumn: core_cpi_yoy

		annotation SummarizationSetBy = Automatic

	column core_cpi_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 0654e48c-9cf0-4fe1-ae73-06a4d5cf6f2e
		summarizeBy: none
		sourceColumn: core_cpi_yoy_r24

		annotation SummarizationSetBy = Automatic

	column pce_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 0fc7f8fb-472e-47bc-a9c8-7fe04fcb6e2a
		summarizeBy: none
		sourceColumn: pce_yoy

		annotation SummarizationSetBy = Automatic

	column pce_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 50d1ef0e-8c96-4855-8b98-88ad32df5b5b
		summarizeBy: none
		sourceColumn: pce_yoy_r24

		annotation SummarizationSetBy = Automatic

	column core_pce_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 5ddfb8da-c426-4517-8930-8a2133f811bc
		summarizeBy: none
		sourceColumn: core_pce_yoy

		annotation SummarizationSetBy = Automatic

	column core_pce_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 48718f76-17f5-45be-b8c6-58568458fbcd
		summarizeBy: none
		sourceColumn: core_pce_yoy_r24

		annotation SummarizationSetBy = Automatic

	column ppi_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 1ce850d3-2a6d-493e-8d46-fec6b243eceb
		summarizeBy: none
		sourceColumn: ppi_yoy

		annotation SummarizationSetBy = Automatic

	column ppi_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 24f1bcd5-bb8e-4077-bd73-4153a5febd88
		summarizeBy: none
		sourceColumn: ppi_yoy_r24

		annotation SummarizationSetBy = Automatic

	column ahe_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 65803657-a7c1-4e46-9e00-371a7dfc4382
		summarizeBy: none
		sourceColumn: ahe_yoy

		annotation SummarizationSetBy = Automatic

	column ahe_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 6dc681f2-c19d-41f7-8824-2c09a39d9726
		summarizeBy: none
		sourceColumn: ahe_yoy_r24

		annotation SummarizationSetBy = Automatic

	column gdp_growth_yoy
		dataType: double
		formatString: 0.00
		lineageTag: fe54bfce-db66-4f77-b39f-d35376be60e3
		summarizeBy: none
		sourceColumn: gdp_growth_yoy

		annotation SummarizationSetBy = Automatic

	column gdp_growth_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: b30a61e9-3d5d-401b-92f7-c2cc238c5a6c
		summarizeBy: none
		sourceColumn: gdp_growth_yoy_r24

		annotation SummarizationSetBy = Automatic

	column indprod_yoy
		dataType: double
		formatString: 0.00
		lineageTag: c47ebd7b-3a9b-47db-80e9-8e872d96e374
		summarizeBy: none
		sourceColumn: indprod_yoy

		annotation SummarizationSetBy = Automatic

	column indprod_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 14e5afe4-6c2b-4cfe-a51c-fe67d72edb7c
		summarizeBy: none
		sourceColumn: indprod_yoy_r24

		annotation SummarizationSetBy = Automatic

	column retail_sales_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 96e89daf-d9f6-43dc-8220-9e200c174832
		summarizeBy: none
		sourceColumn: retail_sales_yoy

		annotation SummarizationSetBy = Automatic

	column retail_sales_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 83de926b-7f61-40cc-9566-9a026ce5625f
		summarizeBy: none
		sourceColumn: retail_sales_yoy_r24

		annotation SummarizationSetBy = Automatic

	column unemployment_rate
		dataType: double
		formatString: 0.00
		lineageTag: cd43d6ed-b873-4478-a736-cc303da2e4d5
		summarizeBy: none
		sourceColumn: unemployment_rate

		annotation SummarizationSetBy = Automatic

	column unemployment_rate_r24
		dataType: double
		formatString: 0.00
		lineageTag: 3cc6f2a0-c6ec-48ed-898b-a3af8987819e
		summarizeBy: none
		sourceColumn: unemployment_rate_r24

		annotation SummarizationSetBy = Automatic

	column u6_rate
		dataType: double
		formatString: 0.00
		lineageTag: 40ad29e2-3959-4bae-99f2-eab1a6bc70c3
		summarizeBy: none
		sourceColumn: u6_rate

		annotation SummarizationSetBy = Automatic

	column u6_rate_r24
		dataType: double
		formatString: 0.00
		lineageTag: ebb080de-1e36-4399-92c9-9b641133e1b7
		summarizeBy: none
		sourceColumn: u6_rate_r24

		annotation SummarizationSetBy = Automatic

	column participation_rate
		dataType: double
		formatString: 0.00
		lineageTag: 536e6421-dcb7-47e0-a103-c076d428fb64
		summarizeBy: none
		sourceColumn: participation_rate

		annotation SummarizationSetBy = Automatic

	column participation_rate_r24
		dataType: double
		formatString: 0.00
		lineageTag: 8b9f986b-c90d-4260-a5bb-0707df97996b
		summarizeBy: none
		sourceColumn: participation_rate_r24

		annotation SummarizationSetBy = Automatic

	column unemp_duration_weeks
		dataType: double
		formatString: 0.00
		lineageTag: 31500cdb-3555-4885-9083-84f2b468ce06
		summarizeBy: none
		sourceColumn: unemp_duration_weeks

		annotation SummarizationSetBy = Automatic

	column unemp_duration_weeks_r24
		dataType: double
		formatString: 0.00
		lineageTag: 6717a3ad-8889-4181-9143-a9fae5977f53
		summarizeBy: none
		sourceColumn: unemp_duration_weeks_r24

		annotation SummarizationSetBy = Automatic

	column initial_claims_k
		dataType: double
		formatString: 0.00
		lineageTag: 99e5db32-8415-4ce6-80d8-acc08c9d4b0c
		summarizeBy: none
		sourceColumn: initial_claims_k

		annotation SummarizationSetBy = Automatic

	column initial_claims_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: c4c7948e-a24d-40c4-b5fa-87bd98dec2de
		summarizeBy: none
		sourceColumn: initial_claims_k_r24

		annotation SummarizationSetBy = Automatic

	column continuing_claims_k
		dataType: double
		formatString: 0.00
		lineageTag: 85274a20-8f91-4044-85f3-93005fe6ffc6
		summarizeBy: none
		sourceColumn: continuing_claims_k

		annotation SummarizationSetBy = Automatic

	column continuing_claims_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 5d03b06c-2218-4aab-a323-48479fc73e8c
		summarizeBy: none
		sourceColumn: continuing_claims_k_r24

		annotation SummarizationSetBy = Automatic

	column payroll_chg_k
		dataType: double
		formatString: 0.00
		lineageTag: 6a449f20-dfd4-45a2-b854-b8ba00722d8c
		summarizeBy: none
		sourceColumn: payroll_chg_k

		annotation SummarizationSetBy = Automatic

	column payroll_chg_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 018858e8-8dc5-4e6b-8378-86d97413842d
		summarizeBy: none
		sourceColumn: payroll_chg_k_r24

		annotation SummarizationSetBy = Automatic

	column jolts_openings_k
		dataType: double
		formatString: 0.00
		lineageTag: 40b9caf1-a2de-4b32-b9fa-1b0fe022f994
		summarizeBy: none
		sourceColumn: jolts_openings_k

		annotation SummarizationSetBy = Automatic

	column jolts_openings_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 90a09d8f-6b1c-4212-8232-294d00b7b5e9
		summarizeBy: none
		sourceColumn: jolts_openings_k_r24

		annotation SummarizationSetBy = Automatic

	column housing_starts_k
		dataType: double
		formatString: 0.00
		lineageTag: ad157dc5-d997-43f9-8778-614c9eb84d6e
		summarizeBy: none
		sourceColumn: housing_starts_k

		annotation SummarizationSetBy = Automatic

	column housing_starts_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 00f11cc8-d04d-44fe-9e7f-bfe39c04d3a6
		summarizeBy: none
		sourceColumn: housing_starts_k_r24

		annotation SummarizationSetBy = Automatic

	column consumer_sentiment_idx
		dataType: double
		formatString: 0.00
		lineageTag: 7dc77d03-a50d-4a7c-962a-22aea0402415
		summarizeBy: none
		sourceColumn: consumer_sentiment_idx

		annotation SummarizationSetBy = Automatic

	column consumer_sentiment_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: f881fbf3-0c54-41c1-adfa-394e336a6049
		summarizeBy: none
		sourceColumn: consumer_sentiment_idx_r24

		annotation SummarizationSetBy = Automatic

	column ism_pmi_idx
		dataType: double
		formatString: 0.00
		lineageTag: 44199daa-5760-4f63-b96a-521a288148e4
		summarizeBy: none
		sourceColumn: ism_pmi_idx

		annotation SummarizationSetBy = Automatic

	column ism_pmi_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: 4c719b84-ac71-492c-8d99-53eeade28f07
		summarizeBy: none
		sourceColumn: ism_pmi_idx_r24

		annotation SummarizationSetBy = Automatic

	column ig_oas
		dataType: double
		formatString: 0.00
		lineageTag: 92b944ee-4246-4153-bf9f-3529021b24e9
		summarizeBy: none
		sourceColumn: ig_oas

		annotation SummarizationSetBy = Automatic

	column ig_oas_r24
		dataType: double
		formatString: 0.00
		lineageTag: 94a857fe-167a-4eb6-873c-2da828896e07
		summarizeBy: none
		sourceColumn: ig_oas_r24

		annotation SummarizationSetBy = Automatic

	column hy_oas
		dataType: double
		formatString: 0.00
		lineageTag: 613d393e-ebc0-47c1-ab90-ce0d34b42dee
		summarizeBy: none
		sourceColumn: hy_oas

		annotation SummarizationSetBy = Automatic

	column hy_oas_r24
		dataType: double
		formatString: 0.00
		lineageTag: 41cb34c3-cba4-4aca-8174-402b3f302be3
		summarizeBy: none
		sourceColumn: hy_oas_r24

		annotation SummarizationSetBy = Automatic

	column gold_usd_oz
		dataType: double
		formatString: 0.00
		lineageTag: bea61cb7-8ac9-4b0b-92ab-5dbdd53399ae
		summarizeBy: none
		sourceColumn: gold_usd_oz

		annotation SummarizationSetBy = Automatic

	column gold_usd_oz_r24
		dataType: double
		formatString: 0.00
		lineageTag: 71a7a322-49a7-43a6-8377-a140413c7dfd
		summarizeBy: none
		sourceColumn: gold_usd_oz_r24

		annotation SummarizationSetBy = Automatic

	column silver_usd_oz
		dataType: double
		formatString: 0.00
		lineageTag: c3770a72-4df6-42a0-809e-86ff21f35f77
		summarizeBy: none
		sourceColumn: silver_usd_oz

		annotation SummarizationSetBy = Automatic

	column silver_usd_oz_r24
		dataType: double
		formatString: 0.00
		lineageTag: 956366d9-864c-4d19-a2cc-3ab20f88e2d8
		summarizeBy: none
		sourceColumn: silver_usd_oz_r24

		annotation SummarizationSetBy = Automatic

	column oil_wti_usd_bbl
		dataType: double
		formatString: 0.00
		lineageTag: 81e8c584-0cdd-49e8-939c-8ada092b912f
		summarizeBy: none
		sourceColumn: oil_wti_usd_bbl

		annotation SummarizationSetBy = Automatic

	column oil_wti_usd_bbl_r24
		dataType: double
		formatString: 0.00
		lineageTag: 17a6fe80-779d-469d-8940-99a435fdf409
		summarizeBy: none
		sourceColumn: oil_wti_usd_bbl_r24

		annotation SummarizationSetBy = Automatic

	column brent_usd_bbl
		dataType: double
		formatString: 0.00
		lineageTag: e18df99e-0896-4534-8d6b-c6fe4db46f8c
		summarizeBy: none
		sourceColumn: brent_usd_bbl

		annotation SummarizationSetBy = Automatic

	column brent_usd_bbl_r24
		dataType: double
		formatString: 0.00
		lineageTag: d7e08af1-2a56-4a35-9b75-9f646d4c99d9
		summarizeBy: none
		sourceColumn: brent_usd_bbl_r24

		annotation SummarizationSetBy = Automatic

	column beef_usd_lb
		dataType: double
		formatString: 0.00
		lineageTag: fa3ebd01-b627-489f-9c91-22d692af73a3
		summarizeBy: none
		sourceColumn: beef_usd_lb

		annotation SummarizationSetBy = Automatic

	column beef_usd_lb_r24
		dataType: double
		formatString: 0.00
		lineageTag: d55949d2-a9c9-49d5-8f7e-e0376fbfedc1
		summarizeBy: none
		sourceColumn: beef_usd_lb_r24

		annotation SummarizationSetBy = Automatic

	column tech_sector_idx
		dataType: double
		formatString: 0.00
		lineageTag: 9dcc3d6b-4923-4a55-a87a-0a2dc674c2e6
		summarizeBy: none
		sourceColumn: tech_sector_idx

		annotation SummarizationSetBy = Automatic

	column tech_sector_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: b4d518d5-cfb8-4fae-9416-44ac8a699b22
		summarizeBy: none
		sourceColumn: tech_sector_idx_r24

		annotation SummarizationSetBy = Automatic

	column ai_sector_idx
		dataType: double
		formatString: 0.00
		lineageTag: 1ba0bb82-7d1c-4e08-bb77-c824fe347cc1
		summarizeBy: none
		sourceColumn: ai_sector_idx

		annotation SummarizationSetBy = Automatic

	column ai_sector_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: 3e734fdb-f1cb-4526-9b9f-0e2b6c47d374
		summarizeBy: none
		sourceColumn: ai_sector_idx_r24

		annotation SummarizationSetBy = Automatic

	column dow_idx
		dataType: double
		formatString: 0.00
		lineageTag: d16caefd-5212-47a7-bb8d-4f4f95d76ed7
		summarizeBy: none
		sourceColumn: dow_idx

		annotation SummarizationSetBy = Automatic

	column dow_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: 7ba76d49-dd1b-44fa-93c4-d88788c036e8
		summarizeBy: none
		sourceColumn: dow_idx_r24

		annotation SummarizationSetBy = Automatic

	column sp500_idx
		dataType: double
		formatString: 0.00
		lineageTag: ebfb591a-eb40-4bab-9baf-afb41ee76723
		summarizeBy: none
		sourceColumn: sp500_idx

		annotation SummarizationSetBy = Automatic

	column sp500_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: f0bf8e95-481b-4a96-ae66-ee86c2542021
		summarizeBy: none
		sourceColumn: sp500_idx_r24

		annotation SummarizationSetBy = Automatic

	column nasdaq_idx
		dataType: double
		formatString: 0.00
		lineageTag: c4ceb1fe-70a6-43a0-9846-13ac217df530
		summarizeBy: none
		sourceColumn: nasdaq_idx

		annotation SummarizationSetBy = Automatic

	column nasdaq_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: 78d704bc-c104-464e-9d5d-c4f5c926d545
		summarizeBy: none
		sourceColumn: nasdaq_idx_r24

		annotation SummarizationSetBy = Automatic

	column russell2000_idx
		dataType: double
		formatString: 0.00
		lineageTag: ec706392-7b96-459a-9b87-6c498f76ccce
		summarizeBy: none
		sourceColumn: russell2000_idx

		annotation SummarizationSetBy = Automatic

	column russell2000_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: f4e6f979-a32c-4db0-af0e-de933621f08f
		summarizeBy: none
		sourceColumn: russell2000_idx_r24

		annotation SummarizationSetBy = Automatic

	column btc_usd
		dataType: double
		formatString: 0.00
		lineageTag: 03bb56ee-cb7b-49d0-9adc-37b1706850f9
		summarizeBy: none
		sourceColumn: btc_usd

		annotation SummarizationSetBy = Automatic

	column btc_usd_r24
		dataType: double
		formatString: 0.00
		lineageTag: 31ea1a2f-b4cf-4858-ac55-966e8774bf47
		summarizeBy: none
		sourceColumn: btc_usd_r24

		annotation SummarizationSetBy = Automatic

	column tech_co_1_px
		dataType: double
		formatString: 0.00
		lineageTag: ed56d1c9-fabb-4559-a1d3-0a77fbd87e50
		summarizeBy: none
		sourceColumn: tech_co_1_px

		annotation SummarizationSetBy = Automatic

	column tech_co_1_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 2607558f-e418-4813-bc15-f7acb2afa191
		summarizeBy: none
		sourceColumn: tech_co_1_px_r24

		annotation SummarizationSetBy = Automatic

	column tech_co_2_px
		dataType: double
		formatString: 0.00
		lineageTag: 4dad867a-74f1-4ae5-ba8c-1a66bca005f6
		summarizeBy: none
		sourceColumn: tech_co_2_px

		annotation SummarizationSetBy = Automatic

	column tech_co_2_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: b3f2915f-43ca-4522-9ba0-f229cda9ee95
		summarizeBy: none
		sourceColumn: tech_co_2_px_r24

		annotation SummarizationSetBy = Automatic

	column tech_co_3_px
		dataType: double
		formatString: 0.00
		lineageTag: 06c13784-26df-4353-8cc9-adfc38e7e267
		summarizeBy: none
		sourceColumn: tech_co_3_px

		annotation SummarizationSetBy = Automatic

	column tech_co_3_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: ab9ab81d-17e2-415f-88d8-6fb9377dbef9
		summarizeBy: none
		sourceColumn: tech_co_3_px_r24

		annotation SummarizationSetBy = Automatic

	column tech_co_4_px
		dataType: double
		formatString: 0.00
		lineageTag: 44fc7d46-e9f3-4021-b39e-efc27af5e1d4
		summarizeBy: none
		sourceColumn: tech_co_4_px

		annotation SummarizationSetBy = Automatic

	column tech_co_4_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: c687e131-970e-4340-9357-8bc521f6bb21
		summarizeBy: none
		sourceColumn: tech_co_4_px_r24

		annotation SummarizationSetBy = Automatic

	column tech_co_5_px
		dataType: double
		formatString: 0.00
		lineageTag: b1d3ba6c-2c16-47fd-beca-35809f448e2c
		summarizeBy: none
		sourceColumn: tech_co_5_px

		annotation SummarizationSetBy = Automatic

	column tech_co_5_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 42f9e3b5-0d6b-4cf6-9078-a92d3f9c1be8
		summarizeBy: none
		sourceColumn: tech_co_5_px_r24

		annotation SummarizationSetBy = Automatic

	column ai_co_1_px
		dataType: double
		formatString: 0.00
		lineageTag: 7a3fa1e6-7ef2-4964-b5ad-3094140de94b
		summarizeBy: none
		sourceColumn: ai_co_1_px

		annotation SummarizationSetBy = Automatic

	column ai_co_1_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 400689ed-c2b2-4e58-80d0-e139af64ec68
		summarizeBy: none
		sourceColumn: ai_co_1_px_r24

		annotation SummarizationSetBy = Automatic

	column ai_co_2_px
		dataType: double
		formatString: 0.00
		lineageTag: 1dc9bcf3-672c-4854-a72d-494fa8ef0edb
		summarizeBy: none
		sourceColumn: ai_co_2_px

		annotation SummarizationSetBy = Automatic

	column ai_co_2_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: eb7f770c-989e-43a1-9ec7-396094cfd5fe
		summarizeBy: none
		sourceColumn: ai_co_2_px_r24

		annotation SummarizationSetBy = Automatic

	column ai_co_3_px
		dataType: double
		formatString: 0.00
		lineageTag: 5dc73998-5261-44b3-9e98-d12b0b6d3b6d
		summarizeBy: none
		sourceColumn: ai_co_3_px

		annotation SummarizationSetBy = Automatic

	column ai_co_3_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: ba5bd637-2bc2-4fac-a3e4-935686a575cf
		summarizeBy: none
		sourceColumn: ai_co_3_px_r24

		annotation SummarizationSetBy = Automatic

	column ai_co_4_px
		dataType: double
		formatString: 0.00
		lineageTag: a4f6bb97-8cf8-475f-a5bd-f20fc2f51416
		summarizeBy: none
		sourceColumn: ai_co_4_px

		annotation SummarizationSetBy = Automatic

	column ai_co_4_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 63aa58e1-31e4-41c1-831d-5ef448e5aa24
		summarizeBy: none
		sourceColumn: ai_co_4_px_r24

		annotation SummarizationSetBy = Automatic

	column ai_co_5_px
		dataType: double
		formatString: 0.00
		lineageTag: dc9e2173-efcb-4003-be2e-64f1c85c1a40
		summarizeBy: none
		sourceColumn: ai_co_5_px

		annotation SummarizationSetBy = Automatic

	column ai_co_5_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 25461cf9-2553-4dc5-9480-e94f08a2bda9
		summarizeBy: none
		sourceColumn: ai_co_5_px_r24

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		lineageTag: 1e7d7d1c-b6d7-4d5b-a6be-5bab0646bc93
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 87c90621-0e44-48a3-98b3-3a6c4a86eeb0
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	partition market_history_rolling24 = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\market_history_rolling24.csv"),
				    [Delimiter = ",", Columns = 107, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"observation_date", "ust_3m", "ust_3m_r24", "ust_2y", "ust_2y_r24", "ust_5y", "ust_5y_r24", "ust_10y", "ust_10y_r24", "ust_30y", "ust_30y_r24", "curve_spread_10y_2y", "curve_spread_10y_2y_r24", "curve_spread_10y_3m", "curve_spread_10y_3m_r24", "fed_funds_eff", "fed_funds_eff_r24", "cpi_yoy", "cpi_yoy_r24", "core_cpi_yoy", "core_cpi_yoy_r24", "pce_yoy", "pce_yoy_r24", "core_pce_yoy", "core_pce_yoy_r24", "ppi_yoy", "ppi_yoy_r24", "ahe_yoy", "ahe_yoy_r24", "gdp_growth_yoy", "gdp_growth_yoy_r24", "indprod_yoy", "indprod_yoy_r24", "retail_sales_yoy", "retail_sales_yoy_r24", "unemployment_rate", "unemployment_rate_r24", "u6_rate", "u6_rate_r24", "participation_rate", "participation_rate_r24", "unemp_duration_weeks", "unemp_duration_weeks_r24", "initial_claims_k", "initial_claims_k_r24", "continuing_claims_k", "continuing_claims_k_r24", "payroll_chg_k", "payroll_chg_k_r24", "jolts_openings_k", "jolts_openings_k_r24", "housing_starts_k", "housing_starts_k_r24", "consumer_sentiment_idx", "consumer_sentiment_idx_r24", "ism_pmi_idx", "ism_pmi_idx_r24", "ig_oas", "ig_oas_r24", "hy_oas", "hy_oas_r24", "gold_usd_oz", "gold_usd_oz_r24", "silver_usd_oz", "silver_usd_oz_r24", "oil_wti_usd_bbl", "oil_wti_usd_bbl_r24", "brent_usd_bbl", "brent_usd_bbl_r24", "beef_usd_lb", "beef_usd_lb_r24", "tech_sector_idx", "tech_sector_idx_r24", "ai_sector_idx", "ai_sector_idx_r24", "dow_idx", "dow_idx_r24", "sp500_idx", "sp500_idx_r24", "nasdaq_idx", "nasdaq_idx_r24", "russell2000_idx", "russell2000_idx_r24", "btc_usd", "btc_usd_r24", "tech_co_1_px", "tech_co_1_px_r24", "tech_co_2_px", "tech_co_2_px_r24", "tech_co_3_px", "tech_co_3_px_r24", "tech_co_4_px", "tech_co_4_px_r24", "tech_co_5_px", "tech_co_5_px_r24", "ai_co_1_px", "ai_co_1_px_r24", "ai_co_2_px", "ai_co_2_px_r24", "ai_co_3_px", "ai_co_3_px_r24", "ai_co_4_px", "ai_co_4_px_r24", "ai_co_5_px", "ai_co_5_px_r24", "source", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {{"observation_date", type date}, {"ust_3m", type number}, {"ust_3m_r24", type number}, {"ust_2y", type number}, {"ust_2y_r24", type number}, {"ust_5y", type number}, {"ust_5y_r24", type number}, {"ust_10y", type number}, {"ust_10y_r24", type number}, {"ust_30y", type number}, {"ust_30y_r24", type number}, {"curve_spread_10y_2y", type number}, {"curve_spread_10y_2y_r24", type number}, {"curve_spread_10y_3m", type number}, {"curve_spread_10y_3m_r24", type number}, {"fed_funds_eff", type number}, {"fed_funds_eff_r24", type number}, {"cpi_yoy", type number}, {"cpi_yoy_r24", type number}, {"core_cpi_yoy", type number}, {"core_cpi_yoy_r24", type number}, {"pce_yoy", type number}, {"pce_yoy_r24", type number}, {"core_pce_yoy", type number}, {"core_pce_yoy_r24", type number}, {"ppi_yoy", type number}, {"ppi_yoy_r24", type number}, {"ahe_yoy", type number}, {"ahe_yoy_r24", type number}, {"gdp_growth_yoy", type number}, {"gdp_growth_yoy_r24", type number}, {"indprod_yoy", type number}, {"indprod_yoy_r24", type number}, {"retail_sales_yoy", type number}, {"retail_sales_yoy_r24", type number}, {"unemployment_rate", type number}, {"unemployment_rate_r24", type number}, {"u6_rate", type number}, {"u6_rate_r24", type number}, {"participation_rate", type number}, {"participation_rate_r24", type number}, {"unemp_duration_weeks", type number}, {"unemp_duration_weeks_r24", type number}, {"initial_claims_k", type number}, {"initial_claims_k_r24", type number}, {"continuing_claims_k", type number}, {"continuing_claims_k_r24", type number}, {"payroll_chg_k", type number}, {"payroll_chg_k_r24", type number}, {"jolts_openings_k", type number}, {"jolts_openings_k_r24", type number}, {"housing_starts_k", type number}, {"housing_starts_k_r24", type number}, {"consumer_sentiment_idx", type number}, {"consumer_sentiment_idx_r24", type number}, {"ism_pmi_idx", type number}, {"ism_pmi_idx_r24", type number}, {"ig_oas", type number}, {"ig_oas_r24", type number}, {"hy_oas", type number}, {"hy_oas_r24", type number}, {"gold_usd_oz", type number}, {"gold_usd_oz_r24", type number}, {"silver_usd_oz", type number}, {"silver_usd_oz_r24", type number}, {"oil_wti_usd_bbl", type number}, {"oil_wti_usd_bbl_r24", type number}, {"brent_usd_bbl", type number}, {"brent_usd_bbl_r24", type number}, {"beef_usd_lb", type number}, {"beef_usd_lb_r24", type number}, {"tech_sector_idx", type number}, {"tech_sector_idx_r24", type number}, {"ai_sector_idx", type number}, {"ai_sector_idx_r24", type number}, {"dow_idx", type number}, {"dow_idx_r24", type number}, {"sp500_idx", type number}, {"sp500_idx_r24", type number}, {"nasdaq_idx", type number}, {"nasdaq_idx_r24", type number}, {"russell2000_idx", type number}, {"russell2000_idx_r24", type number}, {"btc_usd", type number}, {"btc_usd_r24", type number}, {"tech_co_1_px", type number}, {"tech_co_1_px_r24", type number}, {"tech_co_2_px", type number}, {"tech_co_2_px_r24", type number}, {"tech_co_3_px", type number}, {"tech_co_3_px_r24", type number}, {"tech_co_4_px", type number}, {"tech_co_4_px_r24", type number}, {"tech_co_5_px", type number}, {"tech_co_5_px_r24", type number}, {"ai_co_1_px", type number}, {"ai_co_1_px_r24", type number}, {"ai_co_2_px", type number}, {"ai_co_2_px_r24", type number}, {"ai_co_3_px", type number}, {"ai_co_3_px_r24", type number}, {"ai_co_4_px", type number}, {"ai_co_4_px_r24", type number}, {"ai_co_5_px", type number}, {"ai_co_5_px_r24", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
