/// Curated pipeline export reports/market_history_rolling24.csv:
/// monthly macro + market history (rates, inflation, labor, activity,
/// surveys, credit, commodities, equity indices and placeholder firm
/// slots) with rolling 24-month means. SYNTHETIC until the live
/// cutover; firm slots never carry a real ticker's invented history.
table market_history_rolling24
	lineageTag: 2ffb0817-2816-45cd-88f3-1f996d064551

	column observation_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: d738ff33-2eb1-4cf7-b4b9-cd3575bf6df5
		summarizeBy: none
		sourceColumn: observation_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ust_2y
		dataType: double
		formatString: 0.00
		lineageTag: b126622e-28fe-427b-a1ea-4f9684a3cd4f
		summarizeBy: none
		sourceColumn: ust_2y

		annotation SummarizationSetBy = Automatic

	column ust_2y_r24
		dataType: double
		formatString: 0.00
		lineageTag: 05da7cbf-48e9-497f-ac5b-be66cb7ca8e2
		summarizeBy: none
		sourceColumn: ust_2y_r24

		annotation SummarizationSetBy = Automatic

	column ust_10y
		dataType: double
		formatString: 0.00
		lineageTag: 3d462a10-3256-465d-82e1-2e7a642f8311
		summarizeBy: none
		sourceColumn: ust_10y

		annotation SummarizationSetBy = Automatic

	column ust_10y_r24
		dataType: double
		formatString: 0.00
		lineageTag: eabdb0c5-68a6-43f9-a5ed-28993c11695d
		summarizeBy: none
		sourceColumn: ust_10y_r24

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_2y
		dataType: double
		formatString: 0.00
		lineageTag: d399190c-e6ac-4abc-a8e2-21c07227c5a0
		summarizeBy: none
		sourceColumn: curve_spread_10y_2y

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_2y_r24
		dataType: double
		formatString: 0.00
		lineageTag: f2faa06e-b063-4134-89ff-0bdd21189017
		summarizeBy: none
		sourceColumn: curve_spread_10y_2y_r24

		annotation SummarizationSetBy = Automatic

	column fed_funds_eff
		dataType: double
		formatString: 0.00
		lineageTag: 2b7c6120-7da8-41a3-b810-5f94723917d6
		summarizeBy: none
		sourceColumn: fed_funds_eff

		annotation SummarizationSetBy = Automatic

	column fed_funds_eff_r24
		dataType: double
		formatString: 0.00
		lineageTag: 502cbfe4-5d51-4f60-92d2-d69512d3ffee
		summarizeBy: none
		sourceColumn: fed_funds_eff_r24

		annotation SummarizationSetBy = Automatic

	column cpi_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 980475de-2523-43d8-885d-486931ef856c
		summarizeBy: none
		sourceColumn: cpi_yoy

		annotation SummarizationSetBy = Automatic

	column cpi_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 11505241-13a7-4a84-8f20-be323abe83a3
		summarizeBy: none
		sourceColumn: cpi_yoy_r24

		annotation SummarizationSetBy = Automatic

	column pce_yoy
		dataType: double
		formatString: 0.00
		lineageTag: e189e5d2-a011-4a98-8078-f7585976dd07
		summarizeBy: none
		sourceColumn: pce_yoy

		annotation SummarizationSetBy = Automatic

	column pce_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 5ae80f08-3694-4417-820b-e1138d5ebe42
		summarizeBy: none
		sourceColumn: pce_yoy_r24

		annotation SummarizationSetBy = Automatic

	column gdp_growth_yoy
		dataType: double
		formatString: 0.00
		lineageTag: d3513249-22f1-42bd-beb2-656e735588f2
		summarizeBy: none
		sourceColumn: gdp_growth_yoy

		annotation SummarizationSetBy = Automatic

	column gdp_growth_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: f3e9940a-a4a2-4d8e-8fcd-06b68f5109fb
		summarizeBy: none
		sourceColumn: gdp_growth_yoy_r24

		annotation SummarizationSetBy = Automatic

	column unemployment_rate
		dataType: double
		formatString: 0.00
		lineageTag: 6626bfb5-1a12-4b0c-bf72-065309d78a17
		summarizeBy: none
		sourceColumn: unemployment_rate

		annotation SummarizationSetBy = Automatic

	column unemployment_rate_r24
		dataType: double
		formatString: 0.00
		lineageTag: 02c774f3-743f-4f22-ba07-6096d44d5873
		summarizeBy: none
		sourceColumn: unemployment_rate_r24

		annotation SummarizationSetBy = Automatic

	column ig_oas
		dataType: double
		formatString: 0.00
		lineageTag: 903b2543-938f-4cf1-95da-60c12c0cd967
		summarizeBy: none
		sourceColumn: ig_oas

		annotation SummarizationSetBy = Automatic

	column ig_oas_r24
		dataType: double
		formatString: 0.00
		lineageTag: 99cbbd0d-237d-493a-8b57-659346d1a65b
		summarizeBy: none
		sourceColumn: ig_oas_r24

		annotation SummarizationSetBy = Automatic

	column hy_oas
		dataType: double
		formatString: 0.00
		lineageTag: 2236c14b-4307-411b-b1ce-74b520fb0cd9
		summarizeBy: none
		sourceColumn: hy_oas

		annotation SummarizationSetBy = Automatic

	column hy_oas_r24
		dataType: double
		formatString: 0.00
		lineageTag: b09288e1-2aec-4656-b22d-f783fea9be2b
		summarizeBy: none
		sourceColumn: hy_oas_r24

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		lineageTag: e0448898-030f-4bfd-9390-42620197e264
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 933671f4-fa95-4656-999a-ca5d610119b0
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	column ust_3m
		dataType: double
		formatString: 0.00
		lineageTag: cf82ed6f-fe30-40be-9d0a-b7fc823e96eb
		summarizeBy: none
		sourceColumn: ust_3m

		annotation SummarizationSetBy = Automatic

	column ust_3m_r24
		dataType: double
		formatString: 0.00
		lineageTag: d389210a-4bf9-46b3-88a0-89bf80fd2b19
		summarizeBy: none
		sourceColumn: ust_3m_r24

		annotation SummarizationSetBy = Automatic

	column ust_5y
		dataType: double
		formatString: 0.00
		lineageTag: af615540-0029-4333-a424-6bc55aab93bf
		summarizeBy: none
		sourceColumn: ust_5y

		annotation SummarizationSetBy = Automatic

	column ust_5y_r24
		dataType: double
		formatString: 0.00
		lineageTag: 8ef2dd28-c63c-4434-898f-98e97e056c89
		summarizeBy: none
		sourceColumn: ust_5y_r24

		annotation SummarizationSetBy = Automatic

	column ust_30y
		dataType: double
		formatString: 0.00
		lineageTag: a4124b17-5a2f-412f-8626-6a301564ade0
		summarizeBy: none
		sourceColumn: ust_30y

		annotation SummarizationSetBy = Automatic

	column ust_30y_r24
		dataType: double
		formatString: 0.00
		lineageTag: 3712b771-154d-4f39-b531-040573a14393
		summarizeBy: none
		sourceColumn: ust_30y_r24

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_3m
		dataType: double
		formatString: 0.00
		lineageTag: 8fbb7b85-5025-48c2-b105-44cef9fd11a7
		summarizeBy: none
		sourceColumn: curve_spread_10y_3m

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_3m_r24
		dataType: double
		formatString: 0.00
		lineageTag: 3ab9d45e-e621-4dd5-8532-640419dba4ad
		summarizeBy: none
		sourceColumn: curve_spread_10y_3m_r24

		annotation SummarizationSetBy = Automatic

	column core_cpi_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 42e015aa-5537-4e1e-a693-a371904323dc
		summarizeBy: none
		sourceColumn: core_cpi_yoy

		annotation SummarizationSetBy = Automatic

	column core_cpi_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 4c87f684-d417-4ae1-9ef3-c49ac1e8e923
		summarizeBy: none
		sourceColumn: core_cpi_yoy_r24

		annotation SummarizationSetBy = Automatic

	column core_pce_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 8796dc2b-bfba-4def-bce3-b67be2431614
		summarizeBy: none
		sourceColumn: core_pce_yoy

		annotation SummarizationSetBy = Automatic

	column core_pce_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 447d3c8f-6181-4ba3-bc8e-0186504c6015
		summarizeBy: none
		sourceColumn: core_pce_yoy_r24

		annotation SummarizationSetBy = Automatic

	column ppi_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 8e20ea45-ad09-42b7-a6f5-f26f28f719e2
		summarizeBy: none
		sourceColumn: ppi_yoy

		annotation SummarizationSetBy = Automatic

	column ppi_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 121062e1-0e66-43dc-9784-c20b643ca5b7
		summarizeBy: none
		sourceColumn: ppi_yoy_r24

		annotation SummarizationSetBy = Automatic

	column ahe_yoy
		dataType: double
		formatString: 0.00
		lineageTag: bceaeb53-2a49-4c9c-8821-77262295a353
		summarizeBy: none
		sourceColumn: ahe_yoy

		annotation SummarizationSetBy = Automatic

	column ahe_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 31161186-5985-4a1a-ab57-3a3201ecb21a
		summarizeBy: none
		sourceColumn: ahe_yoy_r24

		annotation SummarizationSetBy = Automatic

	column indprod_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 9dbd268a-7993-40a3-9484-0862cb56c10f
		summarizeBy: none
		sourceColumn: indprod_yoy

		annotation SummarizationSetBy = Automatic

	column indprod_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: e44eb917-a95c-4ed1-9a9a-57fad42bcb37
		summarizeBy: none
		sourceColumn: indprod_yoy_r24

		annotation SummarizationSetBy = Automatic

	column retail_sales_yoy
		dataType: double
		formatString: 0.00
		lineageTag: 8272c387-acd0-4e9c-9565-063be53470f4
		summarizeBy: none
		sourceColumn: retail_sales_yoy

		annotation SummarizationSetBy = Automatic

	column retail_sales_yoy_r24
		dataType: double
		formatString: 0.00
		lineageTag: 0d9f3e95-d6ae-41ff-bc9c-fa1b9a13ba3d
		summarizeBy: none
		sourceColumn: retail_sales_yoy_r24

		annotation SummarizationSetBy = Automatic

	column u6_rate
		dataType: double
		formatString: 0.00
		lineageTag: bf6873b0-fd31-498c-897e-f41b9dec407a
		summarizeBy: none
		sourceColumn: u6_rate

		annotation SummarizationSetBy = Automatic

	column u6_rate_r24
		dataType: double
		formatString: 0.00
		lineageTag: a92906c1-af46-48ef-bcfe-d35db8127fc0
		summarizeBy: none
		sourceColumn: u6_rate_r24

		annotation SummarizationSetBy = Automatic

	column participation_rate
		dataType: double
		formatString: 0.00
		lineageTag: af6231f4-8d72-4970-992f-8e18e53e8a3d
		summarizeBy: none
		sourceColumn: participation_rate

		annotation SummarizationSetBy = Automatic

	column participation_rate_r24
		dataType: double
		formatString: 0.00
		lineageTag: 3109b734-2b66-4bb2-865a-59f1c10161ef
		summarizeBy: none
		sourceColumn: participation_rate_r24

		annotation SummarizationSetBy = Automatic

	column unemp_duration_weeks
		dataType: double
		formatString: 0.00
		lineageTag: d49c3302-9bd3-41cb-9369-871d4ea6be5c
		summarizeBy: none
		sourceColumn: unemp_duration_weeks

		annotation SummarizationSetBy = Automatic

	column unemp_duration_weeks_r24
		dataType: double
		formatString: 0.00
		lineageTag: 616759cb-5a41-4cab-96fe-055894f85adf
		summarizeBy: none
		sourceColumn: unemp_duration_weeks_r24

		annotation SummarizationSetBy = Automatic

	column initial_claims_k
		dataType: double
		formatString: 0.00
		lineageTag: cc865c6e-b799-4d11-87fe-aa6bc3a1a116
		summarizeBy: none
		sourceColumn: initial_claims_k

		annotation SummarizationSetBy = Automatic

	column initial_claims_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: a60884a6-297d-419f-9e2e-cd01eabbfb79
		summarizeBy: none
		sourceColumn: initial_claims_k_r24

		annotation SummarizationSetBy = Automatic

	column continuing_claims_k
		dataType: double
		formatString: 0.00
		lineageTag: 8455ec72-e09d-4f5b-8a0f-1b7648b552dc
		summarizeBy: none
		sourceColumn: continuing_claims_k

		annotation SummarizationSetBy = Automatic

	column continuing_claims_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 872078e6-9553-4560-98c9-f2394e1de4e4
		summarizeBy: none
		sourceColumn: continuing_claims_k_r24

		annotation SummarizationSetBy = Automatic

	column payroll_chg_k
		dataType: double
		formatString: 0.00
		lineageTag: dad9b832-7004-4d8f-99f0-ba90cb25e914
		summarizeBy: none
		sourceColumn: payroll_chg_k

		annotation SummarizationSetBy = Automatic

	column payroll_chg_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 2ef7ff7c-a5ff-4c49-a6eb-0a829ba1bf1d
		summarizeBy: none
		sourceColumn: payroll_chg_k_r24

		annotation SummarizationSetBy = Automatic

	column jolts_openings_k
		dataType: double
		formatString: 0.00
		lineageTag: 7b4ec23a-6ca2-4a95-922a-307e40f357ed
		summarizeBy: none
		sourceColumn: jolts_openings_k

		annotation SummarizationSetBy = Automatic

	column jolts_openings_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 74ef23b0-39ab-4137-bf88-c223a635d40f
		summarizeBy: none
		sourceColumn: jolts_openings_k_r24

		annotation SummarizationSetBy = Automatic

	column housing_starts_k
		dataType: double
		formatString: 0.00
		lineageTag: b873cd9d-9741-4865-9453-31a1dfea0e64
		summarizeBy: none
		sourceColumn: housing_starts_k

		annotation SummarizationSetBy = Automatic

	column housing_starts_k_r24
		dataType: double
		formatString: 0.00
		lineageTag: 0e43a9ce-3213-465c-8c76-677bb1a37323
		summarizeBy: none
		sourceColumn: housing_starts_k_r24

		annotation SummarizationSetBy = Automatic

	column consumer_sentiment_idx
		dataType: double
		formatString: 0.00
		lineageTag: 3f435e20-9f5a-44f4-ae78-5f79b1327304
		summarizeBy: none
		sourceColumn: consumer_sentiment_idx

		annotation SummarizationSetBy = Automatic

	column consumer_sentiment_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: 51ec5d58-f8c9-4411-88f2-1033476958ef
		summarizeBy: none
		sourceColumn: consumer_sentiment_idx_r24

		annotation SummarizationSetBy = Automatic

	column ism_pmi_idx
		dataType: double
		formatString: 0.00
		lineageTag: 11d8ae74-20e2-453a-a612-d73c333bdbc7
		summarizeBy: none
		sourceColumn: ism_pmi_idx

		annotation SummarizationSetBy = Automatic

	column ism_pmi_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: 888932f8-0725-4e4f-b419-3c87160b712f
		summarizeBy: none
		sourceColumn: ism_pmi_idx_r24

		annotation SummarizationSetBy = Automatic

	column gold_usd_oz
		dataType: double
		formatString: 0.00
		lineageTag: 7abf9504-51e0-458a-b5e3-068aa81aaa35
		summarizeBy: none
		sourceColumn: gold_usd_oz

		annotation SummarizationSetBy = Automatic

	column gold_usd_oz_r24
		dataType: double
		formatString: 0.00
		lineageTag: e0d2a147-f0f7-4fc6-a508-b043c169208a
		summarizeBy: none
		sourceColumn: gold_usd_oz_r24

		annotation SummarizationSetBy = Automatic

	column silver_usd_oz
		dataType: double
		formatString: 0.00
		lineageTag: c702f0ea-ef84-4122-8958-df849edabfb8
		summarizeBy: none
		sourceColumn: silver_usd_oz

		annotation SummarizationSetBy = Automatic

	column silver_usd_oz_r24
		dataType: double
		formatString: 0.00
		lineageTag: b5877f40-8860-42d1-9c28-30d04dc8160a
		summarizeBy: none
		sourceColumn: silver_usd_oz_r24

		annotation SummarizationSetBy = Automatic

	column oil_wti_usd_bbl
		dataType: double
		formatString: 0.00
		lineageTag: fcfcef99-4c1b-4bc1-9b47-08a2da358150
		summarizeBy: none
		sourceColumn: oil_wti_usd_bbl

		annotation SummarizationSetBy = Automatic

	column oil_wti_usd_bbl_r24
		dataType: double
		formatString: 0.00
		lineageTag: 9737a87b-2cb1-4753-ae41-79dfdf046a53
		summarizeBy: none
		sourceColumn: oil_wti_usd_bbl_r24

		annotation SummarizationSetBy = Automatic

	column brent_usd_bbl
		dataType: double
		formatString: 0.00
		lineageTag: fd93c821-0381-444a-80df-37d93bd3371c
		summarizeBy: none
		sourceColumn: brent_usd_bbl

		annotation SummarizationSetBy = Automatic

	column brent_usd_bbl_r24
		dataType: double
		formatString: 0.00
		lineageTag: 48dad70c-531e-401d-9fed-4466d875d361
		summarizeBy: none
		sourceColumn: brent_usd_bbl_r24

		annotation SummarizationSetBy = Automatic

	column beef_usd_lb
		dataType: double
		formatString: 0.00
		lineageTag: 1fb0138b-fb51-4d87-a832-d6f8044904af
		summarizeBy: none
		sourceColumn: beef_usd_lb

		annotation SummarizationSetBy = Automatic

	column beef_usd_lb_r24
		dataType: double
		formatString: 0.00
		lineageTag: 5a3245bc-d780-4d9a-a692-ef1e27b2da36
		summarizeBy: none
		sourceColumn: beef_usd_lb_r24

		annotation SummarizationSetBy = Automatic

	column tech_sector_idx
		dataType: double
		formatString: 0.00
		lineageTag: b1b05564-7379-4b4d-a478-08f6a1f6b72a
		summarizeBy: none
		sourceColumn: tech_sector_idx

		annotation SummarizationSetBy = Automatic

	column tech_sector_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: 32fa8896-bde0-4d42-b79f-d930dba1ce17
		summarizeBy: none
		sourceColumn: tech_sector_idx_r24

		annotation SummarizationSetBy = Automatic

	column ai_sector_idx
		dataType: double
		formatString: 0.00
		lineageTag: 425a8b84-1239-4139-ab83-e7dc56f3234c
		summarizeBy: none
		sourceColumn: ai_sector_idx

		annotation SummarizationSetBy = Automatic

	column ai_sector_idx_r24
		dataType: double
		formatString: 0.00
		lineageTag: b4f89a51-dbc9-40f2-9cff-5dcf1b767aa2
		summarizeBy: none
		sourceColumn: ai_sector_idx_r24

		annotation SummarizationSetBy = Automatic

	column tech_co_1_px
		dataType: double
		formatString: 0.00
		lineageTag: 8e51f657-5697-4f96-b3d3-268736a9ba12
		summarizeBy: none
		sourceColumn: tech_co_1_px

		annotation SummarizationSetBy = Automatic

	column tech_co_1_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 1711ae95-45b5-442b-9a06-e73bf1c3636c
		summarizeBy: none
		sourceColumn: tech_co_1_px_r24

		annotation SummarizationSetBy = Automatic

	column tech_co_2_px
		dataType: double
		formatString: 0.00
		lineageTag: 74d57b33-b1c7-4cfa-99f7-24059ad2d0a7
		summarizeBy: none
		sourceColumn: tech_co_2_px

		annotation SummarizationSetBy = Automatic

	column tech_co_2_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 7a21ca66-22a3-40d5-adb4-62cce2ad1b88
		summarizeBy: none
		sourceColumn: tech_co_2_px_r24

		annotation SummarizationSetBy = Automatic

	column tech_co_3_px
		dataType: double
		formatString: 0.00
		lineageTag: 983770dc-613d-49f6-80a5-dce3747a2dd3
		summarizeBy: none
		sourceColumn: tech_co_3_px

		annotation SummarizationSetBy = Automatic

	column tech_co_3_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 4d15531b-a0f9-4f0c-9002-cc49532648c9
		summarizeBy: none
		sourceColumn: tech_co_3_px_r24

		annotation SummarizationSetBy = Automatic

	column tech_co_4_px
		dataType: double
		formatString: 0.00
		lineageTag: 6d93d63a-4e41-4848-8697-9c6cca0b610d
		summarizeBy: none
		sourceColumn: tech_co_4_px

		annotation SummarizationSetBy = Automatic

	column tech_co_4_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: a853d1b4-b4d9-4bb1-b3c9-8f933e078f97
		summarizeBy: none
		sourceColumn: tech_co_4_px_r24

		annotation SummarizationSetBy = Automatic

	column tech_co_5_px
		dataType: double
		formatString: 0.00
		lineageTag: 6224b13c-9595-41ed-8bd3-aae7d618a58a
		summarizeBy: none
		sourceColumn: tech_co_5_px

		annotation SummarizationSetBy = Automatic

	column tech_co_5_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 4f348c05-4b1b-4bd3-8e5c-4533a67dbfc9
		summarizeBy: none
		sourceColumn: tech_co_5_px_r24

		annotation SummarizationSetBy = Automatic

	column ai_co_1_px
		dataType: double
		formatString: 0.00
		lineageTag: 762afb5f-2a50-445a-8891-ebfe2e23963c
		summarizeBy: none
		sourceColumn: ai_co_1_px

		annotation SummarizationSetBy = Automatic

	column ai_co_1_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 945ad2c9-ad75-4eb0-9c57-845321797752
		summarizeBy: none
		sourceColumn: ai_co_1_px_r24

		annotation SummarizationSetBy = Automatic

	column ai_co_2_px
		dataType: double
		formatString: 0.00
		lineageTag: 6207aa1f-b80e-4ba6-a507-18a8b5d25447
		summarizeBy: none
		sourceColumn: ai_co_2_px

		annotation SummarizationSetBy = Automatic

	column ai_co_2_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 662a50ea-ce55-4624-aea6-0d2871f56371
		summarizeBy: none
		sourceColumn: ai_co_2_px_r24

		annotation SummarizationSetBy = Automatic

	column ai_co_3_px
		dataType: double
		formatString: 0.00
		lineageTag: 53e00608-9d86-4d22-afff-bf3dd1334fc3
		summarizeBy: none
		sourceColumn: ai_co_3_px

		annotation SummarizationSetBy = Automatic

	column ai_co_3_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 0cde52aa-e8f1-4069-8baa-e849944cf2e2
		summarizeBy: none
		sourceColumn: ai_co_3_px_r24

		annotation SummarizationSetBy = Automatic

	column ai_co_4_px
		dataType: double
		formatString: 0.00
		lineageTag: dd5dc52f-8104-4e15-bdee-12c5dc02ad75
		summarizeBy: none
		sourceColumn: ai_co_4_px

		annotation SummarizationSetBy = Automatic

	column ai_co_4_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 61701e27-958e-4197-896a-44ed048a1346
		summarizeBy: none
		sourceColumn: ai_co_4_px_r24

		annotation SummarizationSetBy = Automatic

	column ai_co_5_px
		dataType: double
		formatString: 0.00
		lineageTag: 72e7c7d3-2dad-4e61-aebf-c36abc9535ac
		summarizeBy: none
		sourceColumn: ai_co_5_px

		annotation SummarizationSetBy = Automatic

	column ai_co_5_px_r24
		dataType: double
		formatString: 0.00
		lineageTag: 80ef8f60-b0bd-4821-9176-9b5b7516ec89
		summarizeBy: none
		sourceColumn: ai_co_5_px_r24

		annotation SummarizationSetBy = Automatic

	partition market_history_rolling24 = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\market_history_rolling24.csv"),
				    [Delimiter = ",", Columns = 97, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"observation_date", "ust_3m", "ust_3m_r24", "ust_2y", "ust_2y_r24", "ust_5y", "ust_5y_r24", "ust_10y", "ust_10y_r24", "ust_30y", "ust_30y_r24", "curve_spread_10y_2y", "curve_spread_10y_2y_r24", "curve_spread_10y_3m", "curve_spread_10y_3m_r24", "fed_funds_eff", "fed_funds_eff_r24", "cpi_yoy", "cpi_yoy_r24", "core_cpi_yoy", "core_cpi_yoy_r24", "pce_yoy", "pce_yoy_r24", "core_pce_yoy", "core_pce_yoy_r24", "ppi_yoy", "ppi_yoy_r24", "ahe_yoy", "ahe_yoy_r24", "gdp_growth_yoy", "gdp_growth_yoy_r24", "indprod_yoy", "indprod_yoy_r24", "retail_sales_yoy", "retail_sales_yoy_r24", "unemployment_rate", "unemployment_rate_r24", "u6_rate", "u6_rate_r24", "participation_rate", "participation_rate_r24", "unemp_duration_weeks", "unemp_duration_weeks_r24", "initial_claims_k", "initial_claims_k_r24", "continuing_claims_k", "continuing_claims_k_r24", "payroll_chg_k", "payroll_chg_k_r24", "jolts_openings_k", "jolts_openings_k_r24", "housing_starts_k", "housing_starts_k_r24", "consumer_sentiment_idx", "consumer_sentiment_idx_r24", "ism_pmi_idx", "ism_pmi_idx_r24", "ig_oas", "ig_oas_r24", "hy_oas", "hy_oas_r24", "gold_usd_oz", "gold_usd_oz_r24", "silver_usd_oz", "silver_usd_oz_r24", "oil_wti_usd_bbl", "oil_wti_usd_bbl_r24", "brent_usd_bbl", "brent_usd_bbl_r24", "beef_usd_lb", "beef_usd_lb_r24", "tech_sector_idx", "tech_sector_idx_r24", "ai_sector_idx", "ai_sector_idx_r24", "tech_co_1_px", "tech_co_1_px_r24", "tech_co_2_px", "tech_co_2_px_r24", "tech_co_3_px", "tech_co_3_px_r24", "tech_co_4_px", "tech_co_4_px_r24", "tech_co_5_px", "tech_co_5_px_r24", "ai_co_1_px", "ai_co_1_px_r24", "ai_co_2_px", "ai_co_2_px_r24", "ai_co_3_px", "ai_co_3_px_r24", "ai_co_4_px", "ai_co_4_px_r24", "ai_co_5_px", "ai_co_5_px_r24", "source", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {{"observation_date", type date}, {"ust_3m", type number}, {"ust_3m_r24", type number}, {"ust_2y", type number}, {"ust_2y_r24", type number}, {"ust_5y", type number}, {"ust_5y_r24", type number}, {"ust_10y", type number}, {"ust_10y_r24", type number}, {"ust_30y", type number}, {"ust_30y_r24", type number}, {"curve_spread_10y_2y", type number}, {"curve_spread_10y_2y_r24", type number}, {"curve_spread_10y_3m", type number}, {"curve_spread_10y_3m_r24", type number}, {"fed_funds_eff", type number}, {"fed_funds_eff_r24", type number}, {"cpi_yoy", type number}, {"cpi_yoy_r24", type number}, {"core_cpi_yoy", type number}, {"core_cpi_yoy_r24", type number}, {"pce_yoy", type number}, {"pce_yoy_r24", type number}, {"core_pce_yoy", type number}, {"core_pce_yoy_r24", type number}, {"ppi_yoy", type number}, {"ppi_yoy_r24", type number}, {"ahe_yoy", type number}, {"ahe_yoy_r24", type number}, {"gdp_growth_yoy", type number}, {"gdp_growth_yoy_r24", type number}, {"indprod_yoy", type number}, {"indprod_yoy_r24", type number}, {"retail_sales_yoy", type number}, {"retail_sales_yoy_r24", type number}, {"unemployment_rate", type number}, {"unemployment_rate_r24", type number}, {"u6_rate", type number}, {"u6_rate_r24", type number}, {"participation_rate", type number}, {"participation_rate_r24", type number}, {"unemp_duration_weeks", type number}, {"unemp_duration_weeks_r24", type number}, {"initial_claims_k", type number}, {"initial_claims_k_r24", type number}, {"continuing_claims_k", type number}, {"continuing_claims_k_r24", type number}, {"payroll_chg_k", type number}, {"payroll_chg_k_r24", type number}, {"jolts_openings_k", type number}, {"jolts_openings_k_r24", type number}, {"housing_starts_k", type number}, {"housing_starts_k_r24", type number}, {"consumer_sentiment_idx", type number}, {"consumer_sentiment_idx_r24", type number}, {"ism_pmi_idx", type number}, {"ism_pmi_idx_r24", type number}, {"ig_oas", type number}, {"ig_oas_r24", type number}, {"hy_oas", type number}, {"hy_oas_r24", type number}, {"gold_usd_oz", type number}, {"gold_usd_oz_r24", type number}, {"silver_usd_oz", type number}, {"silver_usd_oz_r24", type number}, {"oil_wti_usd_bbl", type number}, {"oil_wti_usd_bbl_r24", type number}, {"brent_usd_bbl", type number}, {"brent_usd_bbl_r24", type number}, {"beef_usd_lb", type number}, {"beef_usd_lb_r24", type number}, {"tech_sector_idx", type number}, {"tech_sector_idx_r24", type number}, {"ai_sector_idx", type number}, {"ai_sector_idx_r24", type number}, {"tech_co_1_px", type number}, {"tech_co_1_px_r24", type number}, {"tech_co_2_px", type number}, {"tech_co_2_px_r24", type number}, {"tech_co_3_px", type number}, {"tech_co_3_px_r24", type number}, {"tech_co_4_px", type number}, {"tech_co_4_px_r24", type number}, {"tech_co_5_px", type number}, {"tech_co_5_px_r24", type number}, {"ai_co_1_px", type number}, {"ai_co_1_px_r24", type number}, {"ai_co_2_px", type number}, {"ai_co_2_px_r24", type number}, {"ai_co_3_px", type number}, {"ai_co_3_px_r24", type number}, {"ai_co_4_px", type number}, {"ai_co_4_px_r24", type number}, {"ai_co_5_px", type number}, {"ai_co_5_px_r24", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

