/// Curated pipeline export: every Page 5 series at 03M/06M/12M/24M
/// trailing windows plus calendar YTD, long format behind the page
/// controls. months_ago: 0 = latest month (zoom helper).
table market_history_windows
	lineageTag: cdac78f4-4b41-4477-8b39-59817552eb90

	column observation_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 13bc8067-c1a3-405e-b19f-556ae7eebdfa
		summarizeBy: none
		sourceColumn: observation_date

		annotation SummarizationSetBy = Automatic

	column window
		dataType: string
		lineageTag: d99908fb-2200-46c3-8d41-84f570cdffd8
		summarizeBy: none
		sourceColumn: window

		annotation SummarizationSetBy = Automatic

	column months_ago
		dataType: int64
		formatString: 0
		lineageTag: ee433949-dffe-4b53-8b41-6fa64ca7fc14
		summarizeBy: none
		sourceColumn: months_ago

		annotation SummarizationSetBy = Automatic

	column ust_3m
		dataType: double
		formatString: #,0.00
		lineageTag: dcbe74cf-f683-44b6-b6d9-3fe593395a31
		summarizeBy: none
		sourceColumn: ust_3m

		annotation SummarizationSetBy = Automatic

	column ust_2y
		dataType: double
		formatString: #,0.00
		lineageTag: 0f0423fc-3822-4943-81ea-5bdaa918e46b
		summarizeBy: none
		sourceColumn: ust_2y

		annotation SummarizationSetBy = Automatic

	column ust_5y
		dataType: double
		formatString: #,0.00
		lineageTag: 1d03f095-0be6-4ea3-9d16-badb1d7ffc62
		summarizeBy: none
		sourceColumn: ust_5y

		annotation SummarizationSetBy = Automatic

	column ust_10y
		dataType: double
		formatString: #,0.00
		lineageTag: 6cc674a0-0813-4bd8-8289-77f3f6b9911e
		summarizeBy: none
		sourceColumn: ust_10y

		annotation SummarizationSetBy = Automatic

	column ust_30y
		dataType: double
		formatString: #,0.00
		lineageTag: aaa9ccef-ee66-4d59-9921-37bd10e4e29c
		summarizeBy: none
		sourceColumn: ust_30y

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_2y
		dataType: double
		formatString: #,0.00
		lineageTag: 636cb110-a9cd-4f21-9b08-f46b872bf40b
		summarizeBy: none
		sourceColumn: curve_spread_10y_2y

		annotation SummarizationSetBy = Automatic

	column curve_spread_10y_3m
		dataType: double
		formatString: #,0.00
		lineageTag: 5644c735-c4a0-4d7c-af63-6731a7b5e3ce
		summarizeBy: none
		sourceColumn: curve_spread_10y_3m

		annotation SummarizationSetBy = Automatic

	column fed_funds_eff
		dataType: double
		formatString: #,0.00
		lineageTag: ac4d6856-5737-443a-ad57-c9024858124f
		summarizeBy: none
		sourceColumn: fed_funds_eff

		annotation SummarizationSetBy = Automatic

	column cpi_yoy
		dataType: double
		formatString: #,0.00
		lineageTag: 97e709a4-f6c4-440c-861b-a6f16788e334
		summarizeBy: none
		sourceColumn: cpi_yoy

		annotation SummarizationSetBy = Automatic

	column core_cpi_yoy
		dataType: double
		formatString: #,0.00
		lineageTag: 88f85c9b-a4ad-447c-b203-81a8f83184a4
		summarizeBy: none
		sourceColumn: core_cpi_yoy

		annotation SummarizationSetBy = Automatic

	column pce_yoy
		dataType: double
		formatString: #,0.00
		lineageTag: bdde9fe0-c1db-48b9-88b5-07f216ca8c2f
		summarizeBy: none
		sourceColumn: pce_yoy

		annotation SummarizationSetBy = Automatic

	column core_pce_yoy
		dataType: double
		formatString: #,0.00
		lineageTag: e7f34fb1-36e2-4e92-8819-732a9087c60f
		summarizeBy: none
		sourceColumn: core_pce_yoy

		annotation SummarizationSetBy = Automatic

	column ppi_yoy
		dataType: double
		formatString: #,0.00
		lineageTag: 94693b90-2a57-4906-a18d-ebc91ed6baf2
		summarizeBy: none
		sourceColumn: ppi_yoy

		annotation SummarizationSetBy = Automatic

	column ahe_yoy
		dataType: double
		formatString: #,0.00
		lineageTag: efa291ee-e3be-42b4-9bfd-2d23fade4c08
		summarizeBy: none
		sourceColumn: ahe_yoy

		annotation SummarizationSetBy = Automatic

	column gdp_growth_yoy
		dataType: double
		formatString: #,0.00
		lineageTag: 31989bd3-26cd-439f-aa8c-6fa483329468
		summarizeBy: none
		sourceColumn: gdp_growth_yoy

		annotation SummarizationSetBy = Automatic

	column indprod_yoy
		dataType: double
		formatString: #,0.00
		lineageTag: a9f51857-e592-4aa7-b386-b7d5ec4dde3d
		summarizeBy: none
		sourceColumn: indprod_yoy

		annotation SummarizationSetBy = Automatic

	column retail_sales_yoy
		dataType: double
		formatString: #,0.00
		lineageTag: c8f8c9ef-58d3-4eec-93b8-006a3f20aefb
		summarizeBy: none
		sourceColumn: retail_sales_yoy

		annotation SummarizationSetBy = Automatic

	column unemployment_rate
		dataType: double
		formatString: #,0.00
		lineageTag: 74e7ec3d-5385-41ba-bb3a-9664fa24702a
		summarizeBy: none
		sourceColumn: unemployment_rate

		annotation SummarizationSetBy = Automatic

	column u6_rate
		dataType: double
		formatString: #,0.00
		lineageTag: 0eaefa8d-96c1-4d97-a6f4-012d48a877e7
		summarizeBy: none
		sourceColumn: u6_rate

		annotation SummarizationSetBy = Automatic

	column participation_rate
		dataType: double
		formatString: #,0.00
		lineageTag: 696d548a-fd8c-4e22-a215-c53fd4c73d16
		summarizeBy: none
		sourceColumn: participation_rate

		annotation SummarizationSetBy = Automatic

	column unemp_duration_weeks
		dataType: double
		formatString: #,0.00
		lineageTag: 6a3fa3c5-8f80-4a52-aa32-cd62e26f6b7b
		summarizeBy: none
		sourceColumn: unemp_duration_weeks

		annotation SummarizationSetBy = Automatic

	column initial_claims_k
		dataType: double
		formatString: #,0.00
		lineageTag: 20458d3e-ccdf-480e-aae2-6f5afbdfdb5e
		summarizeBy: none
		sourceColumn: initial_claims_k

		annotation SummarizationSetBy = Automatic

	column continuing_claims_k
		dataType: double
		formatString: #,0.00
		lineageTag: f7506736-a980-4628-8ce4-01ff6ab10832
		summarizeBy: none
		sourceColumn: continuing_claims_k

		annotation SummarizationSetBy = Automatic

	column payroll_chg_k
		dataType: double
		formatString: #,0.00
		lineageTag: 545f29d8-6c47-404c-9dfc-63763f7deeaa
		summarizeBy: none
		sourceColumn: payroll_chg_k

		annotation SummarizationSetBy = Automatic

	column jolts_openings_k
		dataType: double
		formatString: #,0.00
		lineageTag: e78fb24c-d949-4eb0-947d-4f005ed04d78
		summarizeBy: none
		sourceColumn: jolts_openings_k

		annotation SummarizationSetBy = Automatic

	column housing_starts_k
		dataType: double
		formatString: #,0.00
		lineageTag: 16a4d2cc-25e9-4a5f-a1fb-dae2d92c63de
		summarizeBy: none
		sourceColumn: housing_starts_k

		annotation SummarizationSetBy = Automatic

	column consumer_sentiment_idx
		dataType: double
		formatString: #,0.00
		lineageTag: 6d0e4f0d-c49b-40d8-9c25-239d5afb406e
		summarizeBy: none
		sourceColumn: consumer_sentiment_idx

		annotation SummarizationSetBy = Automatic

	column ism_pmi_idx
		dataType: double
		formatString: #,0.00
		lineageTag: 8e7f5a5a-c6eb-4625-bdf6-419f4e6ce240
		summarizeBy: none
		sourceColumn: ism_pmi_idx

		annotation SummarizationSetBy = Automatic

	column ig_oas
		dataType: double
		formatString: #,0.00
		lineageTag: 086ce3d3-9061-4e74-be1c-a610611d1ce8
		summarizeBy: none
		sourceColumn: ig_oas

		annotation SummarizationSetBy = Automatic

	column hy_oas
		dataType: double
		formatString: #,0.00
		lineageTag: d8ca01b1-9eb5-44e4-83b2-f032c0bd3d69
		summarizeBy: none
		sourceColumn: hy_oas

		annotation SummarizationSetBy = Automatic

	column gold_usd_oz
		dataType: double
		formatString: #,0.00
		lineageTag: cc802d77-97d7-41d4-880a-8e6dd50dcc06
		summarizeBy: none
		sourceColumn: gold_usd_oz

		annotation SummarizationSetBy = Automatic

	column silver_usd_oz
		dataType: double
		formatString: #,0.00
		lineageTag: 920ad684-c4d6-4018-adb1-67a542856ca2
		summarizeBy: none
		sourceColumn: silver_usd_oz

		annotation SummarizationSetBy = Automatic

	column oil_wti_usd_bbl
		dataType: double
		formatString: #,0.00
		lineageTag: ce7b9a95-2120-4d23-950c-53dd1e3fad0c
		summarizeBy: none
		sourceColumn: oil_wti_usd_bbl

		annotation SummarizationSetBy = Automatic

	column brent_usd_bbl
		dataType: double
		formatString: #,0.00
		lineageTag: 6c697ead-39eb-4e84-a891-7cc953dd5b8e
		summarizeBy: none
		sourceColumn: brent_usd_bbl

		annotation SummarizationSetBy = Automatic

	column beef_usd_lb
		dataType: double
		formatString: #,0.00
		lineageTag: 502fb6fd-3d1a-4730-befc-0e72d27200e3
		summarizeBy: none
		sourceColumn: beef_usd_lb

		annotation SummarizationSetBy = Automatic

	column tech_sector_idx
		dataType: double
		formatString: #,0.00
		lineageTag: 354d0193-f24b-42f7-bf99-49d0e98bed85
		summarizeBy: none
		sourceColumn: tech_sector_idx

		annotation SummarizationSetBy = Automatic

	column ai_sector_idx
		dataType: double
		formatString: #,0.00
		lineageTag: aee83176-b1d0-46ca-a492-e6448fe3a4cf
		summarizeBy: none
		sourceColumn: ai_sector_idx

		annotation SummarizationSetBy = Automatic

	column dow_idx
		dataType: double
		formatString: #,0.00
		lineageTag: b13fc620-4bb3-4bae-bee5-e257d639dbeb
		summarizeBy: none
		sourceColumn: dow_idx

		annotation SummarizationSetBy = Automatic

	column sp500_idx
		dataType: double
		formatString: #,0.00
		lineageTag: 9272cad6-7c9c-4104-90d2-ef62d51b59dc
		summarizeBy: none
		sourceColumn: sp500_idx

		annotation SummarizationSetBy = Automatic

	column nasdaq_idx
		dataType: double
		formatString: #,0.00
		lineageTag: 4b88c764-a568-4b1c-acf0-29cfefcaeb92
		summarizeBy: none
		sourceColumn: nasdaq_idx

		annotation SummarizationSetBy = Automatic

	column russell2000_idx
		dataType: double
		formatString: #,0.00
		lineageTag: 622204a5-3c23-4bd1-9717-b704247ea0de
		summarizeBy: none
		sourceColumn: russell2000_idx

		annotation SummarizationSetBy = Automatic

	column btc_usd
		dataType: double
		formatString: #,0.00
		lineageTag: 22f58b33-8242-40dd-bfb9-e50339683b6d
		summarizeBy: none
		sourceColumn: btc_usd

		annotation SummarizationSetBy = Automatic

	column tech_co_1_px
		dataType: double
		formatString: #,0.00
		lineageTag: bedb1c71-817a-49fe-9486-85752ad82828
		summarizeBy: none
		sourceColumn: tech_co_1_px

		annotation SummarizationSetBy = Automatic

	column tech_co_2_px
		dataType: double
		formatString: #,0.00
		lineageTag: fb640cfe-a8db-4a94-b162-f94d503da0c1
		summarizeBy: none
		sourceColumn: tech_co_2_px

		annotation SummarizationSetBy = Automatic

	column tech_co_3_px
		dataType: double
		formatString: #,0.00
		lineageTag: 80cd1ebf-4621-4d64-83c3-0960c1d74013
		summarizeBy: none
		sourceColumn: tech_co_3_px

		annotation SummarizationSetBy = Automatic

	column tech_co_4_px
		dataType: double
		formatString: #,0.00
		lineageTag: 919701ad-3e1f-4635-92e6-f5160312fb56
		summarizeBy: none
		sourceColumn: tech_co_4_px

		annotation SummarizationSetBy = Automatic

	column tech_co_5_px
		dataType: double
		formatString: #,0.00
		lineageTag: 10c892d8-86e5-4c06-a3f0-d370b651353b
		summarizeBy: none
		sourceColumn: tech_co_5_px

		annotation SummarizationSetBy = Automatic

	column ai_co_1_px
		dataType: double
		formatString: #,0.00
		lineageTag: 7f7623fb-5342-4921-a2bc-282d9d823fdb
		summarizeBy: none
		sourceColumn: ai_co_1_px

		annotation SummarizationSetBy = Automatic

	column ai_co_2_px
		dataType: double
		formatString: #,0.00
		lineageTag: d22f392b-6936-46d0-8ee9-7ea65a870a4a
		summarizeBy: none
		sourceColumn: ai_co_2_px

		annotation SummarizationSetBy = Automatic

	column ai_co_3_px
		dataType: double
		formatString: #,0.00
		lineageTag: 443db4d1-c733-4b09-b1c7-9dedcc167cc1
		summarizeBy: none
		sourceColumn: ai_co_3_px

		annotation SummarizationSetBy = Automatic

	column ai_co_4_px
		dataType: double
		formatString: #,0.00
		lineageTag: fe509f03-9ce7-4847-a84a-6c2f8d1a871e
		summarizeBy: none
		sourceColumn: ai_co_4_px

		annotation SummarizationSetBy = Automatic

	column ai_co_5_px
		dataType: double
		formatString: #,0.00
		lineageTag: 68ea4a27-21f5-4e3c-b6c5-87536b9f5b51
		summarizeBy: none
		sourceColumn: ai_co_5_px

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		lineageTag: 4b5b1533-2948-46ba-a7a6-480650c3a12a
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 8769978b-08e5-416d-b59b-d3a21cf7ca0e
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	partition market_history_windows = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\market_history_windows.csv"),
				    [Delimiter = ",", Columns = 57, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"observation_date", "window", "months_ago", "ust_3m", "ust_2y", "ust_5y", "ust_10y", "ust_30y", "curve_spread_10y_2y", "curve_spread_10y_3m", "fed_funds_eff", "cpi_yoy", "core_cpi_yoy", "pce_yoy", "core_pce_yoy", "ppi_yoy", "ahe_yoy", "gdp_growth_yoy", "indprod_yoy", "retail_sales_yoy", "unemployment_rate", "u6_rate", "participation_rate", "unemp_duration_weeks", "initial_claims_k", "continuing_claims_k", "payroll_chg_k", "jolts_openings_k", "housing_starts_k", "consumer_sentiment_idx", "ism_pmi_idx", "ig_oas", "hy_oas", "gold_usd_oz", "silver_usd_oz", "oil_wti_usd_bbl", "brent_usd_bbl", "beef_usd_lb", "tech_sector_idx", "ai_sector_idx", "dow_idx", "sp500_idx", "nasdaq_idx", "russell2000_idx", "btc_usd", "tech_co_1_px", "tech_co_2_px", "tech_co_3_px", "tech_co_4_px", "tech_co_5_px", "ai_co_1_px", "ai_co_2_px", "ai_co_3_px", "ai_co_4_px", "ai_co_5_px", "source", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {{"observation_date", type date}, {"months_ago", Int64.Type}, {"ust_3m", type number}, {"ust_2y", type number}, {"ust_5y", type number}, {"ust_10y", type number}, {"ust_30y", type number}, {"curve_spread_10y_2y", type number}, {"curve_spread_10y_3m", type number}, {"fed_funds_eff", type number}, {"cpi_yoy", type number}, {"core_cpi_yoy", type number}, {"pce_yoy", type number}, {"core_pce_yoy", type number}, {"ppi_yoy", type number}, {"ahe_yoy", type number}, {"gdp_growth_yoy", type number}, {"indprod_yoy", type number}, {"retail_sales_yoy", type number}, {"unemployment_rate", type number}, {"u6_rate", type number}, {"participation_rate", type number}, {"unemp_duration_weeks", type number}, {"initial_claims_k", type number}, {"continuing_claims_k", type number}, {"payroll_chg_k", type number}, {"jolts_openings_k", type number}, {"housing_starts_k", type number}, {"consumer_sentiment_idx", type number}, {"ism_pmi_idx", type number}, {"ig_oas", type number}, {"hy_oas", type number}, {"gold_usd_oz", type number}, {"silver_usd_oz", type number}, {"oil_wti_usd_bbl", type number}, {"brent_usd_bbl", type number}, {"beef_usd_lb", type number}, {"tech_sector_idx", type number}, {"ai_sector_idx", type number}, {"dow_idx", type number}, {"sp500_idx", type number}, {"nasdaq_idx", type number}, {"russell2000_idx", type number}, {"btc_usd", type number}, {"tech_co_1_px", type number}, {"tech_co_2_px", type number}, {"tech_co_3_px", type number}, {"tech_co_4_px", type number}, {"tech_co_5_px", type number}, {"ai_co_1_px", type number}, {"ai_co_2_px", type number}, {"ai_co_3_px", type number}, {"ai_co_4_px", type number}, {"ai_co_5_px", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
