/// Curated NFP ML export: ML layer - history vs 12-month MODEL ESTIMATE per series, with category (seed-777 SYNTHETIC).
table nfp_ml_series
	lineageTag: a6001ebd-8c68-4853-a692-591e9440894e

	column row_id
		dataType: string
		lineageTag: 04015a9e-68ef-4608-a9dd-f6f3f23b33a3
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column series_id
		dataType: string
		lineageTag: 75045cfd-c43b-433e-b1a9-42d3d337aeca
		summarizeBy: none
		sourceColumn: series_id

		annotation SummarizationSetBy = Automatic

	column series
		dataType: string
		lineageTag: 7668c712-d398-4783-93ca-c7fb6578c58d
		summarizeBy: none
		sourceColumn: series

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: d78a8af7-adc7-4769-a2fc-dd2bd88176fa
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column month
		dataType: string
		lineageTag: 72e7f7ca-2907-40af-a094-114920f5d29c
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column history_value
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: d0b2bf52-42f2-4465-8ff0-334a0f60ac27
		summarizeBy: none
		sourceColumn: history_value

		annotation SummarizationSetBy = Automatic

	column estimate_value
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 9f93c7cc-0bab-495d-842c-ea1fcf9ea4d5
		summarizeBy: none
		sourceColumn: estimate_value

		annotation SummarizationSetBy = Automatic

	column kind
		dataType: string
		lineageTag: b5d14be0-ea17-4015-993d-3f4bd985ed3c
		summarizeBy: none
		sourceColumn: kind

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 753545b4-5249-485a-a251-20daf1d8a0ba
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	partition nfp_ml_series = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_ml_series.csv"),
				    [Delimiter = ",", Columns = 9, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "series_id", "series", "category", "month", "history_value", "estimate_value", "kind", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"series_id", type text},
				    {"series", type text},
				    {"category", type text},
				    {"month", type text},
				    {"history_value", type number},
				    {"estimate_value", type number},
				    {"kind", type text},
				    {"value_class", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
