/// Playbook ratios from the FILED 990s with targets, verdicts and verdict detail (actual vs target with the gap).
table nfp_990_ratio_actuals
	lineageTag: d6f3ed10-092b-4cf7-9302-47acc0a52600

	measure '990 Op Margin FY25 %' =
			
			CALCULATE(SUM(nfp_990_ratio_actuals[value]), nfp_990_ratio_actuals[ratio_id] = "R990-op_margin_pct-FY2025")
		formatString: 0.00
		displayFolder: NFP Cards
		lineageTag: 1bd19b01-9bdc-450c-be91-d3025ac9b9d2

	measure '990 Months Cash FY25' =
			
			CALCULATE(SUM(nfp_990_ratio_actuals[value]), nfp_990_ratio_actuals[ratio_id] = "R990-months_cash_on_hand-FY2025")
		formatString: 0.00
		displayFolder: NFP Cards
		lineageTag: 0e644670-1f69-4d5f-b821-76bc60b6626d

	measure '990 Revenue Growth FY25 %' =
			
			CALCULATE(SUM(nfp_990_ratio_actuals[value]), nfp_990_ratio_actuals[ratio_id] = "R990-revenue_growth_pct-FY2025")
		formatString: 0.00
		displayFolder: NFP Cards
		lineageTag: 36c11136-1ed0-43ae-bc4c-a64d74f1f092

	measure '990 Program Ratio FY25 %' =
			
			CALCULATE(SUM(nfp_990_ratio_actuals[value]), nfp_990_ratio_actuals[ratio_id] = "R990-program_expense_ratio_pct-FY2025")
		formatString: 0.00
		displayFolder: NFP Cards
		lineageTag: bfa33286-973e-493a-870f-62957861451c

	measure '990 Real Ratios' =
			
			COUNTROWS(FILTER(nfp_990_ratio_actuals, NOT ISBLANK(nfp_990_ratio_actuals[value])))
		formatString: 0
		displayFolder: NFP Cards
		lineageTag: 7c4c059b-a86f-426e-a63c-c38733109c99

	measure 'Reserve Months FY25' =
			
			CALCULATE(SUM(nfp_990_ratio_actuals[value]), nfp_990_ratio_actuals[ratio_id] = "R990-operating_reserve_months-FY2025")
		formatString: 0.00
		displayFolder: NFP Cards
		lineageTag: 48c930cf-f3d7-43f1-9d03-fd8a290deeb8

	measure 'Revenue Concentration FY25 %' =
			
			CALCULATE(SUM(nfp_990_ratio_actuals[value]), nfp_990_ratio_actuals[ratio_id] = "R990-revenue_concentration_pct-FY2025")
		formatString: 0.00
		displayFolder: NFP Cards
		lineageTag: ece5e634-180b-4b2e-b641-a13872ac75a4

	column row_id
		dataType: string
		lineageTag: 21f0c12c-c096-4083-8535-68dc755ff521
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column ratio_id
		dataType: string
		lineageTag: 8f7e6bae-d844-4985-89e4-0b074c20971d
		summarizeBy: none
		sourceColumn: ratio_id

		annotation SummarizationSetBy = Automatic

	column ratio_kind
		dataType: string
		lineageTag: e1fa80dc-054c-44f2-80f0-3de6e9861b3f
		summarizeBy: none
		sourceColumn: ratio_kind

		annotation SummarizationSetBy = Automatic

	column ratio
		dataType: string
		lineageTag: b9d4895d-a71e-4348-a458-3017f6ac8034
		summarizeBy: none
		sourceColumn: ratio

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: string
		lineageTag: a4803731-52bc-44fb-b856-2eb839922f51
		summarizeBy: none
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: b9c80373-7f80-4f8b-a172-69c4fb6d70ad
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: f77484d4-72e4-44d3-b4f5-d66dde9f0b43
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column formula_990
		dataType: string
		lineageTag: 0eb17902-87fe-4b5b-982a-1eca50ff9984
		summarizeBy: none
		sourceColumn: formula_990

		annotation SummarizationSetBy = Automatic

	column basis
		dataType: string
		lineageTag: e5792563-c344-4f99-bb94-958ff21cb055
		summarizeBy: none
		sourceColumn: basis

		annotation SummarizationSetBy = Automatic

	column confidence
		dataType: string
		lineageTag: a9300d52-152e-4ca1-850c-af5b9fee01e6
		summarizeBy: none
		sourceColumn: confidence

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 0f632579-6054-4e62-b050-1eba63eb6e85
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	column note
		dataType: string
		lineageTag: 90b10b47-6f24-454d-84f6-189de1dad84c
		summarizeBy: none
		sourceColumn: note

		annotation SummarizationSetBy = Automatic

	column target_value
		dataType: double
		formatString: #,0.00;(#,0.00)
		lineageTag: af247edb-da07-4692-afb6-33cbacf73e2b
		summarizeBy: none
		sourceColumn: target_value

		annotation SummarizationSetBy = Automatic

	column target_direction
		dataType: string
		lineageTag: cfe463f7-010a-43f3-988b-0a6e44064a9a
		summarizeBy: none
		sourceColumn: target_direction

		annotation SummarizationSetBy = Automatic

	column target_label
		dataType: string
		lineageTag: 4aac6fab-10c0-4c85-9207-58fa87a42a11
		summarizeBy: none
		sourceColumn: target_label

		annotation SummarizationSetBy = Automatic

	column target_class
		dataType: string
		lineageTag: e2c287d7-0f35-49b6-baa5-72bb42087185
		summarizeBy: none
		sourceColumn: target_class

		annotation SummarizationSetBy = Automatic

	column vs_target
		dataType: string
		lineageTag: e8e609eb-44f9-4ab8-b51c-253d13e54291
		summarizeBy: none
		sourceColumn: vs_target

		annotation SummarizationSetBy = Automatic

	column verdict_detail
		dataType: string
		lineageTag: 8d65e8ef-f96f-414f-a5d0-3df28188595b
		summarizeBy: none
		sourceColumn: verdict_detail

		annotation SummarizationSetBy = Automatic

	partition nfp_990_ratio_actuals = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_990_ratio_actuals.csv"),
				    [Delimiter = ",", Columns = 18, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "ratio_id", "ratio_kind", "ratio", "fiscal_year", "value", "unit", "formula_990", "basis", "confidence", "value_class", "note", "target_value", "target_direction", "target_label", "target_class", "vs_target", "verdict_detail"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"ratio_id", type text},
				    {"ratio_kind", type text},
				    {"ratio", type text},
				    {"fiscal_year", type text},
				    {"value", type number},
				    {"unit", type text},
				    {"formula_990", type text},
				    {"basis", type text},
				    {"confidence", type text},
				    {"value_class", type text},
				    {"note", type text},
				    {"target_value", type number},
				    {"target_direction", type text},
				    {"target_label", type text},
				    {"target_class", type text},
				    {"vs_target", type text},
				    {"verdict_detail", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
