/// REAL filed Form 990 figures for JSV (EIN 94-2222989) read directly from the FY2021-FY2025 filings the owner provided - PUBLIC_RESEARCH, HIGH confidence, never estimated.
table nfp_990_actuals
	lineageTag: 17c453f2-8f0e-473f-9c06-c479ea739d18

	measure '990 FY25 Revenue' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[fiscal_year] = "FY2025", nfp_990_actuals[line_item] = "total_revenue")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: 710e9fa8-4f3a-4dbd-a8a8-c9eab93e25a2

	measure '990 FY25 Expenses' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[fiscal_year] = "FY2025", nfp_990_actuals[line_item] = "total_expenses")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: 864133cb-2309-41c6-888e-cad29a054dcc

	measure '990 FY25 Net Assets' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[fiscal_year] = "FY2025", nfp_990_actuals[line_item] = "net_assets_end")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: 1a24b466-35a5-4c6a-bb67-c3e476b92916

	measure '990 FY25 Surplus' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[fiscal_year] = "FY2025", nfp_990_actuals[line_item] = "surplus_deficit")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: fcc73736-7717-435c-bf4e-45d2028d9454

	measure '990 FY25 Investments' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[fiscal_year] = "FY2025", nfp_990_actuals[line_item] = "investments_securities_end")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: 010a7cc4-f1c7-4f84-8dee-e7d91e186649

	column row_id
		dataType: string
		lineageTag: 30329039-b7fd-46a2-9dcd-710441513a60
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column item_id
		dataType: string
		lineageTag: 851c6264-e1b6-408a-9afa-93ee69bc4536
		summarizeBy: none
		sourceColumn: item_id

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: string
		lineageTag: e0bc0afe-30db-4248-bf31-aa63dee310b2
		summarizeBy: none
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column fiscal_year_end
		dataType: string
		lineageTag: eb8a0f97-9afa-484c-b510-5e158c591853
		summarizeBy: none
		sourceColumn: fiscal_year_end

		annotation SummarizationSetBy = Automatic

	column line_item
		dataType: string
		lineageTag: 2ad16931-5ae2-44b3-bad6-1ed413bbb663
		summarizeBy: none
		sourceColumn: line_item

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		lineageTag: adb81b3a-2c67-4b21-b05e-c0c261d32b81
		summarizeBy: none
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: bd345e43-9311-404c-9726-017879649337
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column basis
		dataType: string
		lineageTag: 679dd4ac-e03e-46c4-9964-8b1e290cf8d9
		summarizeBy: none
		sourceColumn: basis

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		lineageTag: 1eec0ce0-6946-41d7-81b9-615467321793
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 763a37b7-468f-4f72-b778-3598dd98f8c1
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	column date_verified
		dataType: string
		lineageTag: 8be60ab9-3a61-44a5-a7ee-f89b436bd779
		summarizeBy: none
		sourceColumn: date_verified

		annotation SummarizationSetBy = Automatic

	column confidence
		dataType: string
		lineageTag: 56935812-6a6b-4499-bc4e-618e40671c04
		summarizeBy: none
		sourceColumn: confidence

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: e46df730-23c7-49ce-866d-4761e4357d3a
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	column note
		dataType: string
		lineageTag: cfd61c9e-b659-475f-b0d3-77c46664ebbc
		summarizeBy: none
		sourceColumn: note

		annotation SummarizationSetBy = Automatic

	partition nfp_990_actuals = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_990_actuals.csv"),
				    [Delimiter = ",", Columns = 14, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "item_id", "fiscal_year", "fiscal_year_end", "line_item", "amount", "unit", "basis", "source", "url", "date_verified", "confidence", "value_class", "note"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"item_id", type text},
				    {"fiscal_year", type text},
				    {"fiscal_year_end", type text},
				    {"line_item", type text},
				    {"amount", type number},
				    {"unit", type text},
				    {"basis", type text},
				    {"source", type text},
				    {"url", type text},
				    {"date_verified", type text},
				    {"confidence", type text},
				    {"value_class", type text},
				    {"note", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
