/// YoY FY2024 vs FY2025: statement lines (variance $ and %) and every ratio with its FY2025 arithmetic shown inline.
table nfp_990_yoy
	lineageTag: 69b48003-7741-4cfc-8049-c8efe0687438

	column row_id
		dataType: string
		lineageTag: 514e05a2-189a-471b-be3c-0e3d3ecb8297
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column section
		dataType: string
		lineageTag: 3d062b0b-bd4d-4ae1-8a18-f411c8149fd4
		summarizeBy: none
		sourceColumn: section

		annotation SummarizationSetBy = Automatic

	column line_label
		dataType: string
		lineageTag: 0213d9de-7a22-43ad-8fa2-d9f722133da2
		summarizeBy: none
		sourceColumn: line_label

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: 7d8a353f-a4f9-46e2-920b-b86db5ad473b
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column fy2024
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 77728a4b-7b32-4284-ab79-df5123adbe04
		summarizeBy: none
		sourceColumn: fy2024

		annotation SummarizationSetBy = Automatic

	column fy2025
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 281cfbb1-7061-40f0-be23-35c546d80c41
		summarizeBy: none
		sourceColumn: fy2025

		annotation SummarizationSetBy = Automatic

	column variance
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 779de91c-e69a-4514-8da9-bc7c5971c9a6
		summarizeBy: none
		sourceColumn: variance

		annotation SummarizationSetBy = Automatic

	column variance_pct
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: b65bc491-a487-4a8b-a7e8-71184976b53d
		summarizeBy: none
		sourceColumn: variance_pct

		annotation SummarizationSetBy = Automatic

	column math_fy2025
		dataType: string
		lineageTag: a655ff47-0e97-42de-ba86-38f5d2476595
		summarizeBy: none
		sourceColumn: math_fy2025

		annotation SummarizationSetBy = Automatic

	column note
		dataType: string
		lineageTag: 2dad801e-9ed1-4829-ae51-a96f9e25729d
		summarizeBy: none
		sourceColumn: note

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 0caa2a62-cf40-464f-8039-7e1b0ca7b2d2
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	partition nfp_990_yoy = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_990_yoy.csv"),
				    [Delimiter = ",", Columns = 11, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "section", "line_label", "unit", "fy2024", "fy2025", "variance", "variance_pct", "math_fy2025", "note", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"section", type text},
				    {"line_label", type text},
				    {"unit", type text},
				    {"fy2024", type number},
				    {"fy2025", type number},
				    {"variance", type number},
				    {"variance_pct", type number},
				    {"math_fy2025", type text},
				    {"note", type text},
				    {"value_class", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
