/// REAL filed Form 990 figures for JSV (EIN 94-2222989) read directly from the FY2021-FY2025 filings the owner provided - PUBLIC_RESEARCH, HIGH confidence, never estimated.
table nfp_990_actuals
	lineageTag: b99a6d21-dde8-48f3-b379-ee8992df7695

	measure '990 FY25 Revenue' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[fiscal_year] = "FY2025", nfp_990_actuals[line_item] = "total_revenue")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: 24b73d6b-4b06-42b8-b35a-91cfc519bbc1

	measure '990 FY25 Expenses' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[fiscal_year] = "FY2025", nfp_990_actuals[line_item] = "total_expenses")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: 721abf56-affe-4f52-9798-2bd732aad274

	measure '990 FY25 Net Assets' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[fiscal_year] = "FY2025", nfp_990_actuals[line_item] = "net_assets_end")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: ce7cc6c4-8797-411d-bc45-e163d3474bef

	measure '990 FY25 Surplus' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[fiscal_year] = "FY2025", nfp_990_actuals[line_item] = "surplus_deficit")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: 62d2497c-b2d5-499b-8c66-3bf4c46552d1

	measure '990 FY25 Investments' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[fiscal_year] = "FY2025", nfp_990_actuals[line_item] = "investments_securities_end")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: 341460b7-34c6-4ba5-afe2-ee4c4592d7fe

	measure '990 Filed Revenue $' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[line_item] = "total_revenue")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: a384e163-ab72-4f00-9c4b-99667c4a2223

	measure '990 Filed Expenses $' =
			
			CALCULATE(SUM(nfp_990_actuals[amount]), nfp_990_actuals[line_item] = "total_expenses")
		formatString: $#,0
		displayFolder: NFP Cards
		lineageTag: 9a985e25-2319-4872-b879-97c537cf051c

	column row_id
		dataType: string
		lineageTag: 49ec237c-40cf-4e4e-8565-7fa7e1786b03
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column item_id
		dataType: string
		lineageTag: 3e557667-ab53-45fa-ab91-88c20f91bf7f
		summarizeBy: none
		sourceColumn: item_id

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: string
		lineageTag: 9f7f1d3b-574d-4423-a0d9-b5503ac09ee0
		summarizeBy: none
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column fiscal_year_end
		dataType: string
		lineageTag: bbc0a387-096f-4474-8df2-1e56f5e3a6d8
		summarizeBy: none
		sourceColumn: fiscal_year_end

		annotation SummarizationSetBy = Automatic

	column line_item
		dataType: string
		lineageTag: c30242ec-daf4-4fe5-892a-c87272395b49
		summarizeBy: none
		sourceColumn: line_item

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		lineageTag: 6c4f602a-b330-4b4a-a99a-acf154d6e69b
		summarizeBy: none
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: 580c250b-0c33-4411-8b75-7c139acd9239
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column basis
		dataType: string
		lineageTag: 7ea7d461-a4ef-425a-b6d2-7ec464e1dfe2
		summarizeBy: none
		sourceColumn: basis

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		lineageTag: be48f406-7159-4c6d-b0ba-2b1c03aa2fd1
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: 20e72d4d-cdaa-493f-8726-309390b6400b
		summarizeBy: none
		sourceColumn: url

		annotation SummarizationSetBy = Automatic

	column date_verified
		dataType: string
		lineageTag: de76f0d9-4b28-4b72-aa6e-9ba4db3c205b
		summarizeBy: none
		sourceColumn: date_verified

		annotation SummarizationSetBy = Automatic

	column confidence
		dataType: string
		lineageTag: 6c42f73e-33eb-4108-a4dd-ae6f034c3a64
		summarizeBy: none
		sourceColumn: confidence

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 012af116-9480-424b-b836-cb9df697eae9
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	column note
		dataType: string
		lineageTag: e05fd831-7ae4-4c96-81f1-8e2f867fb758
		summarizeBy: none
		sourceColumn: note

		annotation SummarizationSetBy = Automatic

	partition nfp_990_actuals = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_990_actuals.csv"),
				    [Delimiter = ",", Columns = 14, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "item_id", "fiscal_year", "fiscal_year_end", "line_item", "amount", "unit", "basis", "source", "url", "date_verified", "confidence", "value_class", "note"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"item_id", type text},
				    {"fiscal_year", type text},
				    {"fiscal_year_end", type text},
				    {"line_item", type text},
				    {"amount", type number},
				    {"unit", type text},
				    {"basis", type text},
				    {"source", type text},
				    {"url", type text},
				    {"date_verified", type text},
				    {"confidence", type text},
				    {"value_class", type text},
				    {"note", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
