/// CFO review: years in columns, target, variances, verdict with amounts, the FY2025 math, and the reading.
table nfp_cfo_review
	lineageTag: 5dd3a3fa-0fbd-48f1-9139-570a30f427b4

	column row_id
		dataType: string
		lineageTag: af9dfdc5-c9ee-4a4e-90ec-9a41a4c74b0f
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column ratio_kind
		dataType: string
		lineageTag: c5b6bc12-ba7a-4c3b-abf1-f16c5e7d2dff
		summarizeBy: none
		sourceColumn: ratio_kind

		annotation SummarizationSetBy = Automatic

	column ratio
		dataType: string
		lineageTag: 159b07e1-2e0e-4064-af93-a4f6436d16e0
		summarizeBy: none
		sourceColumn: ratio

		annotation SummarizationSetBy = Automatic

	column fy2025_value
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 90efef77-6370-4d34-8a11-b136913c9cc7
		summarizeBy: none
		sourceColumn: fy2025_value

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: ef9992f5-a1ca-44c5-a7f2-e8122e0f06ed
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column trend_fy2021_fy2025
		dataType: string
		lineageTag: ea7da200-de04-44e3-8066-97bf30b928a7
		summarizeBy: none
		sourceColumn: trend_fy2021_fy2025

		annotation SummarizationSetBy = Automatic

	column benchmark_or_policy
		dataType: string
		lineageTag: 527ff439-8497-4c19-8c57-ce15b73cf8bb
		summarizeBy: none
		sourceColumn: benchmark_or_policy

		annotation SummarizationSetBy = Automatic

	column vs_target
		dataType: string
		lineageTag: cce9a22d-e757-4069-8a85-72366f4f4b37
		summarizeBy: none
		sourceColumn: vs_target

		annotation SummarizationSetBy = Automatic

	column verdict_detail
		dataType: string
		lineageTag: e81119f0-9705-4984-8ab9-d96942a105f6
		summarizeBy: none
		sourceColumn: verdict_detail

		annotation SummarizationSetBy = Automatic

	column math_fy2025
		dataType: string
		lineageTag: d05bf168-595a-4eef-87f0-ec36e1a38fb5
		summarizeBy: none
		sourceColumn: math_fy2025

		annotation SummarizationSetBy = Automatic

	column cfo_reading
		dataType: string
		lineageTag: 98bcd3b5-366b-457f-8511-013a111c2319
		summarizeBy: none
		sourceColumn: cfo_reading

		annotation SummarizationSetBy = Automatic

	column reviewed_by
		dataType: string
		lineageTag: 50da3b02-cbdd-4a2a-9f07-a7650fd347c5
		summarizeBy: none
		sourceColumn: reviewed_by

		annotation SummarizationSetBy = Automatic

	column what_it_means
		dataType: string
		lineageTag: 4af21def-6ee6-42cb-9260-2398f0f04bf8
		summarizeBy: none
		sourceColumn: what_it_means

		annotation SummarizationSetBy = Automatic

	column fy2021
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: f5571f94-8ef2-4508-bcd8-e4452615b2e4
		summarizeBy: none
		sourceColumn: fy2021

		annotation SummarizationSetBy = Automatic

	column fy2022
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 0e49b30b-16ef-4f51-9e0e-802760302324
		summarizeBy: none
		sourceColumn: fy2022

		annotation SummarizationSetBy = Automatic

	column fy2023
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 3746396b-c660-4989-b511-807044ba9d13
		summarizeBy: none
		sourceColumn: fy2023

		annotation SummarizationSetBy = Automatic

	column fy2024
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: b489db5e-4d83-479f-9af4-dc6ee4f4366b
		summarizeBy: none
		sourceColumn: fy2024

		annotation SummarizationSetBy = Automatic

	column fy2025
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 6f30ac5d-ae32-4497-835b-500ca7fcd4b2
		summarizeBy: none
		sourceColumn: fy2025

		annotation SummarizationSetBy = Automatic

	column target_value
		dataType: double
		formatString: #,0.00;(#,0.00)
		lineageTag: 3ca5b1bd-a47a-42be-a42e-4015f052e559
		summarizeBy: none
		sourceColumn: target_value

		annotation SummarizationSetBy = Automatic

	column variance_to_target
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: e36e72e4-80c6-4dbf-9c62-d2b8a121a3b1
		summarizeBy: none
		sourceColumn: variance_to_target

		annotation SummarizationSetBy = Automatic

	column yoy_variance
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 7ac5ff08-fe25-4ac6-b7e0-8bdcb3d58273
		summarizeBy: none
		sourceColumn: yoy_variance

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 8e598240-e633-4fbf-90ae-c75cc93748b3
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	partition nfp_cfo_review = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_cfo_review.csv"),
				    [Delimiter = ",", Columns = 22, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "ratio_kind", "ratio", "fy2025_value", "unit", "trend_fy2021_fy2025", "benchmark_or_policy", "vs_target", "verdict_detail", "math_fy2025", "cfo_reading", "reviewed_by", "what_it_means", "fy2021", "fy2022", "fy2023", "fy2024", "fy2025", "target_value", "variance_to_target", "yoy_variance", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"ratio_kind", type text},
				    {"ratio", type text},
				    {"fy2025_value", type number},
				    {"unit", type text},
				    {"trend_fy2021_fy2025", type text},
				    {"benchmark_or_policy", type text},
				    {"vs_target", type text},
				    {"verdict_detail", type text},
				    {"math_fy2025", type text},
				    {"cfo_reading", type text},
				    {"reviewed_by", type text},
				    {"what_it_means", type text},
				    {"fy2021", type number},
				    {"fy2022", type number},
				    {"fy2023", type number},
				    {"fy2024", type number},
				    {"fy2025", type number},
				    {"target_value", type number},
				    {"variance_to_target", type number},
				    {"yoy_variance", type number},
				    {"value_class", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
