/// CFO review: years in columns, target, variances, verdict with amounts, reading.
table nfp_cfo_review
	lineageTag: 88c46618-2753-42f3-908e-a1fb07fff2be

	column row_id
		dataType: string
		lineageTag: a6c58ef1-159a-48d2-8bf2-4691c14a5991
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column ratio_kind
		dataType: string
		lineageTag: 93554b4d-2cd0-4360-a521-ac8919da0aae
		summarizeBy: none
		sourceColumn: ratio_kind

		annotation SummarizationSetBy = Automatic

	column ratio
		dataType: string
		lineageTag: b2e87743-a5c2-45e2-bcdc-42b9baac4dee
		summarizeBy: none
		sourceColumn: ratio

		annotation SummarizationSetBy = Automatic

	column fy2025_value
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: e41a37e8-35ca-4158-ac46-2781540bfa39
		summarizeBy: none
		sourceColumn: fy2025_value

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: 4c06ad24-1f9d-42b4-9f60-5cd25379dc90
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column trend_fy2021_fy2025
		dataType: string
		lineageTag: 0fbd992d-9fe3-447b-9852-e692f1299494
		summarizeBy: none
		sourceColumn: trend_fy2021_fy2025

		annotation SummarizationSetBy = Automatic

	column benchmark_or_policy
		dataType: string
		lineageTag: 0b99f879-1ec0-44ad-a0d7-fd5f137f3f1e
		summarizeBy: none
		sourceColumn: benchmark_or_policy

		annotation SummarizationSetBy = Automatic

	column vs_target
		dataType: string
		lineageTag: 35fa472a-41ac-4a6c-820d-a11a7336476f
		summarizeBy: none
		sourceColumn: vs_target

		annotation SummarizationSetBy = Automatic

	column verdict_detail
		dataType: string
		lineageTag: 91ee35b5-8712-450e-9241-740a2d3b272d
		summarizeBy: none
		sourceColumn: verdict_detail

		annotation SummarizationSetBy = Automatic

	column cfo_reading
		dataType: string
		lineageTag: eb8cbfd2-2452-4be1-8720-dae596ff5272
		summarizeBy: none
		sourceColumn: cfo_reading

		annotation SummarizationSetBy = Automatic

	column fy2021
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 7e38b56c-026e-4c87-ad04-8844ddc90a43
		summarizeBy: none
		sourceColumn: fy2021

		annotation SummarizationSetBy = Automatic

	column fy2022
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: b964842d-e639-46fd-9bbc-8364a1978b6e
		summarizeBy: none
		sourceColumn: fy2022

		annotation SummarizationSetBy = Automatic

	column fy2023
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: e69b3b1a-7c8e-4b19-8733-cc62cee6184e
		summarizeBy: none
		sourceColumn: fy2023

		annotation SummarizationSetBy = Automatic

	column fy2024
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 9d092553-8b71-4ff2-be96-60f7bcb037c8
		summarizeBy: none
		sourceColumn: fy2024

		annotation SummarizationSetBy = Automatic

	column fy2025
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: ed749120-ee10-44b4-b07b-026466177404
		summarizeBy: none
		sourceColumn: fy2025

		annotation SummarizationSetBy = Automatic

	column target_value
		dataType: double
		formatString: #,0.00;(#,0.00)
		lineageTag: 3a33e09d-a6d9-483b-af16-4a2e17712ad4
		summarizeBy: none
		sourceColumn: target_value

		annotation SummarizationSetBy = Automatic

	column variance_to_target
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 5d03ef57-bdb4-4a07-8908-893c1871150d
		summarizeBy: none
		sourceColumn: variance_to_target

		annotation SummarizationSetBy = Automatic

	column yoy_variance
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: aeef9ca3-5b30-4579-a599-d9a8c912488a
		summarizeBy: none
		sourceColumn: yoy_variance

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 6f5b8213-ce25-42f5-82f5-3c6362231fbc
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	partition nfp_cfo_review = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_cfo_review.csv"),
				    [Delimiter = ",", Columns = 19, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "ratio_kind", "ratio", "fy2025_value", "unit", "trend_fy2021_fy2025", "benchmark_or_policy", "vs_target", "verdict_detail", "cfo_reading", "fy2021", "fy2022", "fy2023", "fy2024", "fy2025", "target_value", "variance_to_target", "yoy_variance", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"ratio_kind", type text},
				    {"ratio", type text},
				    {"fy2025_value", type number},
				    {"unit", type text},
				    {"trend_fy2021_fy2025", type text},
				    {"benchmark_or_policy", type text},
				    {"vs_target", type text},
				    {"verdict_detail", type text},
				    {"cfo_reading", type text},
				    {"fy2021", type number},
				    {"fy2022", type number},
				    {"fy2023", type number},
				    {"fy2024", type number},
				    {"fy2025", type number},
				    {"target_value", type number},
				    {"variance_to_target", type number},
				    {"yoy_variance", type number},
				    {"value_class", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
