/// Curated NFP export: cumulative position of the five capital alternatives, years 0-5.
table nfp_alt_timeline
	lineageTag: 00021159-3448-47c8-8312-035393d3d872

	column row_id
		dataType: string
		lineageTag: d652ba30-d437-4de1-99f8-783249133d13
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column year
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: a5c88594-5ad6-4ec5-9d3a-d4112e63a8e7
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column expand_program
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 240d6c03-6146-48b8-ac07-b999ef3303b3
		summarizeBy: none
		sourceColumn: expand_program

		annotation SummarizationSetBy = Automatic

	column launch_program
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 11666cc6-d203-4d95-9c78-9e6655926406
		summarizeBy: none
		sourceColumn: launch_program

		annotation SummarizationSetBy = Automatic

	column invest_capital
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 8c9a65a5-f785-4b22-a094-c5ea368ff368
		summarizeBy: none
		sourceColumn: invest_capital

		annotation SummarizationSetBy = Automatic

	column retain_cash
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: b5fd6e6a-2d6e-4d16-8294-a13c1a5f5382
		summarizeBy: none
		sourceColumn: retain_cash

		annotation SummarizationSetBy = Automatic

	column capital_project
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: fdd22d75-20f6-4559-9448-99c7022416ea
		summarizeBy: none
		sourceColumn: capital_project

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 70129f8f-17d3-4334-a7bf-b0260cda0760
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	partition nfp_alt_timeline = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_alt_timeline.csv"),
				    [Delimiter = ",", Columns = 8, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "year", "expand_program", "launch_program", "invest_capital", "retain_cash", "capital_project", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"year", type number},
				    {"expand_program", type number},
				    {"launch_program", type number},
				    {"invest_capital", type number},
				    {"retain_cash", type number},
				    {"capital_project", type number},
				    {"value_class", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
