/// FILED 990 figures in classic statement presentation with FY2025-vs-FY2024 variance in $ and %.
table nfp_fin_statements
	lineageTag: c2377970-5b77-4de8-b289-655ece84bc57

	column row_id
		dataType: string
		lineageTag: 419ae675-8a88-4eaf-b2db-99380695034f
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column statement
		dataType: string
		lineageTag: 2c8bf8f8-a7b9-41c6-98f4-e06ec9dd78e8
		summarizeBy: none
		sourceColumn: statement

		annotation SummarizationSetBy = Automatic

	column section
		dataType: string
		lineageTag: 603f62bf-c430-4d04-9057-60c3dabc9708
		summarizeBy: none
		sourceColumn: section

		annotation SummarizationSetBy = Automatic

	column line_label
		dataType: string
		lineageTag: 0deb5e7a-4c35-48c2-8ca7-199acfaeb0bb
		summarizeBy: none
		sourceColumn: line_label

		annotation SummarizationSetBy = Automatic

	column fy2021
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 5d8a0c08-5159-4030-8236-4cd3796220b6
		summarizeBy: none
		sourceColumn: fy2021

		annotation SummarizationSetBy = Automatic

	column fy2022
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 7f44be75-5dfa-4c6d-9695-e09eb9ae87f5
		summarizeBy: none
		sourceColumn: fy2022

		annotation SummarizationSetBy = Automatic

	column fy2023
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 8d152b8d-a56b-4d41-a8c9-e9ea6789e6b5
		summarizeBy: none
		sourceColumn: fy2023

		annotation SummarizationSetBy = Automatic

	column fy2024
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 771405c7-7f5f-4565-bfb6-8b09c48c3d6b
		summarizeBy: none
		sourceColumn: fy2024

		annotation SummarizationSetBy = Automatic

	column fy2025
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 71b032a0-ba54-4de7-bf48-60772f07106a
		summarizeBy: none
		sourceColumn: fy2025

		annotation SummarizationSetBy = Automatic

	column note
		dataType: string
		lineageTag: e8d4c2cc-984d-413c-9601-b6dfa99d08c1
		summarizeBy: none
		sourceColumn: note

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 6a09dee7-caf6-4aa3-88e5-ed31503b413c
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	column var_25v24
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 515cd36e-297b-4c06-83a6-dee2084693a4
		summarizeBy: none
		sourceColumn: var_25v24

		annotation SummarizationSetBy = Automatic

	column var_25v24_pct
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 308b4a92-5cf0-4cf8-a7a6-c1eba59131b9
		summarizeBy: none
		sourceColumn: var_25v24_pct

		annotation SummarizationSetBy = Automatic

	partition nfp_fin_statements = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_fin_statements.csv"),
				    [Delimiter = ",", Columns = 13, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "statement", "section", "line_label", "fy2021", "fy2022", "fy2023", "fy2024", "fy2025", "note", "value_class", "var_25v24", "var_25v24_pct"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"statement", type text},
				    {"section", type text},
				    {"line_label", type text},
				    {"fy2021", type number},
				    {"fy2022", type number},
				    {"fy2023", type number},
				    {"fy2024", type number},
				    {"fy2025", type number},
				    {"note", type text},
				    {"value_class", type text},
				    {"var_25v24", type number},
				    {"var_25v24_pct", type number}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
