/// KPI register with target, variance to target, prior year and YoY variance, plus audience (board vs CEO).
table nfp_990_kpis
	lineageTag: f37561e0-7fb4-4416-aae3-f056ece02438

	column row_id
		dataType: string
		lineageTag: 71629a99-7889-488b-bcf6-3d4061bfa3d4
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column kpi_id
		dataType: string
		lineageTag: b3cc1021-5c3b-4a71-8b4f-def1252714ab
		summarizeBy: none
		sourceColumn: kpi_id

		annotation SummarizationSetBy = Automatic

	column kpi
		dataType: string
		lineageTag: bd168801-60f5-4ebf-ab6d-48785b7a497a
		summarizeBy: none
		sourceColumn: kpi

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 65121f22-1768-4d28-92d9-af694c3fb7d1
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column formula_990
		dataType: string
		lineageTag: 0a69402a-fa1c-4d3a-b16a-cb96dae07994
		summarizeBy: none
		sourceColumn: formula_990

		annotation SummarizationSetBy = Automatic

	column fy2025_value
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: b55a256f-b697-4151-badc-cde9e9ce0a0b
		summarizeBy: none
		sourceColumn: fy2025_value

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: de11c6e4-fe5e-43df-8ce3-da7ccbaeb62a
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column benchmark_or_policy
		dataType: string
		lineageTag: a4289acc-288f-42e1-bc90-bda3b5ac31f9
		summarizeBy: none
		sourceColumn: benchmark_or_policy

		annotation SummarizationSetBy = Automatic

	column target_class
		dataType: string
		lineageTag: 3e316b9e-25fc-4f37-8327-b8b2e4fa7365
		summarizeBy: none
		sourceColumn: target_class

		annotation SummarizationSetBy = Automatic

	column vs_target
		dataType: string
		lineageTag: 927a6163-7cf1-482a-ad7f-798acadaf979
		summarizeBy: none
		sourceColumn: vs_target

		annotation SummarizationSetBy = Automatic

	column trend_fy2021_fy2025
		dataType: string
		lineageTag: 84826d66-5365-4765-83ef-e43183a0ab88
		summarizeBy: none
		sourceColumn: trend_fy2021_fy2025

		annotation SummarizationSetBy = Automatic

	column typical_audience
		dataType: string
		lineageTag: b4b97db8-f9ec-41f2-a830-b18291257133
		summarizeBy: none
		sourceColumn: typical_audience

		annotation SummarizationSetBy = Automatic

	column target_value
		dataType: double
		formatString: #,0.00;(#,0.00)
		lineageTag: dd411017-b095-4eaa-8b97-64446872367d
		summarizeBy: none
		sourceColumn: target_value

		annotation SummarizationSetBy = Automatic

	column variance_to_target
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 9d23d1df-41a3-4c35-ad87-fc184bc315ee
		summarizeBy: none
		sourceColumn: variance_to_target

		annotation SummarizationSetBy = Automatic

	column fy2024_value
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 83c45d8a-2930-46d8-8e32-e0c8a1a46f4e
		summarizeBy: none
		sourceColumn: fy2024_value

		annotation SummarizationSetBy = Automatic

	column yoy_variance
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: b0d9b6c6-7a9e-41a5-ac41-faaa8e2b9391
		summarizeBy: none
		sourceColumn: yoy_variance

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 9dd7d1b8-45ef-4e5b-b7a7-8fad46634ea6
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	partition nfp_990_kpis = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_990_kpis.csv"),
				    [Delimiter = ",", Columns = 17, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "kpi_id", "kpi", "description", "formula_990", "fy2025_value", "unit", "benchmark_or_policy", "target_class", "vs_target", "trend_fy2021_fy2025", "typical_audience", "target_value", "variance_to_target", "fy2024_value", "yoy_variance", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"kpi_id", type text},
				    {"kpi", type text},
				    {"description", type text},
				    {"formula_990", type text},
				    {"fy2025_value", type number},
				    {"unit", type text},
				    {"benchmark_or_policy", type text},
				    {"target_class", type text},
				    {"vs_target", type text},
				    {"trend_fy2021_fy2025", type text},
				    {"typical_audience", type text},
				    {"target_value", type number},
				    {"variance_to_target", type number},
				    {"fy2024_value", type number},
				    {"yoy_variance", type number},
				    {"value_class", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
