/// Playbook ratios computed from the FILED 990 figures for every filed year - ratio_kind filters one ratio across years for trend charts.
table nfp_990_ratio_actuals
	lineageTag: c8fd50ab-af84-4aa9-80a0-46487c0eec90

	measure '990 Op Margin FY25 %' =
			
			CALCULATE(SUM(nfp_990_ratio_actuals[value]), nfp_990_ratio_actuals[ratio_id] = "R990-op_margin_pct-FY2025")
		formatString: 0.00
		displayFolder: NFP Cards
		lineageTag: f0d8da79-462d-47cf-8526-41b2171500c2

	measure '990 Months Cash FY25' =
			
			CALCULATE(SUM(nfp_990_ratio_actuals[value]), nfp_990_ratio_actuals[ratio_id] = "R990-months_cash_on_hand-FY2025")
		formatString: 0.00
		displayFolder: NFP Cards
		lineageTag: 87281821-01a7-4531-8bdc-c3a68398836d

	measure '990 Revenue Growth FY25 %' =
			
			CALCULATE(SUM(nfp_990_ratio_actuals[value]), nfp_990_ratio_actuals[ratio_id] = "R990-revenue_growth_pct-FY2025")
		formatString: 0.00
		displayFolder: NFP Cards
		lineageTag: 39a256e0-b0f8-4e1f-88ae-ee3a791c6e31

	measure '990 Real Ratios' =
			
			COUNTROWS(FILTER(nfp_990_ratio_actuals, NOT ISBLANK(nfp_990_ratio_actuals[value])))
		formatString: 0
		displayFolder: NFP Cards
		lineageTag: 113e8c96-6745-45f0-900f-9cf68a0737df

	column row_id
		dataType: string
		lineageTag: 2533d53d-3fe6-4e99-a8a3-1682c436a515
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column ratio_id
		dataType: string
		lineageTag: 44e48d7a-05de-4c99-a1d2-cc67131acf47
		summarizeBy: none
		sourceColumn: ratio_id

		annotation SummarizationSetBy = Automatic

	column ratio_kind
		dataType: string
		lineageTag: 340f0a0d-4575-490b-bc17-dd6c1d6bcd1a
		summarizeBy: none
		sourceColumn: ratio_kind

		annotation SummarizationSetBy = Automatic

	column ratio
		dataType: string
		lineageTag: c01f12df-fea5-49fb-b696-fdec53196ca5
		summarizeBy: none
		sourceColumn: ratio

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: string
		lineageTag: 5f66932e-132c-4e3c-84b4-d6b12d51a575
		summarizeBy: none
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		lineageTag: ce7a7254-3ede-421b-85fb-88413137b149
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: 2db67ac0-5be0-4d36-9809-1c263fa51112
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column formula_990
		dataType: string
		lineageTag: 10d4fa79-1542-4daf-bacc-7fc8bf6d0496
		summarizeBy: none
		sourceColumn: formula_990

		annotation SummarizationSetBy = Automatic

	column basis
		dataType: string
		lineageTag: ca271fda-cc88-4593-90a0-3e4b229eacbf
		summarizeBy: none
		sourceColumn: basis

		annotation SummarizationSetBy = Automatic

	column confidence
		dataType: string
		lineageTag: ea88fe58-8870-438d-869c-3defeb5c474b
		summarizeBy: none
		sourceColumn: confidence

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: 40140391-0e95-47d5-a8b4-a8e3f156857e
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	column note
		dataType: string
		lineageTag: 4f24767b-55f2-46c4-8b2f-9b890b68e1fe
		summarizeBy: none
		sourceColumn: note

		annotation SummarizationSetBy = Automatic

	partition nfp_990_ratio_actuals = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_990_ratio_actuals.csv"),
				    [Delimiter = ",", Columns = 12, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "ratio_id", "ratio_kind", "ratio", "fiscal_year", "value", "unit", "formula_990", "basis", "confidence", "value_class", "note"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"ratio_id", type text},
				    {"ratio_kind", type text},
				    {"ratio", type text},
				    {"fiscal_year", type text},
				    {"value", type number},
				    {"unit", type text},
				    {"formula_990", type text},
				    {"basis", type text},
				    {"confidence", type text},
				    {"value_class", type text},
				    {"note", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
