/// KPI register with target, variances, verdict with amounts, audience and description.
table nfp_990_kpis
	lineageTag: 13d70371-544c-4299-9f0f-aaa28e24c9b0

	column row_id
		dataType: string
		lineageTag: f49b6d7b-9690-4cb4-8fbc-53a808378957
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column kpi_id
		dataType: string
		lineageTag: 60921f3e-40fb-4e6c-96bb-52dfa1ef5cc8
		summarizeBy: none
		sourceColumn: kpi_id

		annotation SummarizationSetBy = Automatic

	column kpi
		dataType: string
		lineageTag: 7067f63c-4108-47f5-853d-35703d45ac3e
		summarizeBy: none
		sourceColumn: kpi

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 17bc5ec3-fd1f-49a8-b5f8-83e638ca43e9
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column formula_990
		dataType: string
		lineageTag: 5aea3a52-3703-4fa7-a3d4-d56caa44f32d
		summarizeBy: none
		sourceColumn: formula_990

		annotation SummarizationSetBy = Automatic

	column fy2025_value
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: e5d120be-2ac8-4808-a228-a5800202ca69
		summarizeBy: none
		sourceColumn: fy2025_value

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: e8cb672d-0d92-402b-b2c8-f07ba0065669
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column benchmark_or_policy
		dataType: string
		lineageTag: 6eb1787b-6d67-43ed-b3d7-0362851e512c
		summarizeBy: none
		sourceColumn: benchmark_or_policy

		annotation SummarizationSetBy = Automatic

	column target_class
		dataType: string
		lineageTag: a661ffd2-1c0a-4357-a458-78f1466198bb
		summarizeBy: none
		sourceColumn: target_class

		annotation SummarizationSetBy = Automatic

	column vs_target
		dataType: string
		lineageTag: 13ff8008-7fc3-4f4d-a20f-9ba90495457e
		summarizeBy: none
		sourceColumn: vs_target

		annotation SummarizationSetBy = Automatic

	column verdict_detail
		dataType: string
		lineageTag: 2980c179-a2b8-4d49-bc61-f166679a1f8b
		summarizeBy: none
		sourceColumn: verdict_detail

		annotation SummarizationSetBy = Automatic

	column trend_fy2021_fy2025
		dataType: string
		lineageTag: 4dbf8db5-a3b7-48c1-ba31-7df543aad4ed
		summarizeBy: none
		sourceColumn: trend_fy2021_fy2025

		annotation SummarizationSetBy = Automatic

	column typical_audience
		dataType: string
		lineageTag: 30a4596e-1fa6-439a-950d-61af8dc4866d
		summarizeBy: none
		sourceColumn: typical_audience

		annotation SummarizationSetBy = Automatic

	column target_value
		dataType: double
		formatString: #,0.00;(#,0.00)
		lineageTag: 1893a2dd-49ff-4faa-9166-c2b50504fc3d
		summarizeBy: none
		sourceColumn: target_value

		annotation SummarizationSetBy = Automatic

	column variance_to_target
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 541c329c-fdaa-4bb2-818e-f04ff3bcea26
		summarizeBy: none
		sourceColumn: variance_to_target

		annotation SummarizationSetBy = Automatic

	column fy2024_value
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 139d5920-dac7-4642-a32e-6b5e280c3a54
		summarizeBy: none
		sourceColumn: fy2024_value

		annotation SummarizationSetBy = Automatic

	column yoy_variance
		dataType: double
		formatString: #,0.##;(#,0.##)
		lineageTag: 36d93746-74be-4237-97af-0e9255993a86
		summarizeBy: none
		sourceColumn: yoy_variance

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: e2cacdcd-c844-4599-a85f-a9c2edebf3c1
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	partition nfp_990_kpis = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_990_kpis.csv"),
				    [Delimiter = ",", Columns = 18, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "kpi_id", "kpi", "description", "formula_990", "fy2025_value", "unit", "benchmark_or_policy", "target_class", "vs_target", "verdict_detail", "trend_fy2021_fy2025", "typical_audience", "target_value", "variance_to_target", "fy2024_value", "yoy_variance", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"kpi_id", type text},
				    {"kpi", type text},
				    {"description", type text},
				    {"formula_990", type text},
				    {"fy2025_value", type number},
				    {"unit", type text},
				    {"benchmark_or_policy", type text},
				    {"target_class", type text},
				    {"vs_target", type text},
				    {"verdict_detail", type text},
				    {"trend_fy2021_fy2025", type text},
				    {"typical_audience", type text},
				    {"target_value", type number},
				    {"variance_to_target", type number},
				    {"fy2024_value", type number},
				    {"yoy_variance", type number},
				    {"value_class", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
