/// KPI register: description, 990 formula, latest value, benchmark or board policy, verdict, 5-year path, and the audience that typically reviews it (board vs CEO).
table nfp_990_kpis
	lineageTag: f4f082b2-baa1-4119-a70f-fe6e4597fa1b

	column row_id
		dataType: string
		lineageTag: 260f07a6-0cd4-439e-8677-fe539d702db2
		summarizeBy: none
		sourceColumn: row_id

		annotation SummarizationSetBy = Automatic

	column kpi_id
		dataType: string
		lineageTag: f0aeb3b5-2840-4904-a2e0-a37141085377
		summarizeBy: none
		sourceColumn: kpi_id

		annotation SummarizationSetBy = Automatic

	column kpi
		dataType: string
		lineageTag: d4cdc4e9-e293-424d-80b1-62e3ececb252
		summarizeBy: none
		sourceColumn: kpi

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 8bab5d5a-35de-4650-940b-f1510d3bcb98
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column formula_990
		dataType: string
		lineageTag: 2e037be0-e717-45ab-99b5-f99d5c4dc429
		summarizeBy: none
		sourceColumn: formula_990

		annotation SummarizationSetBy = Automatic

	column fy2025_value
		dataType: double
		formatString: #,0.##
		lineageTag: 4974a16d-c9e7-4da1-a5dd-487d4a65159d
		summarizeBy: none
		sourceColumn: fy2025_value

		annotation SummarizationSetBy = Automatic

	column unit
		dataType: string
		lineageTag: a9910c24-990a-4a85-bd5a-9503ff3eb0c3
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column benchmark_or_policy
		dataType: string
		lineageTag: 61098c9d-cdb4-4e47-aab4-6af506a9f604
		summarizeBy: none
		sourceColumn: benchmark_or_policy

		annotation SummarizationSetBy = Automatic

	column target_class
		dataType: string
		lineageTag: 6227e0cb-f702-4ef6-939b-75fac9672651
		summarizeBy: none
		sourceColumn: target_class

		annotation SummarizationSetBy = Automatic

	column vs_target
		dataType: string
		lineageTag: 72256122-fbed-489c-afbf-923b4b3ff3fc
		summarizeBy: none
		sourceColumn: vs_target

		annotation SummarizationSetBy = Automatic

	column trend_fy2021_fy2025
		dataType: string
		lineageTag: 67583dff-1f23-4b85-8cfa-2edc29d5b4ac
		summarizeBy: none
		sourceColumn: trend_fy2021_fy2025

		annotation SummarizationSetBy = Automatic

	column typical_audience
		dataType: string
		lineageTag: f62015ef-cc7a-4dc8-a444-391698f665b8
		summarizeBy: none
		sourceColumn: typical_audience

		annotation SummarizationSetBy = Automatic

	column value_class
		dataType: string
		lineageTag: bb0e9733-6da8-4f5a-ba75-969ddbf591b4
		summarizeBy: none
		sourceColumn: value_class

		annotation SummarizationSetBy = Automatic

	partition nfp_990_kpis = m
		mode: import
		source =
				let
				  Source = Csv.Document(
				    File.Contents("C:\dev\Finance-ML\reports\nfp_990_kpis.csv"),
				    [Delimiter = ",", Columns = 13, QuoteStyle = QuoteStyle.Csv]
				),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Selected columns" = Table.SelectColumns(#"Promoted headers", {"row_id", "kpi_id", "kpi", "description", "formula_990", "fy2025_value", "unit", "benchmark_or_policy", "target_class", "vs_target", "trend_fy2021_fy2025", "typical_audience", "value_class"}),
				  #"Changed Type" = Table.TransformColumnTypes(#"Selected columns", {
				    {"row_id", type text},
				    {"kpi_id", type text},
				    {"kpi", type text},
				    {"description", type text},
				    {"formula_990", type text},
				    {"fy2025_value", type number},
				    {"unit", type text},
				    {"benchmark_or_policy", type text},
				    {"target_class", type text},
				    {"vs_target", type text},
				    {"trend_fy2021_fy2025", type text},
				    {"typical_audience", type text},
				    {"value_class", type text}
				  })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
